<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-file-o" aria-hidden="true"></i>
					<?php echo $this->translate('View File'); ?>
				</h3>
				<div class="box-tools">
					
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username"><?php echo $this->fileEntity->getFileName();?></h3>
				<p class="text-muted"><?php echo $this->fileEntity->getFileTitle(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('Path'); ?>:</b>
						<a class="pull-right"><?php echo APPLICATION_PATH . '/' .$this->fileEntity->getFilePath(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Mime Type'); ?>:</b>
						<a class="pull-right"><?php echo $this->fileEntity->getFileMime(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Size'); ?>:</b>
						<a class="pull-right"><?php echo $this->fileEntity->getFileSize()?> <?php echo $this->translate('bytes');?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Created'); ?>:</b>
						<a class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $this->fileEntity->getFileCreate());?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>