<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-user"></i>
					<?php echo $this->translate('Delete Employee'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
    		<div class="box-body">
    			<div class="alert alert-warning">
    				<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following employee?'); ?></p>
    			</div>
    			<h3 class="profile-username"><?php echo $this->employeeEntity->getEmployeeName(); ?></h3>
    			<p class="text-muted"><?php echo $this->employeeEntity->getEmployeeTitle(); ?></p>
    			<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
    		</div>
    	</div>
	</div>
</div>