<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-gears"></i>
					<?php echo $this->translate('Cron'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('cron-create');?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			
			<?php if($this->paginator->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No Cron Jobs'); ?>
				</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-bordered table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate('Command'); ?></th>
							<th><?php echo $this->translate('Run Once'); ?></th>
							<th><?php echo $this->translate('Minute'); ?></th>
							<th><?php echo $this->translate('Hour'); ?></th>
							<th><?php echo $this->translate('Day Of Month'); ?></th>
							<th><?php echo $this->translate('Month'); ?></th>
							<th><?php echo $this->translate('Last Run'); ?></th>
							<th><?php echo $this->translate('Enabled'); ?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $entity):?>
						<tr>
							<td><?php echo $entity->getCronCommand(); ?></td>
							<td><?php echo $entity->getCronRunOnce();?></td>
							<td><?php echo $entity->getCronMinute(); ?></td>
							<td><?php echo $entity->getCronHour(); ?></td>
							<td><?php echo $entity->getCronDom(); ?></td>
							<td><?php echo $entity->getCronMonth(); ?></td>
							<td>
								<?php if($entity->getCronLastRun() > 0): ?>
									<?php echo date($this->appConfig()->getCOnfigDateLong(), $entity->getCronLastRun()); ?>
								<?php else: ?>
									<?php echo $this->translate('N/A'); ?>
								<?php endif; ?>		
							</td>
							<td><?php echo $entity->getCronEnabled();?></td>
							<td class="text-right">
								<a href="<?php echo $this->url('cron-update', array('cronId' => $entity->getCronId()));?>" title="<?php echo $this->translate('Edit this cron'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif;?>
			</div>
		</div>
	</div>
</div>