<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Delete Work Order Part'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following work order part?'); ?></p>
				</div>
				<h3 class="profile-username"><?php echo $this->partEntity->getWorkorderPartsDescription(); ?></h3>
				<p class="text-muted"><?php echo $this->currencyFormat($this->partEntity->getWorkorderPartsAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('Qty')?>: </b>
						<span class="text-right"><?php echo $this->partEntity->getWorkorderPartsQty();?></span>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Total')?>:</b>
						<span class="text-right"><?php echo $this->currencyFormat($this->partEntity->getWorkorderPartsTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></span>
					</li>
				</ul>
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                 </form>
			</div>
		</div>
	</div>
</div>