<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
 <div class="row">
 	<div class="col-xs-12 col-sm-6">
 		<div class="box box-primary">
 			<div class="box-header with-border">
 				<h3 class="box-title">
 					<i class="fa fa-user"></i>
 					<?php echo $this->translate('My Info'); ?>
				</h3>
 				<div class="box-tools">
 				
 				</div>
 			</div>
 			<div class="box-body box-profile">
 				<h3 class="profile-username"><?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?></h3>
 				<p class="text-muted"><?php echo $this->userEntity->getUserJobTitle(); ?></p>
 				<ul class="list-group list-group-unbordered">
 					<li class="list-group-item">
     					<b><?php echo $this->translate('E-Mail'); ?></b> <a class="pull-right"><?php echo $this->userEntity->getUserEmail(); ?></a>
     				</li>
     				<li class="list-group-item">
     					<b><?php echo $this->translate('Phone'); ?></b> 
     					<a class="pull-right"><?php echo $this->userEntity->getPhoneEntity()->getPhoneNum();?></a>
     				</li>
     				<li class="list-group-item">
     					<b><?php echo $this->translate('Adddress'); ?></b> 
     					<a class="pull-right">
     					
     					</a>
     				</li>
     				<li class="list-group-item">
     					<b><?php echo $this->translate('Status'); ?></b> 
     					<a class="pull-right"><?php echo $this->userEntity->getUserStatus(); ?></a>
     				</li>
 				</ul>
 			</div>
 		</div>
 	</div>
 	 	<div class="col-xs-12 col-sm-6">
 		<div class="box box-primary">
 			<div class="box-header with-border">
 				<h3 class="box-title">
 					<i class="fa fa-cog"></i>
 					<?php echo $this->translate('My Auth'); ?>
 				</h3>
 				<div class="box-tools">
 				
 				</div>
 				
 			</div>
 			<div class="box-body box-profile">
 				<h3 class="profile-username">
 					<?php echo $this->identity()->getAuthName(); ?>
 				</h3>
 				<p class="text-muted"><?php echo $this->identity()->getAuthEmail(); ?></p>
 				<ul class="list-group list-group-unbordered">
 					<li class="list-group-item">
     				 	<b><?php echo $this->translate('Role');?></b> 
     				 	<a class="pull-right"><?php echo $this->identity()->getAuthRole(); ?></a>
     				 </li>
     				 <li class="list-group-item">
     				 	<b><?php echo $this->translate('Type'); ?></b> 
     				 	<a class="pull-right"><?php echo $this->identity()->getAuthType(); ?></a>
      				 </li>
      				 <li class="list-group-item">
      				 	<b><?php echo $this->translate('Last Sign In'); ?></b> 
      				 	<a class="pull-right"><?php echo ($this->identity()->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $this->identity()->getAuthLastLogin()) : $this->translate('Never Signed In'); ?></a>
      				 </li>
      				 <li class="list-group-item">
      				 	<b><?php echo $this->translate('Ip Address');?></b> 
      				 	<a class="pull-right"><?php echo ($this->identity()->getAuthLastIp() != null) ? $this->identity()->getAuthLastIp() : $this->translate('Never Signed In'); ?></a>
      				 </li>
 				</ul>
 			</div>
 		</div>
 	</div>
 </div>
 <div class="row">
 	<div class="col-xs-12 col-sm-4">
 		<?php echo $this->Ticket($this->userEntity->getClientId(), 'Open', $this->identity->getUser); ?>
 	</div>
 </div>