<table class="table table-hover">
	<thead>
		<tr>
			<th><?php echo $this->translate('Invoice'); ?></th>
			<th><?php echo $this->translate('Due Date'); ?>
			<th><?php echo $this->translate('Total'); ?></th>
			<th><?php echo $this->translate('Status'); ?></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->subscriptionInvoiceEntitys as $entity): ?>
		<tr>
			<td><a href="<?php echo $this->url('invoice-view', array('clientId' => $entity->getInvoiceEntity()->getClientId(), 'invoiceId' => $entity->getInvoiceEntity()->getInvoiceId())); ?>" 
				title="<?php echo $this->translate('View this invoice'); ?>">
					<?php echo $entity->getInvoiceEntity()->getInvoiceId(); ?>
				</a>
			</td>
			<td><?php echo date($this->appConfig()->getConfigDateShort(), $entity->getInvoiceEntity()->getInvoiceDate()); ?></td>
			<td><?php echo $this->currencyFormat($entity->getInvoiceEntity()->getInvoiceTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
			<td><?php echo $entity->getInvoiceEntity()->getInvoiceStatus(); ?></td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>