<?php if($this->entitys->count() == 0): ?>
<div class="box-body">
	<div class="alert alert-info">
		<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No users allowed'); ?></p>
	</div>
</div>
<?php else: ?>
<div class="box-body table-responsive no-padding">
    <table class="table table-hover table-striped table-condensed">
    	<thead>
    		<tr>
    			<th><?php echo $this->translate('Name')?></th>
    			<th></th>
    		</tr>
    	</thead>
    	<tbody>
    	<?php foreach($this->entitys as $entity): ?>
    		<tr>
    			<td>
    				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
    				<a href="<?php echo $this->url('user-view', array('clientId' => $entity->getUserEntity()->getClientId(), 'userId' => $entity->getUserId)); ?>" 
    					title="<?php echo $this->translate('View this user'); ?>">
    					<?php echo $entity->getUserEntity()->getUserNameFirst(); ?> <?php echo $entity->getUserEntity()->getUserNameLast(); ?>
    				</a>
    				<?php else: ?>
    				<?php echo $entity->getUserEntity()->getUserNameFirst(); ?> <?php echo $entity->getUserEntity()->getUserNameLast(); ?>
    				<?php endif;?>
    			</td>
    			<td class="text-right">
    				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'subscription-user-delete') ):?>
    				<a href="<?php echo $this->url('subscription-user-delete', array('clientId' => $entity->getUserEntity()->getClientId(), 'subscriptionUserId' => $entity->getSubscriptionUserId(), 'subscriptionId' => $entity->getSubscriptionId())); ?>" 
    					title="<?php echo $this->translate('Remove user from subscription'); ?>" class="btn btn-box-tool">
    						<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
    				</a>
    				<?php endif; ?>
    			</td>
    		</tr>
    	<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?php endif;?>