<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->translate('View Host Type'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('host-type-delete', array('hostTypeId' => $this->typeEntity->getHostTypeId())); ?>" title="<?php echo $this->translate('Delete this host type'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('host-type-update', array('hostTypeId' => $this->typeEntity->getHostTypeId())); ?>" title="<?php echo $this->translate('Edit this host type'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username"><?php echo $this->typeEntity->getHostTypeName(); ?></h3>
			</div>
		</div>
	</div>
</div>
			