<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->translate('View Subscription'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'subscription-delete') ):?>
					<a href="<?php echo $this->url('subscription-delete', array('clientId' => $this->subscriptionEntity->getClientId(), 'subscriptionId' => $this->subscriptionEntity->getSubscriptionId())); ?>" 
						title="<?php echo $this->translate('Delete this subscription'); ?>" class="btn btn-box-tool">
							<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
					</a>
					<?php endif; ?>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'subscription-update') ):?>
					<a href="<?php echo $this->url('subscription-update', array('clientId' => $this->subscriptionEntity->getClientId(), 'subscriptionId' => $this->subscriptionEntity->getSubscriptionId())); ?>" 
						title="<?php echo $this->translate('Edit this subscription'); ?>" class="btn btn-box-tool">
							<i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?>
					</a>
					<?php endif; ?>
				</div>
				<div class="box-body">
					<h3 class="profile-username">
						<?php echo $this->subscriptionEntity->getProductEntity()->getProductName(); ?>
						<span class="pull-right badge">
							<?php echo $this->subscriptionEntity->getSubscriptionStatusEntity()->getSubscriptionStatusName();?>
						</span>
					</h3>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Due Date')?>:</b>
            							<?php echo date($this->appConfig()->getConfigDateShort(), $this->subscriptionEntity->getSubscriptionDateDue()); ?>
            						</p>
								</div>

								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('End Date')?>:</b> 
            							<?php echo date($this->appConfig()->getConfigDateShort(), $this->subscriptionEntity->getSubscriptionDateEnd()); ?>
            						</p>
								</div>
							</div>


							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Create Date')?>:</b>
            							<?php echo date($this->appConfig()->getConfigDateShort(), $this->subscriptionEntity->getSubscriptionDateCreate()); ?>
            						</p>
								</div>

								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Last Update')?>:</b>
            							<?php echo date($this->appConfig()->getConfigDateShort(), $this->subscriptionEntity->getSubscriptionDateUpdate()); ?>
            						</p>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Payment')?>:</b>
            							<?php echo $this->subscriptionEntity->getPaymentOptionEntity()->getPaymentOptionName(); ?>
            						</p>
								</div>

								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Billing Schedule')?>:</b>
            							<?php echo $this->subscriptionEntity->getSubscriptionScheduleEntity()->getSubscriptionScheduleName(); ?>
            						</p>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Product')?>:</b>
            							<?php echo $this->subscriptionEntity->getProductEntity()->getProductName(); ?>
            						</p>
								</div>
								<div class="col-xs-12 col-sm-6">
									<p>
										<b><?php echo $this->translate('Next Product')?>:</b>
            							<?php echo $this->subscriptionEntity->getProductEntity()->getProductName(); ?>
            						</p>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<b><?php echo $this->translate('Per Host')?>:</b>
        							<?php echo $this->subscriptionEntity->getSubscriptionHost(); ?>
        						</div>
								<div class="col-xs-12 col-sm-6">
									<b><?php echo $this->translate('Per User')?>:</b>
        							<?php echo $this->subscriptionEntity->getSubscriptionUser(); ?>
        						</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="row">
			<?php if($this->subscriptionEntity->getSubscriptionHost()): ?>
			<div class="col-xs-12 col-sm-6">
				<div class="box box-primary">
					<div class="box-header">
						<h3 class="box-title">
							<i class="fa fa-desktop"></i>
        					<?php echo $this->translate('Hosts');?>
        				</h3>
        				<div class="box-tools">
							<a href="" title="<?php echo $this->translate('View all hosts'); ?>" class="btn btn-box-tool"><i class="fa fa-search"></i> <?php echo $this->translate('View All');?></a>
						</div>
					</div>
            		<?php if($this->subscriptionEntity->getSubscriptionHost() == 0): ?>
            		<div class="box-body">
						<div class="alert alert-info">
							<p>
								<i class="fa fa-info-circle"></i> <?php echo $this->translate('No hosts');?></p>
						</div>
            		<?php else: ?>
            		<div class="box-body table-responsive no-padding">
            			<?php echo $this->getSubscriptionHosts($this->subscriptionEntity->getSubscriptionId());?>
            		<?php endif; ?>
            		</div>
				</div>
			</div>
			
			<div class="col-xs-12 col-sm-6">
				<div class="box box-primary">
					<div class="box-header">
						<h3 class="box-title">
							<i class="fa fa-credit-card"></i> <?php echo $this->translate('Invoices');?>
        				</h3>
        				<div class="box-tools">
							<a href="" title="<?php echo $this->translate('View all invoices'); ?>" class="btn btn-box-tool"><i class="fa fa-search"></i> <?php echo $this->translate('View All');?></a>
						</div>
					</div>
					<div class="box-body table-responsive no-padding">
						<?php echo $this->getSubscriptionInvoices($this->subscriptionEntity->getSubscriptionId()); ?>
					</div>
				</div>
			</div>
			<?php endif;?>
			
			<?php if($this->subscriptionEntity->getSubscriptionUser()): ?>
			<div class="col-xs-12 col-sm-6">
				<div class="box box-primary">
					<div class="box-header">
						<h3 class="box-title">
							<i class="fa fa-user"></i> <?php echo $this->translate('Users');?>
        				</h3>
					</div>
					<div class="box-body">
            		<?php if($this->subscriptionEntity->getSubscriptionUser() == 0): ?>
            		<div class="alert alert-info">
							<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No users');?></p>
						</div>
            		<?php else: ?>
            		
            		<?php endif; ?>
            		</div>
				</div>
			</div>
			
			<div class="col-xs-12 col-sm-6">
				<div class="box box-primary">
					<div class="box-header">
						<h3 class="box-title">
							<i class="fa fa-user"></i> <?php echo $this->translate('Invoices');?>
        				</h3>
					</div>
					<div class="box-body">
					
					
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>