<style>
@media print {
    footer {page-break-after: always;}
}
</style>
<section class="invoice small">
	<div class="row">
		<div class="col-xs-12">
			<h2 class="page-header">
				<?php echo $this->appConfig()->getConfigCompanyName();?>
				<small class="pull-right"><?php echo $this->translate('Invoice #'); ?><?php echo $this->invoiceEntity->getInvoiceId(); ?></small>
			</h2>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-5">
			<div class="panel panel-default">
				<div class="panel-heading">
					<b><?php echo $this->translate('From'); ?>: <?php echo $this->appConfig()->getConfigCompanyName(); ?></b>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyStreet(); ?></p>
						</div>
					</div>
					<?php if(! empty($this->appConfig()->getConfigCompanyStreetCont())) :?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyStreetCont(); ?></p>
						</div>
					</div>
					<?php endif;?>
								
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyPhone(); ?></p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-2">
			<p></p>
		</div>
		<div class="col-xs-5">
			<div class="panel panel-default text-right">
				<div class="panel-heading">
					<b><?php echo $this->translate('To'); ?>: <?php echo $this->clientEntity->getClientName(); ?></b>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationStreet(); ?></p>
						</div>
					</div>
					<?php if(! empty($this->locationEntity->getLocationStreetCont())) :?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationStreetCont(); ?></p>
						</div>
					</div>
					<?php endif;?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationCity(); ?>, <?php echo $this->locationEntity->getLocationState(); ?> <?php echo $this->locationEntity->getLocationZip(); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->phoneEntity->getPhoneNum(); ?></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-5">
			<p><b><?php echo $this->translate('Invoice Date'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateShort(), $this->invoiceEntity->getInvoiceDate()); ?>
		</div>
		<div class="col-xs-2"></div>
		<div class="col-xs-5">
			<p><b><?php echo $this->translate('Period'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateShort(), $this->invoiceEntity->getInvoiceDateStart()); ?> - <?php echo date($this->appConfig()->getConfigDateShort(), $this->invoiceEntity->getInvoiceDateEnd()); ?>
		</div>
	</div>	
    <div class="row">
    	<div class="col-xs-12">
    		
    				<table class="table table-bordered small">
                  		<thead>
                  			<tr>
                  				<th class="col-xs-1"><?php echo $this->translate('Qty'); ?></th>
                  				<th><?php echo $this->translate('Description'); ?></th>
                  				<th class="col-xs-1 text-right"><?php echo $this->translate('Amount'); ?></th>
                  				<th class="col-xs-1 text-right" nowrap><?php echo $this->translate('Total'); ?></th>
                  			</tr>
                  		</thead>
                  		<tbody>
                  		<?php foreach($this->itemEntitys as $itemEntity): ?>
                  			<tr>
                  				<td><?php echo $itemEntity->getInvoiceItemQty(); ?></td>
                  				<td><?php echo $itemEntity->getInvoiceItemDescrip(); ?></td>
                  				<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getInvoiceItemAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  				<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getInvoiceItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  		<?php endforeach; ?>
                  		</tbody>
                  		<tfoot>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Sub Total'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceSubtotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php if($this->optionEntity->getInvoiceOptionEnableDiscount()): ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Discount'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceDiscount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php endif; ?>
                  			<?php if($this->optionEntity->getInvoiceOptionEnableTax()): ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Tax'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceTax(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php endif; ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Total'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Payment'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoicePayment(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Balance'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  		</tfoot>
                 	</table>
                </div>
    </div>
    <br />
      
    <p class="text-center"><?php echo $this->optionEntity->getInvoiceOptionTerms(); ?></p>
  
	<hr/>
	<p class="text-center"><?php echo $this->translate('Please detach this section and eclose with your payment. DO NOT SEND CASH!'); ?></p>
	
	<p><br /></p>
	
	<div class="row">
		<div class="col-xs-6">
			<h4><?php echo $this->appConfig()->getConfigCompanyName();?></h4>
			<p><b><?php echo $this->translate('Bill To'); ?>:</b>
			<address>
				 <?php echo $this->clientEntity->getClientName(); ?><br />
				 <?php echo $this->locationEntity->getLocationStreet(); ?><br />
				 <?php if(! empty($this->locationEntity->getLocationStreetCont())) :?>
				 	<?php echo $this->locationEntity->getLocationStreetCont(); ?><br />
				 <?php endif; ?>
				 <?php echo $this->locationEntity->getLocationCity(); ?>, <?php echo $this->locationEntity->getLocationState(); ?> <?php echo $this->locationEntity->getLocationZip(); ?>
			</address>
			
			<p><b><?php echo $this->translate('Billing questions, call us at'); ?>: <?php echo $this->appConfig()->getConfigCompanyPhone(); ?></b>
		
			<p><?php echo $this->optionEntity->getInvoiceOptionMemo(); ?></p>
		</div>
		<div class="col-xs-6">
			<table class="table table-bordered table-condensed">
				<thead>
					<tr>
						<th><?php echo $this->translate('Account'); ?></th>
						<th><?php echo $this->translate('Invoice'); ?></th>
						<th><?php echo $this->translate('Date'); ?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $this->clientId; ?></td>
						<td><?php echo $this->invoiceEntity->getInvoiceId(); ?></td>
						<td><?php echo date($this->appConfig()->getConfigDateShort(), $this->invoiceEntity->getInvoiceDate()); ?></td>
					</tr>
					<tr>
						<th colspan="2" ><?php echo $this->translate('Amount Due'); ?></th>
						<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
					</tr>
				</tbody>
			</table>
			<div class="pull-right">
				<b><?php echo $this->translate('Payment Amount')?> $_____________________</b>
			</div>
			<br /><br />
			<p><?php echo $this->translate('Please send your payment to this address');?>:</p>
			<address>
				<?php echo $this->appConfig()->getConfigCompanyName(); ?><br />
				<?php echo $this->appConfig()->getConfigCompanyStreet(); ?><br />
				<?php if(! empty($this->appConfig()->getConfigCompanyStreetCont())) :?>
					<?php echo $this->appConfig()->getConfigCompanyStreetCont(); ?><br />
				<?php endif; ?>
				<?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?>
			</address>
		</div>
	</div>
	
</section>

<footer></footer>
<?php foreach($this->workorderEntitys as $workorderEntity): ?>
<section class="invoice small">
	<div class="row">
		<div class="col-xs-12">
			<h2 class="page-header">
				<?php echo $this->appConfig()->getConfigCompanyName();?>
				<small class="pull-right"><?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getworkOrderId(); ?></small>
			</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<div class="panel panel-default">
    			<div class="panel-body">
    				<div class="row">
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Scheduled'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateScheduled()); ?></p>
    					</div>
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Status'); ?>:</b> <?php echo $workorderEntity->getWorkorderStatus(); ?></p>
    					</div>
    				</div>
    				<div class="row">
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Contact'); ?>:</b> 
    							<?php if(! $workorderEntity->getUserEntity()): ?>
    							<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing contact.')?></span>
    						<?php else: ?>
    							<?php $userEntity = $workorderEntity->getUserEntity(); ?>
    								<?php echo $userEntity->getUserNameFirst(); ?> <?php echo $userEntity->getUserNameLast(); ?>
    						<?php endif;?>
    						
    						</p>
    					</div>
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Phone'); ?>:</b> 
    							<?php if(! $workorderEntity->getPhoneEntity()) :?>
    							<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing phone.')?></span>
    						<?php else: ?>
    							<?php $phoneEntity = $workorderEntity->getPhoneEntity(); ?>
    							<?php echo $phoneEntity->getPhoneNum();?>
    						<?php endif; ?>
    						
    						</p>
    					</div>
    				</div>
    				<div class="row">
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Labor'); ?>:</b> <?php echo $this->currencyFormat($workorderEntity->getWorkorderLabor(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
    					</div>
    					<div class="col-xs-6">
    						<p><b><?php echo $this->translate('Parts'); ?>:</b> <?php echo $this->currencyFormat($workorderEntity->getWorkorderParts(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
    					</div>
    				</div>
    				<div class="row">
    					<div class="col-xs-12">
    						<?php $locationEntity = $workorderEntity->getLocationEntity(); ?>
    						<p><b><?php echo $this->translate('Location'); ?>:</b>
    							<?php if($locationEntity): ?> 
    							<?php echo $locationEntity->getLocationStreet();?> <?php echo $locationEntity->getLocationCity(); ?>, <?php echo $locationEntity->getLocationState();?> <?php echo $locationEntity->getLocationZip(); ?>
    							<?php else: ?>
    								<?php echo $this->translate('No location set');?>
    							<?php endif;?>
    						</p>
    					</div>
    				</div>
    				<div class="row">
    					<div class="col-xs-12">
    						<?php echo $workorderEntity->getWorkorderDescription();?>
    					</div>
    				</div>
    			</div>
    		</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-list-alt"></i> <?php echo $this->translate('Notes')?>
				</div>
    			<div class="panel-body">
    				<?php echo $this->getWorkorderNotes($workorderEntity, false); ?>
    			</div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
		<div class="col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-clock-o"></i> <?php echo $this->translate('Times')?>
				</div>
    			<div class="panel-body">
    				<?php echo $this->getWorkorderTimes($workorderEntity, false); ?>
    			</div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
		<div class="col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-hdd-o"></i> <?php echo $this->translate('Parts')?>
				</div>
    			<div class="panel-body">
    				<?php echo $this->getWorkorderParts($workorderEntity, false); ?>
    			</div>
    		</div>
    	</div>
    </div>

</section>
<footer></footer>
<?php endforeach; ?>
