
<section class="invoice small">
	<div class="row">
		<div class="col-xs-12">
			<h2 class="page-header">
				<?php echo $this->appConfig()->getConfigCompanyName();?>
				<small class="pull-right"><?php echo $this->translate('Invoice #'); ?><?php echo $this->invoiceEntity->getInvoiceId(); ?></small>
			</h2>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-5">
			<div class="panel panel-default">
				<div class="panel-heading">
					<b><?php echo $this->translate('From'); ?>: <?php echo $this->appConfig()->getConfigCompanyName(); ?></b>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyStreet(); ?></p>
						</div>
					</div>
					<?php if(! empty($this->appConfig()->getConfigCompanyStreetCont())) :?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyStreetCont(); ?></p>
						</div>
					</div>
					<?php endif;?>
								
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->appConfig()->getConfigCompanyPhone(); ?></p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-2">
			<p></p>
		</div>
		<div class="col-xs-5">
			<div class="panel panel-default text-right">
				<div class="panel-heading">
					<b><?php echo $this->translate('To'); ?>: <?php echo $this->clientEntity->getClientName(); ?></b>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationStreet(); ?></p>
						</div>
					</div>
					<?php if(! empty($this->locationEntity->getLocationStreetCont())) :?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationStreetCont(); ?></p>
						</div>
					</div>
					<?php endif;?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->locationEntity->getLocationCity(); ?>, <?php echo $this->locationEntity->getLocationState(); ?> <?php echo $this->locationEntity->getLocationZip(); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $this->phoneEntity->getPhoneNum(); ?></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
				
    <div class="row">
    	<div class="col-xs-12">
    		
    				<table class="table table-bordered small">
                  		<thead>
                  			<tr>
                  				<th class="col-xs-1"><?php echo $this->translate('Qty'); ?></th>
                  				<th><?php echo $this->translate('Description'); ?></th>
                  				<th class="col-xs-1 text-right"><?php echo $this->translate('Amount'); ?></th>
                  				<th class="col-xs-1 text-right" nowrap><?php echo $this->translate('Total'); ?></th>
                  			</tr>
                  		</thead>
                  		<tbody>
                  		<?php foreach($this->itemEntitys as $itemEntity): ?>
                  			<tr>
                  				<td><?php echo $itemEntity->getInvoiceItemQty(); ?></td>
                  				<td><?php echo $itemEntity->getInvoiceItemDescrip(); ?></td>
                  				<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getInvoiceItemAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  				<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getInvoiceItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  		<?php endforeach; ?>
                  		</tbody>
                  		<tfoot>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Sub Total'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceSubtotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php if($this->optionEntity->getInvoiceOptionEnableDiscount()): ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Discount'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceDiscount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php endif; ?>
                  			<?php if($this->optionEntity->getInvoiceOptionEnableTax()): ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Tax'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceTax(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<?php endif; ?>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Total'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Payment'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoicePayment(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  			<tr>
                  				<th colspan="3" class="text-right"><?php echo $this->translate('Balance'); ?></th>
                  				<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                  			</tr>
                  		</tfoot>
                 	</table>
                </div>
    </div>
    <br />
      
    <p class="text-center"><?php echo $this->optionEntity->getInvoiceOptionTerms(); ?></p>
  
	<hr/>
	<p class="text-center"><?php echo $this->translate('Please detach this section and eclose with your payment. DO NOT SEND CASH!'); ?></p>
	
	<p><br /></p>
	
	<div class="row">
		<div class="col-xs-6">
			<h4><?php echo $this->appConfig()->getConfigCompanyName();?></h4>
			<p><b><?php echo $this->translate('Bill To'); ?>:</b>
			<address>
				 <?php echo $this->clientEntity->getClientName(); ?><br />
				 <?php echo $this->locationEntity->getLocationStreet(); ?><br />
				 <?php if(! empty($this->locationEntity->getLocationStreetCont())) :?>
				 	<?php echo $this->locationEntity->getLocationStreetCont(); ?><br />
				 <?php endif; ?>
				 <?php echo $this->locationEntity->getLocationCity(); ?>, <?php echo $this->locationEntity->getLocationState(); ?> <?php echo $this->locationEntity->getLocationZip(); ?>
			</address>
			
			<p><b><?php echo $this->translate('Billing questions, call us at'); ?>: <?php echo $this->appConfig()->getConfigCompanyPhone(); ?></b>
		
			<p><?php echo $this->optionEntity->getInvoiceOptionMemo(); ?></p>
		</div>
		<div class="col-xs-6">
			<table class="table table-bordered table-condensed">
				<thead>
					<tr>
						<th><?php echo $this->translate('Account'); ?></th>
						<th><?php echo $this->translate('Invoice'); ?></th>
						<th><?php echo $this->translate('Date'); ?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><?php echo $this->clientId; ?></td>
						<td><?php echo $this->invoiceEntity->getInvoiceId(); ?></td>
						<td><?php echo date($this->appConfig()->getConfigDateShort(), $this->invoiceEntity->getInvoiceDate()); ?></td>
					</tr>
					<tr>
						<th colspan="2" ><?php echo $this->translate('Amount Due'); ?></th>
						<td class="text-right"><?php echo $this->currencyFormat($this->invoiceEntity->getInvoiceBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
					</tr>
				</tbody>
			</table>
			<div class="pull-right">
				<b><?php echo $this->translate('Payment Amount')?> $_____________________</b>
			</div>
			<br /><br />
			<p><?php echo $this->translate('Please send your payment to this address');?>:</p>
			<address>
				<?php echo $this->appConfig()->getConfigCompanyName(); ?><br />
				<?php echo $this->appConfig()->getConfigCompanyStreet(); ?><br />
				<?php if(! empty($this->appConfig()->getConfigCompanyStreetCont())) :?>
					<?php echo $this->appConfig()->getConfigCompanyStreetCont(); ?><br />
				<?php endif; ?>
				<?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?>
			</address>
		</div>
	</div>
	
</section>



