<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-file"></i>
					<?php echo $this->translate('Log Files'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			
			<div class="box-body">
				<?php if(count($this->logFiles) == 0):?>
		<div class="alert alert-info">
			<p><i class="fa fa-info-circle fa-fw"></i> <?php echo $this->translate('There are no log files');?></p>
		</div>
    	<?php else:?>
			<?php foreach($this->logFiles as $fileInfo):?>
				<?php if($fileInfo->isDot() || $fileInfo->getFilename() == ".gitignore") continue;?>
				<div class="row">
					<div class="col-xs-12 col-sm-2">
						<i class="fa fa-file-code-o fa-fw"></i>
						<a href="<?php echo $this->url('log-view', array('file' => $fileInfo->getFilename()));?>" title="<?php echo $this->translate('View this log file'); ?>">
							<?php echo $fileInfo->getFilename(); ?>
						</a>
						
					</div>
					<div class="col-xs-12 col-sm-9">
						<span class="text-muted  small"><?php echo $fileInfo->getPathname();?> - Modified: <?php echo date("m/d/Y G:i:s", $fileInfo->getMTime());?></span>
					</div>
					<div class="col-xs-12 col-sm-1">
						<span class="text-muted small pull-right"><a href="">Download</a></span>
					</div>
				</div>
			<?php endforeach;?>
		<?php endif;?>
			</div>
		</div>
	</div>
</div>