<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Client\Service\ClientServiceInterface'             => __DIR__ . '/src/Client/Service/ClientServiceInterface.php',
    'Client\Service\ClientService'                      => __DIR__ . '/src/Client/Service/ClientService.php',
    'Client\Service\Factory\ClientServiceFactory'       => __DIR__ . '/src/Client/Service/Factory/ClientServiceFactory.php',
    'Client\Controller\ViewController'                  => __DIR__ . '/src/Client/Controller/ViewController.php',
    'Client\Controller\CreateController'                => __DIR__ . '/src/Client/Controller/CreateController.php',
    'Client\Controller\UpdateController'                => __DIR__ . '/src/Client/Controller/UpdateController.php',
    'Client\Controller\IndexController'                 => __DIR__ . '/src/Client/Controller/IndexController.php',
    'Client\Controller\Factory\IndexControllerFactory'  => __DIR__ . '/src/Client/Controller/Factory/IndexControllerFactory.php',
    'Client\Controller\Factory\CreateControllerFactory' => __DIR__ . '/src/Client/Controller/Factory/CreateControllerFactory.php',
    'Client\Controller\Factory\ViewControllerFactory'   => __DIR__ . '/src/Client/Controller/Factory/ViewControllerFactory.php',
    'Client\Controller\Factory\UpdateControllerFactory' => __DIR__ . '/src/Client/Controller/Factory/UpdateControllerFactory.php',
    'Client\Form\ClientForm'                            => __DIR__ . '/src/Client/Form/ClientForm.php',
    'Client\Mapper\ClientMapperInterface'               => __DIR__ . '/src/Client/Mapper/ClientMapperInterface.php',
    'Client\Mapper\ClientMapper'                        => __DIR__ . '/src/Client/Mapper/ClientMapper.php',
    'Client\Mapper\Factory\ClientMapperFactory'         => __DIR__ . '/src/Client/Mapper/Factory/ClientMapperFactory.php',
    'Client\Hydrator\ClientHydrator'                    => __DIR__ . '/src/Client/Hydrator/ClientHydrator.php',
    'Client\Entity\ClientEntityInterface'               => __DIR__ . '/src/Client/Entity/ClientEntityInterface.php',
    'Client\Entity\ClientEntity'                        => __DIR__ . '/src/Client/Entity/ClientEntity.php',
    'Client\Module'                                     => __DIR__ . '/Module.php',
);
