<section class="content">

<div class="row">
	<div class="col-xs-12 col-sm-offset-3 col-sm-6">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cogs" aria-hidden="true"></i> <?php echo $this->translate('Complete'); ?>
				</h3>
			</div>
			<div class="box-body">
				<p><?php echo $this->translate('The install is complete.')?>
					<a href="<?php echo $this->url('auth-sign-in');?>" title="<?php echo $this->translate('Sign In'); ?>"><?php echo $this->translate('You may sign in here to complete the setup of your company.')?></a>
				</p>
			</div>
			
		</div>
	</div>
</div>

</section>