<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<!-- Client Menu -->					
<li class="treeview <?php if($this->activeMenuItem == 'employee'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-table"></i> <span><?php echo $this->translate('My Profile'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<?php echo $this->navigation('employeeMenu')->menu()->setPartial('partials/employee-menu'); ?>
</li>