<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<li class="treeview <?php if($this->activeMenuItem == 'employee'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-table"></i> <span><?php echo $this->translate('My Profile'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<!-- home -->
		<li class="<?php if($this->activeSubMenuItem == 'employee-profile'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-profile'); ?>" title="My Profile">
				<i class="fa fa-home"></i> <span><?php echo $this->translate('Home')?></span>
			</a>
		</li>
			
		<!-- Client Favorites -->
		
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-favorite-index') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'client-favorite-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('client-favorite-index'); ?>" title="Client Favorites">
				<i class="fa fa-star"></i> <span><?php echo $this->translate('Client Favorites')?></span>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- password -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'employee-password') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'employee-password'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-password');?>" title="<?php echo $this->translate('Change Password')?>">
				<i class="fa fa-lock"></i> <span><?php echo $this->translate('Change Password')?></span>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- messages -->
		<li class="<?php if($this->activeSubMenuItem == ''):?>active<?php endif;?>">
			<a href="" >
				<i class="fa fa-envelope"></i> <span><?php echo $this->translate('Messages')?></span>
			</a>
		</li>
			
		<!-- Calendar -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'employee-calendar') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'employee-calendar'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-calendar'); ?>" title="<?php echo $this->translate('View calendar'); ?>">
				<i class="fa fa-calendar" aria-hidden="true"></i> <span><?php echo $this->translate('Calendar')?></span>
			</a>
		</li>
		<?php endif; ?>
		
		<!-- Mileage -->
		<li class="<?php if($this->activeSubMenuItem == ''):?>active<?php endif;?>">
			<a href="" >
				<i class="fa fa-truck" aria-hidden="true"></i> <span><?php echo $this->translate('Mileage')?></span>
			</a>
		</li>
		
		
			
		<!-- Time -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'employee-time') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'employee-time'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-time'); ?>" title="<?php echo $this->translate('View time clock'); ?>">
				<i class="fa fa-clock-o" aria-hidden="true"></i> <span><?php echo $this->translate('Time Clock')?></span>
			</a>
		</li>
		<?php endif; ?>
	</ul>
</li>
	
<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-view') ):?>
    
<li class="treeview <?php if($this->activeMenuItem == 'client'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-table"></i> <span><?php echo $this->translate('Client'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-index') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'client-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('client-index'); ?>" title="<?php echo $this->translate('Clients'); ?>">
				<i class="fa fa-group"></i> <?php echo $this->translate('Clients'); ?>
			</a>
		</li>
		<?php endif; ?>
			
			
		<!-- Client Menu -->
		<?php if($this->clientId): ?>
			
		<!-- Client Home -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-view') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'client-view'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('client-view', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-home"></i> <?php echo $this->translate('Client Home')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Client Fav -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-favorite-create') ):?>
		<?php $favoriteEntity = $this->hasFavorite($this->clientId, $this->identity()->getAuthId()); ?>
		
		<?php if($favoriteEntity): ?>
		<li class="<?php if($this->activeSubMenuItem == 'client-favorite-create'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('client-favorite-delete', array('clientId' => $this->clientId, 'clientFavoriteId' => $favoriteEntity->getclientFavoriteId())); ?>" title="<?php echo $this->translate('Remove From Favorite')?>">
				<i class="fa fa-star"></i> <?php echo $this->translate('Remove From Favorite')?>
			</a>
		</li>
		<?php else: ?>
		<li class="<?php if($this->activeSubMenuItem == 'client-favorite-create'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('client-favorite-create', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-star"></i> <?php echo $this->translate('Add To Favorite')?>
			</a>
		</li>
		<?php endif; ?>
		<?php endif; ?>
			
		<!-- Call Log -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'call-log-index') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'call-log-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('call-log-index', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Estimates')?>">
				<i class="fa fa-phone"></i> <?php echo $this->translate('Call Log')?>
			</a>
		</li>
		<?php endif; ?>
		
		
		<!-- Estimate -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-index') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'estimate-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('estimate-index', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Estimates')?>">
				<i class="fa fa-newspaper-o"></i> <?php echo $this->translate('Estimates')?>
			</a>
		</li>
		<?php endif; ?>
		
		<!-- Hosts -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'host-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'host-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('host-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-desktop"></i> <?php echo $this->translate('Hosts')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Invoice -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'invoice-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('invoice-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-credit-card"></i> <?php echo $this->translate('Invoices')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Network -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'network-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'network-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('network-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-sitemap"></i> <?php echo $this->translate('Network')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Password -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'password-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'password-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('password-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-lock"></i> <?php echo $this->translate('Passwords')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!--  tickets -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'ticket-index') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'ticket-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('ticket-index', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-life-ring" aria-hidden="true"></i> <?php echo $this->translate('Support Tickets')?>
			</a>
		</li>
		<?php endif;?>
			
		<!-- Tasks -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'task-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'task-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('task-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-tasks"></i> <?php echo $this->translate('Tasks')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Users -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'user-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('user-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-user"></i> <?php echo $this->translate('Users')?>
			</a>
		</li>
		<?php endif; ?>
			
		<!-- Workorders -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-list') ):?>
		<li class="<?php if($this->activeSubMenuItem == 'workorder-list'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('workorder-list', array('clientId' => $this->clientId)); ?>">
				<i class="fa fa-wrench"></i> <?php echo $this->translate('Work Orders')?>
			</a>
		</li>
		<?php endif; ?>
	<?php endif;?>
	</ul>
</li>
<?php endif; ?>