<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title"><?php echo $this->translate('Clients'); ?></h3>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-create') ):?>
						<a href="<?php echo $this->url('client-create', array());?>" title="<?php echo $this->translate('Create Client'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>	
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
    			<ul class="list-group list-group-unbordered">
    				<li class="list-group-item">
            			<form class="form-inline">
                			<div class="row">
                				<div class="col-xs-12">
                				
                					<div class="form-group">
                        				<select class="form-control input-sm" name="clientStatus" id="clientStatus">
                        					<option value=""><?php echo $this->translate('Status'); ?></option>
                        					<option value="Active" <?php if($this->clientStatus == 'Active'):?> selected <?php endif?>><?php echo $this->translate('Active'); ?></option>
                        					<option value="Closed" <?php if($this->clientStatus == 'Closed'):?> selected <?php endif?>><?php echo $this->translate('Closed'); ?></option>
                        				</select>
                    				</div>
                    				
                    				<div class="form-group">
                						<div class="input-group input-group-sm">
                							<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="<?php echo $this->translate('Search'); ?>" value="<?php echo $this->keyword; ?>">
                    						<div class="input-group-btn">
                    							<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    						</div>
                						</div>
                					</div>
                				
                				</div>
                			</div>
                		</form>
            		</li>
    			
					<?php if($this->paginator->count() == 0): ?>
					<li class="list-group-item">
        				<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> 
        					<?php if($this->clientStatus):?>
        						<?php echo $this->translate("There where no {$this->clientStatus} clients found"); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php else:?>
        						<?php echo $this->translate('There where no clients found'); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php endif; ?>
        				</div>
					</li>
					<?php else: ?>
    			
    				<?php foreach($this->paginator as $clientEntity): ?>
    				<li class="list-group-item">
                    	<div class="row">
                        	<div class="col-xs-12">
                        		<h3 class="profile-username">
                        			<a href="<?php echo $this->url('client-view', array('clientId' => $clientEntity->getClientId()));?>" title="<?php echo $this->translate('View this client'); ?>">
                        				<?php echo $clientEntity->getClientName(); ?>
                        			</a>
                        			<span class="pull-right badge"><?php echo $clientEntity->getClientStatus(); ?></span>
                        		</h3>
                        	</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-xs-12 col-sm-9">
                    			<?php if(! $clientEntity->getLocationEntity()->getLocationId()) :?>
                    			<p class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('No location'); ?></p>
                    			<?php else: ?>
                        		<b><?php echo $this->translate('Location'); ?>:</b>
                        		<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
                        		<a href="<?php echo $this->url('location-view', array('clientId' => $clientEntity->getClientId(), 'locationId' => $clientEntity->getLocationEntity()->getLocationId()));?>" title="<?php echo $this->translate('View this location'); ?>">
                        			<?php echo $clientEntity->getLocationEntity()->getLocationStreet(); ?>
                        			<?php echo $clientEntity->getLocationEntity()->getLocationCity(); ?>,
                        			<?php echo $clientEntity->getLocationEntity()->getLocationState(); ?>
                        			<?php echo $clientEntity->getLocationEntity()->getLocationZip(); ?>
                        		</a>
                        		<?php else: ?>
                        			<?php echo $clientEntity->getLocationEntity()->getLocationStreet(); ?>
                        			<?php echo $clientEntity->getLocationEntity()->getLocationCity(); ?>,
                        			<?php echo $clientEntity->getLocationEntity()->getLocationState(); ?>
                        			<?php echo $clientEntity->getLocationEntity()->getLocationZip(); ?>
                        		<?php endif; ?>
                        		<?php endif;?>
                        	</div>
                        	<div class="col-xs-12 col-sm-3 text-right">
                        		<?php if(! $clientEntity->getPhoneEntity()->getPhoneId()): ?>
                        			<p class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('No phone'); ?>
                        		<?php else: ?>
                        		<b><?php echo $this->translate('Phone'); ?>:</b>
                        		<a href="tel:<?php echo $clientEntity->getPhoneEntity()->getPhoneNum(); ?>" title="<?php echo $this->translate('Call this phone number'); ?>">
                        			<?php echo $clientEntity->getPhoneEntity()->getPhoneNum(); ?>
                        		</a>
                        		<?php endif; ?>
                        	</div>
                    	</div>
                    </li>
                    <?php endforeach; ?>
           		 <?php endif; ?>
            	</ul>
            	<?php if($this->pageCount > 1): ?>
				<div class="row">
					<div class="col-xs-12">
    				<?php echo $this->Paginator(
    	                        $this->itemCountPerPage,
    	                        $this->itemCount,
    	                        $this->pageCount,
    	                        $this->page,
    	                        $this->routeParams,
    	                        $this->queryParams); ?>
    	        	</div>
    			</div>
				<?php endif; ?>
            </div>
        </div>
    </div>
</div>