
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Work Orders'); ?>
				</h3>
				
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-create') ):?>
					<a href="<?php echo $this->url('workorder-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new work order');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<form class="form-inline">
        					<div class="form-group">
                				<select class="form-control input-sm" name="workorderStatus" id="workorderStatus">
                					<option value=""><?php echo $this->translate('Status'); ?></option>
                					<option value="Active" <?php if($this->workorderStatus == 'Active'):?> selected <?php endif?>><?php echo $this->translate('Active'); ?></option>
                					<option value="Closed" <?php if($this->workorderStatus == 'Closed'):?> selected <?php endif?>><?php echo $this->translate('Closed'); ?></option>
                				</select>
            				</div>
            					
        					<div class="form-group">
        						<div class="input-group input-group-sm" style="width: 250px;">
        							<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="Search" value="<?php echo $this->keyword; ?>">
            						<div class="input-group-btn">
            							<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            						</div>
        						</div>
        					</div>
        				</form>
					</li>
					<?php if($this->paginator->count() == 0): ?>
					<li class="list-group-item">
        				<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> 
        					<?php if($this->workorderStatus):?>
        						<?php echo $this->translate("There where no {$this->workorderStatus} work orders found"); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php else:?>
        						<?php echo $this->translate('There where no work orders found'); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php endif; ?>
        				</div>
					</li>
				<?php else: ?>
					<?php foreach($this->paginator as $workorderEntity): ?>
					<li class="list-group-item">
						<div class="row">
							<div class="col-xs-12">
								<h3 class="profile-username">
									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-view') ):?>
									<a href="<?php echo $this->url('workorder-view', array('clientId' => $this->clientId, 'workorderId' => $workorderEntity->getWorkorderId())); ?>" title="<?php echo $this->translate('View this work order'); ?>"><?php echo $this->translate('Work Order #')?><?php echo $workorderEntity->getWorkorderId(); ?></a>
									<?php else: ?>
									<?php echo $this->translate('Work Order #')?><?php echo $workorderEntity->getWorkorderId(); ?>
									<?php endif; ?>
									<span class="pull-right badge <?php ($workorderEntity->getWorkorderStatus() == 'Active') ? 'text-success' : 'text-danger'; ?>"><?php echo $workorderEntity->getWorkorderStatus(); ?></span>	
								</h3>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<b><?php echo $this->translate('Title'); ?>: </b> <?php echo $workorderEntity->getWorkorderTitle();?>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Scheduled'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateScheduled()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Ends'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateEnd()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Contact'); ?>:</b> 
									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
									<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $workorderEntity->getUserEntity()->getUserId()));?>" title="<?php echo $this->translate('View this user'); ?>">
										<?php echo $workorderEntity->getUserEntity()->getUserNameFirst();?> <?php echo $workorderEntity->getUserEntity()->getUserNameLast();?>
									</a>
									<?php else: ?>
										<?php echo $workorderEntity->getUserEntity()->getUserNameFirst();?> <?php echo $workorderEntity->getUserEntity()->getUserNameLast();?>
									<?php endif; ?>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-8">
								<b><?php echo $this->translate('Location'); ?>:</b> 
								<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
								<a href="<?php echo $this->url('location-view', array('locationId' => $workorderEntity->getLocationEntity()->getLocationId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('View this location'); ?>">
									<?php echo $workorderEntity->getLocationEntity()->getLocationStreet(); ?> 
									<?php echo $workorderEntity->getLocationEntity()->getLocationCity(); ?>,
									<?php echo $workorderEntity->getLocationEntity()->getLocationState(); ?>
									<?php echo $workorderEntity->getLocationEntity()->getLocationZip(); ?>
								</a>
								<?php else: ?>
									<?php echo $workorderEntity->getLocationEntity()->getLocationStreet(); ?> 
									<?php echo $workorderEntity->getLocationEntity()->getLocationCity(); ?>,
									<?php echo $workorderEntity->getLocationEntity()->getLocationState(); ?>
									<?php echo $workorderEntity->getLocationEntity()->getLocationZip(); ?>
								<?php endif; ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Phone'); ?>:</b> 
								<a href="tel:<?php echo $workorderEntity->getPhoneEntity()->getPhoneNum(); ?>" title="<?php echo $this->translate('Call this phone number')?>"><?php echo $workorderEntity->getPhoneEntity()->getPhoneNum(); ?></a>
							</div>
						</div>
					</li>
					<?php endforeach;?>
				</ul>	
				<div class="row">
					<div class="col-xs-12">
						<?php echo $this->Paginator(
	                        $this->itemCountPerPage,
	                        $this->itemCount,
	                        $this->pageCount,
	                        $this->page,
	                        $this->routeParams,
	                        $this->queryParams); ?>
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>