<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h4 class="box-title">
					<i class="fa fa-newspaper-o"></i>
					<?php echo $this->translate('View Estimate'); ?>
				</h4>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-print') ):?>
					<a href="<?php echo $this->url('estimate-print', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId()));?>" title="<?php echo $this->translate('Print this estimate')?>" class="btn btn-box-tool" target="_blank"><i class="fa fa-print"></i> <?php echo $this->translate('Print'); ?></a>
					<?php endif;?>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-delete') ):?>
						<a href="<?php echo $this->url('estimate-delete', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId()));?>" title="<?php echo $this->translate('Delete this estimate'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<?php endif; ?>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-update') ):?>
					<a href="<?php echo $this->url('estimate-update', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId()));?>" title="<?php echo $this->translate('Edit this estimate'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12 text-center">
						<h4><?php echo strtoupper($this->clientEntity->getClientName()); ?></h4>
						<hr style="margin-top:-8px; margin-bottom:-8px;"/>
						<h4><?php echo strtoupper($this->estimateEntity->getEstimateTitle()); ?></h4>
					</div>
				</div>
				<br />
				<div class="row">
					<div class="col-xs-12 text-center">
						<h4><?php echo strtoupper($this->locationEntity->getLocationStreet()); ?></h4>
						<h4 style="margin-top:-8px; margin-bottom:-8px;"><?php echo strtoupper($this->locationEntity->getLocationCity()); ?>, <?php echo strtoupper($this->locationEntity->getLocationState()); ?> <?php echo strtoupper($this->locationEntity->getLocationZip()) ;?></h4>
						<h4><?php echo $this->phoneEntity->getPhoneNum(); ?></h4>
					</div>
				</div>
				<br />
				<div class="row">
					<div class="col-xs-12 text-center">
						<h4><?php echo strtoupper($this->translate('Created'));?> <?php echo date($this->appConfig()->getConfigDateShort(), $this->estimateEntity->getEstimateDateDue()); ?></h4>
						<h4 style="margin-top:-8px; margin-bottom:-8px;"><?php echo strtoupper($this->translate('by')); ?> <?php echo strtoupper($this->appConfig()->getConfigCompanyName()); ?></h4>
						<h4><?php echo $this->appConfig()->getConfigCompanyPhone(); ?></h4>
					</div>
				</div>
				<br />
    			<div class="row">
    				<div class="col-xs-12">
    					<p><?php echo $this->estimateEntity->getEstimateOverview(); ?></p>
    				</div>
    			</div>
    			<div class="row">
    				<div class="col-xs-12">
    					<p><?php echo $this->translate('This estimate is copy written by')?> <?php echo $this->appConfig()->getConfigCompanyName(); ?> <?php echo $this->translate('and may not be reproduced or copied.'); ?></p>
    				</div>
    			</div>
			</div>
			
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h4 class="box-title">
					<i class="fa fa-newspaper-o"></i>
					<?php echo $this->translate('Estimate Options'); ?>
				</h4>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-option-create') ):?>
						<a href="<?php echo $this->url('estimate-option-create', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId()));?>" title="<?php echo $this->translate('Add new estimate option'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
				<div class="box-body">
					<?php if($this->optionEntitys->count() == 0):?>
					<div class="alert alert-info">
						<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This estimate has no options yet. Click new and create one.'); ?></p>
					</div>
					<?php else: ?>
					<?php foreach($this->optionEntitys as $optionEntity): ?>
					<div class="row">
						<div class="col-xs-12">
							<h4 class="text-center"><?php echo strtoupper($optionEntity->getEstimateOptionTitle()); ?>
								<span class="pull-right">
								
								<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-option-item-create') ):?>
								<a href="<?php echo $this->url('estimate-option-item-create', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId(), 'estimateOptionId' => $optionEntity->getEstimateOptionId())); ?>" title="<?php echo $this->translate('Add new item to option'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New')?></a>
								<?php endif; ?>
								
								<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-option-delete') ):?>
								<a href="<?php echo $this->url('estimate-option-delete', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId(), 'estimateOptionId' => $optionEntity->getEstimateOptionId())); ?>" title="<?php echo $this->translate('Delete this option'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete')?></a>
								<?php endif; ?>
								<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'estimate-option-update') ):?>
								<a href="<?php echo $this->url('estimate-option-update', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId(), 'estimateOptionId' => $optionEntity->getEstimateOptionId()))?>" title="<?php echo $this->translate('Edit this option'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit')?></a>
								<?php endif; ?>
								</span>
							</h4>
							<hr/>
							<p><?php echo $optionEntity->getEstimateOptionDecription(); ?></p>
							<?php if($optionEntity->getItemEntity()->count() == 0): ?>
							<div class="alert alert-info">
								<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This option has no items.'); ?></p>
							</div>
							<?php else: ?>
							<?php $total = 0; ?>
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover">
                					<thead>
                						<tr>
                							<th class="col-xs-1"><?php echo $this->translate('Type'); ?></th>
                							<th class="col-xs-1"><?php echo $this->translate('Quantity'); ?></th>
                							<th><?php echo $this->translate('Description'); ?></th>
                							<th class="col-xs-1 text-right"><?php echo $this->translate('Amount'); ?></th>
                							<th class="col-xs-1 text-right"><?php echo $this->translate('Total'); ?></th>
                							<th class="col-xs-1"></th>
                						</tr>
                					</thead>
                					<tbody>
                					<?php foreach($optionEntity->getItemEntity() as $itemEntity): ?>
                					<tr>
                						<td><?php echo  $this->translate($itemEntity->getEstimateOptionItemType());?></td>
                						<td><?php echo $itemEntity->getEstimateOptionItemQty(); ?></td>
                						<td><?php echo $itemEntity->getEstimateOptionTitle(); ?></td>
                						<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                						<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
                						<td class="text-right">
                							<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'estimate-option-item-delete') ):?>
                							<a href="<?php echo $this->url('estimate-option-item-delete', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId(), 'estimateOptionId' => $itemEntity->getEstimateOptionId(), 'estimateOptionItemId' => $itemEntity->getEstimateOptionItemId())); ?>" title="<?php echo $this->translate('Delete this item'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i></a>
											<?php endif; ?>
											
											<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'estimate-option-item-update') ):?>
											<a href="<?php echo $this->url('estimate-option-item-update', array('clientId' => $this->clientId, 'estimateId' => $this->estimateEntity->getEstimateId(), 'estimateOptionId' => $itemEntity->getEstimateOptionId(), 'estimateOptionItemId' => $itemEntity->getEstimateOptionItemId())); ?>" title="<?php echo $this->translate('Edit this item'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i></a>
											<?php endif; ?>
                						</td>
                					</tr>
                					<?php $total = $total + $itemEntity->getEstimateOptionItemTotal(); ?>
                					<?php endforeach; ?>
                					</tbody>
                					<tfoot>
                						<tr>
                							<th colspan="4" class="text-right"><?php echo $this->translate('Total'); ?></th>
                							<th class="text-right"><?php echo $this->currencyFormat($total, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></th>
                							<th></th>
                						</tr>
                					</tfoot>
                				</table>
							</div>
							<?php endif; ?>
						</div>
					</div>
					<br />
					<?php endforeach; ?>
					<?php endif;?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h4 class="box-title">
					<i class="fa fa-newspaper-o"></i>
					<?php echo $this->translate('Estimate Options Specs & Details'); ?>
				</h4>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php if($this->optionEntitys->count() == 0):?>
					<div class="alert alert-info">
						<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This estimate has no options yet. Click new and create one.'); ?></p>
					</div>
				<?php else: ?>
				<?php $total = 0; ?>
				<?php foreach($this->optionEntitys as $key => $optionEntity): ?>
					<div class="row">
						<div class="col-xs-12">
							<h4 class="text-center"><?php echo strtoupper($optionEntity->getEstimateOptionTitle()); ?> <?php echo $this->translate('SPECS & DETAILS')?></h4>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $optionEntity->getEstimateOptionDecription(); ?></p>
						</div>
					</div>
					<?php foreach($optionEntity->getItemEntity() as $itemEntity): ?>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $itemEntity->getEstimateOptionItemDescription(); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<p><b><?php echo $this->translate('Amount'); ?></b> <?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
						</div>
					</div>
					<?php $total = $total + $itemEntity->getEstimateOptionItemTotal(); ?>
					<?php endforeach; ?>
					<div class="row">
						<div class="col-xs-12">
							<p><b><?php echo $this->translate('This Option Total Cost'); ?></b> <?php echo $this->currencyFormat($total, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
						</div>
					</div>
					<?php if(count($this->optionEntitys) > $key): ?>
					<hr />
					<?php endif; ?>
				<?php endforeach; ?>
				<?php endif; ?>	
			</div>
		</div>
	</div>
</div>
				
				