<li class="dropdown notifications-menu">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-bell-o"></i>
		<span class="label label-danger"><?php echo $this->notificationEntitys->getTotalItemCount(); ?></span>
	</a>
	<ul class="dropdown-menu">
		<li class="header">You have <?php echo $this->notificationEntitys->getTotalItemCount(); ?> notifications</li>
		<li>
			<ul class="menu">
			<?php if($this->notificationEntitys->getTotalItemCount() > 0): ?>
			<?php foreach($this->notificationEntitys as $notificationEntity): ?>
				<li><?php echo $notificationEntity->getNotificationText(); ?></li>
			<?php endforeach;?>
			<?php endif;?>
			
			</ul>
		</li>
		<li><a href="<?php echo $this->url('notification-clear'); ?>" title="<?php echo $this->translate('Clear Notifications'); ?>" class="text-center"><?php echo $this->translate('Clear Notifications'); ?></a></li>
	</ul>
</li>