<li class="dropdown notifications-menu">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-bell-o"></i>
		<span class="label label-danger"><?php echo $this->notificationEntitys->getTotalItemCount(); ?></span>
	</a>
	<ul class="dropdown-menu">
		<li class="header">You have <?php echo $this->notificationEntitys->getTotalItemCount(); ?> notifications</li>
		<li>
			<ul class="menu">
			<?php if($this->notificationEntitys->getTotalItemCount() > 0): ?>
			<?php foreach($this->notificationEntitys as $notificationEntity): ?>
				<li>
					<div class="row">
						<div class="col-xs-12">
							<p><?php echo $notificationEntity->getNotificationText(); ?></p>
						</div>
					</div>
					
				</li>
			<?php endforeach;?>
			<?php endif;?>
			</ul>
		</li>
	</ul>
</li>