<!-- messages -->
 		<a id="openMessages"></a>
 		<div class="box box-success">
 			<div class="box-header with-border">
     			<h3 class="box-title"><i class="fa fa-envelope f-fw"></i> <?php echo $this->translate('Messages'); ?></h3>
     			<div class="box-tools pull-right"></div>
     		</div>
 			<div class="box-body">
 				<div class="alert alert-info">
 					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('You have new messages'); ?></p>
 				</div>
 			</div>
 		</div>
 		