<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Edit Invoice Options'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
                    <div class="col-md-12">
                        <?php $element = $this->form->get('invoiceOptionEnableTax'); ?>
                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                            <?php echo $this->formElement($element); ?>
                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                            <?php if($this->formElementErrors($element)): ?>
                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-12">
                        <?php $element = $this->form->get('invoiceOptionEnableDiscount'); ?>
                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                            <?php echo $this->formElement($element); ?>
                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                            <?php if($this->formElementErrors($element)): ?>
                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('invoiceOptionMemo'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('invoiceOptionTerms'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				<?php echo $this->formElement($this->form->get('invoiceOptionId')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $("#invoiceOptionMemo").wysihtml5()
	  $("#invoiceOptionTerms").wysihtml5();;
  });
 </script>