
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Table structure for table `acl_resource`
--

CREATE TABLE IF NOT EXISTS `acl_resource` (
  `acl_resource_id` int(20) NOT NULL AUTO_INCREMENT,
  `acl_resource` varchar(100) NOT NULL,
  PRIMARY KEY (`acl_resource_id`),
  UNIQUE KEY `acl_resource` (`acl_resource`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=latin1;

--
-- RELATIONS FOR TABLE `acl_resource`:
--

--
-- Dumping data for table `acl_resource`
--

INSERT INTO `acl_resource` (`acl_resource_id`, `acl_resource`) VALUES
(117, 'account-create'),
(119, 'account-delete'),
(116, 'account-index'),
(151, 'account-ledger-view'),
(122, 'account-type-create'),
(123, 'account-type-delete'),
(121, 'account-type-index'),
(124, 'account-type-update'),
(125, 'account-type-view'),
(118, 'account-update'),
(120, 'account-view'),
(137, 'acl-create'),
(139, 'acl-delete'),
(136, 'acl-index'),
(127, 'acl-resource-create'),
(129, 'acl-resource-delete'),
(126, 'acl-resource-index'),
(128, 'acl-resource-update'),
(130, 'acl-resource-view'),
(132, 'acl-role-create'),
(134, 'acl-role-delete'),
(131, 'acl-role-index'),
(133, 'acl-role-update'),
(135, 'acl-role-view'),
(138, 'acl-update'),
(140, 'acl-view'),
(80, 'admin-index'),
(69, 'auth-create'),
(70, 'auth-delete'),
(68, 'auth-index'),
(73, 'auth-password'),
(71, 'auth-update'),
(72, 'auth-view'),
(5, 'client-create'),
(97, 'client-favorite-create'),
(98, 'client-favorite-delete'),
(96, 'client-favorite-index'),
(2, 'client-index'),
(4, 'client-update'),
(3, 'client-view'),
(81, 'config-index'),
(82, 'config-update'),
(10, 'employee-create'),
(11, 'employee-delete'),
(9, 'employee-index'),
(8, 'employee-password'),
(6, 'employee-profile'),
(7, 'employee-profile-update'),
(12, 'employee-update'),
(13, 'employee-view'),
(1, 'home'),
(107, 'host-attribute-create'),
(108, 'host-attribute-delete'),
(106, 'host-attribute-index'),
(109, 'host-attribute-update'),
(112, 'host-attribute-value-create'),
(113, 'host-attribute-value-delete'),
(111, 'host-attribute-value-index'),
(114, 'host-attribute-value-update'),
(115, 'host-attribute-value-view'),
(110, 'host-attribute-view'),
(15, 'host-create'),
(18, 'host-delete'),
(14, 'host-list'),
(20, 'host-type-create'),
(21, 'host-type-delete'),
(19, 'host-type-index'),
(22, 'host-type-update'),
(23, 'host-type-view'),
(16, 'host-update'),
(17, 'host-view'),
(25, 'invoice-create'),
(26, 'invoice-delete'),
(90, 'invoice-item-create'),
(91, 'invoice-item-delete'),
(24, 'invoice-list'),
(92, 'invoice-option-index'),
(93, 'invoice-option-update'),
(95, 'invoice-payemnt-delete'),
(94, 'invoice-payment-create'),
(153, 'invoice-payment-delete'),
(27, 'invoice-print'),
(28, 'invoice-update'),
(31, 'invoice-view'),
(29, 'invoice-workorder'),
(30, 'invoice-workorder-delete'),
(33, 'labor-create'),
(34, 'labor-delete'),
(32, 'labor-index'),
(35, 'labor-update'),
(36, 'labor-view'),
(39, 'location-create'),
(37, 'location-update'),
(38, 'location-view'),
(41, 'network-create'),
(42, 'network-delete'),
(40, 'network-list'),
(43, 'network-update'),
(44, 'network-view'),
(46, 'password-create'),
(47, 'password-delete'),
(45, 'password-list'),
(48, 'password-update'),
(49, 'password-view'),
(99, 'payment-option-index'),
(152, 'phone-view'),
(75, 'task-create'),
(76, 'task-delete'),
(74, 'task-list'),
(102, 'task-note-create'),
(103, 'task-note-delete'),
(101, 'task-note-list'),
(104, 'task-note-update'),
(105, 'task-note-view'),
(79, 'task-reminder'),
(77, 'task-update'),
(78, 'task-view'),
(52, 'user-create'),
(53, 'user-delete'),
(51, 'user-list'),
(50, 'user-profile'),
(54, 'user-update'),
(55, 'user-view'),
(142, 'vendor-bill-create'),
(143, 'vendor-bill-delete'),
(141, 'vendor-bill-index'),
(144, 'vendor-bill-update'),
(145, 'vendor-bill-view'),
(57, 'vendor-create'),
(58, 'vendor-delete'),
(56, 'vendor-index'),
(147, 'vendor-payment-create'),
(148, 'vendor-payment-delete'),
(146, 'vendor-payment-index'),
(149, 'vendor-payment-update'),
(150, 'vendor-payment-view'),
(59, 'vendor-update'),
(60, 'vendor-view'),
(67, 'workorder-complete'),
(62, 'workorder-create'),
(100, 'workorder-credit-create'),
(63, 'workorder-delete'),
(61, 'workorder-list'),
(83, 'workorder-note-create'),
(85, 'workorder-note-delete'),
(84, 'workorder-note-update'),
(86, 'workorder-part-create'),
(87, 'workorder-part-delete'),
(66, 'workorder-print'),
(88, 'workorder-time-create'),
(89, 'workorder-time-delete'),
(64, 'workorder-update'),
(65, 'workorder-view');
SET FOREIGN_KEY_CHECKS=1;
