<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<?php 
    $totalDeductions = $this->entity->getPayrollTaxFederalIncome() + 
    $this->entity->getPayrollTaxSocialSecurity() +
    $this->entity->getPayrollTaxState() +
    $this->entity->getPayrollTaxMedicare;
    
    $totalPay = $this->entity->getPayrollWages() +
    $this->entity->getPayrollWagesOt() +
    $this->entity->getPayrollWagesVacation() +
    $this->entity->getPayrollWagesSick();
    
    $totalNetPay = $totalPay - $totalDeductions;
    
    $ytdTotalDeductions = $this->ytdFederalIncomeTax + 
    $this->ytdSocialSecurityTax + 
    $this->ytdMedicareTax + 
    $this->ytdStateTax;
?>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar" aria-hidden="true"></i>
					<?php echo $this->translate('Payroll'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-print') ):?>
					<a href="<?php echo $this->url('payroll-print', array('payrollId' => $this->entity->getPayrollId()));?>" target="_blank" 
						title="<?php echo $this->translate('Print this payroll'); ?>" class="btn btn-box-tool"><i class="fa fa-print"></i> <?php echo $this->translate('Print'); ?></a>
					<?php endif; ?>
					
					<a href="javascript:void(0);" data-toggle="modal" data-target="#payrollDeductionModal" 
						title="<?php echo $this->translate('Add Deduction'); ?>" class="btn btn-box-tool">
							<i class="fa fa-plus"></i> <?php echo $this->translate('Add Deduction'); ?>
					</a>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-delete') ):?>
					<a href="<?php echo $this->url('invoice-delete', array('payrollId' => $this->entity->getPayrollId()));?>" 
						title="<?php echo $this->translate('Delete this payroll'); ?>" class="btn btn-box-tool">
							<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
					</a>
              		<?php endif; ?>
              		
              		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-update') ):?>
              		<a href="<?php echo $this->url('payroll-update', array('payrollId' => $this->entity->getPayrollId()));?>" 
              			title="<?php echo $this->translate('Edit this payroll'); ?>" class="btn btn-box-tool">
              				<i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?>
              		</a>
					<?php endif; ?>
				</div>
				<div class="box-body">
					<div class="row">
						<div class="col-xs-8">
							<?php echo $this->appConfig()->getConfigCompanyName();?>
							<p><?php echo $this->appConfig()->getConfigCompanyStreet(); ?><br />
								<?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?>
							</p>
						</div>
						<div class="col-xs-4 text-right">
							<h3><?php echo $this->translate('Earnings Statement'); ?></h3>
						</div>
					</div>
					
					<hr />
					
					<div class="row">
						<div class="col-xs-4">
							<p><b><?php echo $this->translate('Employee Name'); ?></b></p>
						</div>
						<div class="col-xs-2 text-center">
							<p><b><?php echo $this->translate('Social Security Id'); ?></b>
						</div>
						<div class="col-xs-2 text-center">
							<p><b><?php echo $this->translate('Employee Id'); ?></b></p>
						</div>
						<div class="col-xs-1 text-center">
							<p><b><?php echo $this->translate('Check'); ?></b></p>
						</div>
						<div class="col-xs-2 text-center">
							<p><b><?php echo $this->translate('Pay Period'); ?></b></p>
						</div>
						<div class="col-xs-1 text-center">
							<p><b><?php echo $this->translate('Pay Date'); ?></b></p>
						</div>
					</div>
					
					<div class="row">
						<div class="col-xs-4"><?php echo $this->entity->getEmployeeEntity()->getEmployeeName(); ?></div>
						<div class="col-xs-2 text-center"><?php echo $this->entity->getEmployeeEntity()->getEmployeeSsn(); ?></div>
						<div class="col-xs-2 text-center"><?php echo $this->entity->getEmployeeId(); ?></div>
						<div class="col-xs-1 text-center"><?php echo $this->entity->getPayrollCheck(); ?></div>
						<div class="col-xs-2 text-center">
							<?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateStart());?> -
							<?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateEnd());?>
						</div>
						<div class="col-xs-1 text-center"><?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateCreate());?></div>
					</div>
					
					<hr />
					
					<div class="row">
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-3">
									<p><b><?php echo $this->translate('Income'); ?></b></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><b><?php echo $this->translate('Rate'); ?></b></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><b><?php echo $this->translate('Hours'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Regular Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHours(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWages(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Over Time Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRateOt(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursOt(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesOt(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Vacation Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursVacation(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesVacation(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Sick Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursSick(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesSick(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
						</div>
						
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-6">
									<p><b><?php echo $this->translate('Deductions'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Year To Date'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Federal Income Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxFederalIncome(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdFederalIncomeTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Social Security Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxSocialSecurity(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdSocialSecurityTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Medicare Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxMedicare(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdMedicareTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('State Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxState(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdStateTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<?php if(count($this->payrollDeductionEntitys) > 0): ?>
							<?php foreach($this->payrollDeductionEntitys as $payrollDeductionEntity): ?>
							<div class="row">
								<div class="col-xs-6">
									<p>
										<a href="<?php echo $this->url('payroll-deduction-view', array('payrollDeductionId' => $payrollDeductionEntity->getPayrollDeductionId())); ?>" title="<?php echo $this->translate('View this deduction'); ?>">
											<?php echo $payrollDeductionEntity->getPayrollDeductionTypeEntity()->getPayrollDeductionTypeName(); ?>
										</a>
									</p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($payrollDeductionEntity->getPayrollDeductionAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($payrollDeductionEntity->getPayrollDeductionYtd(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<?php $totalDeductions = $totalDeductions + $payrollDeductionEntity->getPayrollDeductionAmount(); ?>
							<?php endforeach;?>
							<?php endif?>
						</div>
					</div>
					
					<hr />
					
					<div class="row">
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('YTD Gross'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('YTD Deductions'); ?></b></p>
								</div>
								<div class="col-xs-4">
									<p><b><?php echo $this->translate('YTD Net Pay'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($this->ytdGross, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($ytdTotalDeductions, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
								<div class="col-xs-4">
									<p><?php echo $this->currencyFormat($this->ytdNet, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
						</div>
						
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Deductions'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Net Pay'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($totalPay, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($totalDeductions, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesNet(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->form()->openTag($this->form); ?>
<div class="modal fade" id="payrollDeductionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">
					<i class="fa fa-dollar"></i> 
					<?php echo $this->translate('Add Deduction')?>
				</h4>
			</div>
			<div class="modal-body">
      			<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
      			
      			<div class="row">
      				<div class="col-xs-12 col-sm-8">
						<?php $element = $this->form->get('payrollDeductionTypeId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
					</div>
					
					<div class="col-xs-12 col-sm-4">
						<?php $element = $this->form->get('payrollDeductionAmount'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
					</div>
					
					<?php echo $this->formElement($this->form->get('payrollDeductionId')); ?>
					<?php echo $this->formElement($this->form->get('payrollId')); ?>
					<?php echo $this->formElement($this->form->get('payrollDeductionYear')); ?>
      			</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>