<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-group"></i>
					<?php echo $this->mspEntity->getName(); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<div class="box-body">
				<ul class="nav nav-tabs">
					<li role="presentation"><a href="<?php echo $this->url('panorama-view', array('cid' => $this->mspEntity->getCid())); ?>"><?php echo $this->translate('Devices')?></a></li>
					<li role="presentation" class="active"><a href="<?php echo $this->url('panorama-user', array('cid' => $this->mspEntity->getCid())); ?>"><?php echo $this->translate('Users'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Software'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Groups'); ?></a></li>
				</ul>
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Username'); ?></th>
							<th><?php echo $this->translate('Last seen'); ?></th>
							<th><?php echo $this->translate('Full name'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $userEntity): ?>
						<tr>
							<td><?php Echo $userEntity->getUsername(); ?></td>
							<td><?php echo $userEntity->getLastSeen(); ?></td>
							<td><?php echo $userEntity->getFullName(); ?></td>
						</tr>
					<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>