<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Work Order Options'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('workorder-option-update');?>" title="<?php echo $this->translate('Edit'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<?php if(! $this->optionEntity): ?>
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('Work Order Options have not been set up.'); ?>
				</div>
				<?php else: ?>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<div class="row">
							<div class="col-xs-12">
								<b><?php echo $this->translate('Disclaimer'); ?>:</b> <br />
								<?php echo $this->optionEntity->getWorkorderOptionDisclaimer(); ?>
							</div>
						</div>
					</li>
				</ul>
				<?php endif;?>
			</div>
		</div>
	</div>
</div>