<li class="dropdown tasks-menu">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-flag-o"></i>
		<span class="label label-warning"><?php echo $this->taksEntitys->getTotalItemCount(); ?></span>
	</a>
	<ul class="dropdown-menu">
		<li class="header"><?php echo $this->translate('You have')?> <?php echo $this->taksEntitys->getTotalItemCount(); ?> <?php echo $this->translate('tasks'); ?></li>
		<li>
			<ul class="menu">
			<?php if($this->taksEntitys->getTotalItemCount() != 0):?>
				<?php foreach($this->taksEntitys as $taskEntity): ?>
				<li>
					<a href="<?php echo $this->url('task-view', array('clientId' => $taskEntity->getClientId(), 'taskId' => $taskEntity->getTaskId()));?>" title="<?php echo $this->translate('View this task'); ?>">
						<?php echo $taskEntity->getTaskTitle(); ?>
					</a>
				</li>
				<?php endforeach;?>
				<?php endif;?>
			</ul>
		</li>
	</ul>
</li>