<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-shopping-cart" aria-hidden="true"></i>
					<?php echo $this->translate('Delete Product'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following product?'); ?></p>
				</div>
					<h3 class="profile-username">
						<i class="<?php echo $this->productEntity->getProductImage()?>"></i>
						<?php echo $this->productEntity->getProductName(); ?>
					</h3>
					<p class="text-muted"><?php echo $this->productEntity->getProductDescriptionShort(); ?></p>
					<p class="text-muted"><?php echo $this->productEntity->getProductDescriptionLong(); ?></p>
					<ul class="list-group list-group-unbordered">
    					<li class="list-group-item">
    						<b><?php echo $this->translate('Product ID'); ?>:</b>
    						<span class="pull-right"><?php echo $this->productEntity->getPRoductId(); ?></span>
    					</li>
    				</ul>
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>