<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar" aria-hidden="true"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools">
					<?php if($this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-create')): ?>
					<a href="<?php echo $this->url('payroll-create');?>" 
						title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool">
							<i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?>
					</a>
					<?php endif; ?>
				</div>
			</div>
			<?php if($this->paginator->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No payroll entries'); ?>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-bordered table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate('Payroll Id'); ?></th>
							<th><?php echo $this->translate('Employee'); ?></th>
							<th><?php echo $this->translate('Check'); ?></th>
							<th><?php echo $this->translate('Pay Period'); ?></th>
							<th><?php echo $this->translate('Gross Pay'); ?></th>
							<th><?php echo $this->translate('Net Pay'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $entity): ?>
						<tr>
							<td><a href="<?php echo $this->url('payroll-view', array('payrollId' => $entity->getPayrollId()));?>" title="<?php echo $this->translate('View Payroll'); ?>"><?php echo $entity->getPayrollId(); ?></a></td>
							<td><?php echo $entity->getEmployeeEntity()->getEmployeeName(); ?></td>
							<td></td>
							<td>
								<?php echo date($this->appConfig()->getConfigDateShort(), $entity->getPayrollDateStart()); ?> - 
								<?php echo date($this->appConfig()->getConfigDateShort(), $entity->getPayrollDateEnd()); ?>
							</td>
							<td><?php echo $this->currencyFormat($entity->getPayrollWages(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
							<td><?php echo $this->currencyFormat($entity->getPayrollWagesNet(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>