<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AclRole\Service\RoleService'                => __DIR__ . '/src/AclRole/Service/RoleService.php',
    'AclRole\Service\RoleServiceInterface'       => __DIR__ . '/src/AclRole/Service/RoleServiceInterface.php',
    'AclRole\Service\Factory\RoleServiceFactory' => __DIR__ . '/src/AclRole/Service/Factory/RoleServiceFactory.php',
    'AclRole\Mapper\RoleMapperInterface'         => __DIR__ . '/src/AclRole/Mapper/RoleMapperInterface.php',
    'AclRole\Mapper\RoleMapper'                  => __DIR__ . '/src/AclRole/Mapper/RoleMapper.php',
    'AclRole\Mapper\Factory\RoleMapperFactory'   => __DIR__ . '/src/AclRole/Mapper/Factory/RoleMapperFactory.php',
    'AclRole\Hydrator\RoleHydrator'              => __DIR__ . '/src/AclRole/Hydrator/RoleHydrator.php',
    'AclRole\Entity\RoleEntity'                  => __DIR__ . '/src/AclRole/Entity/RoleEntity.php',
    'AclRole\Module'                             => __DIR__ . '/Module.php',
);
