<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa phone"></i>
					<?php echo $this->translate('Call Log'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'call-log-create') ):?>
					<a href="<?php echo $this->url('call-log-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new call log'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>	
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
			<?php if($this->paginator->count() == 0): ?>
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no call logs');?></p>
				</div>
			<?php else: ?>
			<ul class="list-group list-group-unbordered">
			<?php foreach($this->paginator as $logEntity): ?>
			<li class="list-group-item">
				<div class="row">
					<div class="col-xs-12 col-sm-2">
    					<b><?php echo $this->translate('Call Date');?>: </b> 
    						<a href="<?php echo $this->url('call-log-view', array('clientId' => $this->clientId, 'callLogId' => $logEntity->getCallLogId()));?>" title="<?php echo $this->translate('View this call log'); ?>">
    							<?php echo date($this->appConfig()->getConfigDateLong(), $logEntity->getCallLogTime());?>
    						</a>
    				</div>
    				<div class="col-xs-12 col-sm-2">
    					<b><?php echo $this->translate('To')?>:</b> <?php echo $logEntity->getEmployeeEntity()->getEmployeeName();?>
    				</div>
    				<div class="col-xs-12 col-sm-7">
    					<?php echo $logEntity->getCallLogDetail();?>
    				</div>
    				<div class="col-xs-12 col-sm-1">
    					<b><?php echo $this->translate('Call Back'); ?>:</b> <?php echo ($logEntity->getCallLogRequireCallBack() == 1) ? $this->translate('Yes') : $this->translate('No');?>
    				</div>
				</div>
			</li>
			<?php endforeach;?>
			</ul>
			<div class="row">
					<div class="col-xs-12">
    				<?php echo $this->Paginator(
    	                        $this->itemCountPerPage,
    	                        $this->itemCount,
    	                        $this->pageCount,
    	                        $this->page,
    	                        $this->routeParams,
    	                        $this->queryParams); ?>
    	        	</div>
    			</div>
			<?php endif; ?>
			</div>
		</div>
	</div>
</div>