<li class="dropdown user user-menu">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<img src="/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
		<span class="hidden-xs"><?php echo $this->identity()->getAuthName(); ?></span>
	</a>
	<ul class="dropdown-menu">
		<!-- User image -->
		<li class="user-header">
			<img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
			<p><?php echo $this->identity()->getAuthName(); ?> - 
				<?php if($this->identity()->getEmployeeId() > 0): ?>
					<?php echo $this->identity()->getEmployeeEntity()->getEmployeeTitle();?>
				<?php else:?>
					<?php echo $this->identity()->getUserEntity()->getUserJobTitle(); ?>
				<?php endif;?>
				<small>Member since Nov. 2012</small>
			</p>
		</li>
		
		<!-- Menu Footer-->
		<li class="user-footer">
			<div class="pull-left">
				<?php if($this->identity()->getEmployeeId() > 0): ?>
					<a href="<?php echo $this->url('employee-profile'); ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Profile'); ?></a>
				<?php else: ?>
					<a href="<?php echo $this->url('user-profile'); ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Profile'); ?></a>
				<?php endif; ?>
			</div>
			<div class="pull-right">
				<a href="<?php echo $this->url('auth-sign-out'); ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Sign out'); ?></a>
			</div>
		</li>
	</ul>
</li>