<div class="box box-primary">
	<div class="box-header with-border">
		<h3 class="box-title">
			<i class="fa fa-cog"></i> <?php echo $this->translate('Auth Details'); ?>
 		</h3>
 		<div class="box-tools"></div>
 		<div class="box-body box-profile">
 			<h3 class="profile-username">
 				<?php echo $this->authEntity->getAuthName(); ?>
 			</h3>
 			<p class="text-muted"><?php echo $this->authEntity->getAuthEmail(); ?></p>
 			<ul class="list-group list-group-unbordered">
     			<li class="list-group-item">
     				 <b><?php echo $this->translate('Role');?></b> <a class="pull-right"><?php echo $this->authEntity->getAuthRole(); ?></a>
     			</li>
     			<li class="list-group-item">
     				<b><?php echo $this->translate('Type'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getAuthType(); ?></a>
      			</li>
      			<li class="list-group-item">
      				<b><?php echo $this->translate('Last Sign In'); ?></b> 
      				 <a class="pull-right"><?php echo ($this->authEntity->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $this->authEntity->getAuthLastLogin()) : $this->translate('Never Signed In'); ?></a>
      			</li>
      			<li class="list-group-item">
      				<b><?php echo $this->translate('Ip Address');?></b> <a class="pull-right"><?php echo ($this->authEntity->getAuthLastIp() != null) ? $this->authEntity->getAuthLastIp() : $this->translate('Never Signed In'); ?></a>
      			</li>
     		</ul>
 		</div>
 	</div>
</div>