<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InvoiceOption\Service\OptionServiceInterface'             => __DIR__ . '/src/InvoiceOption/Service/OptionServiceInterface.php',
    'InvoiceOption\Service\OptionsService'                     => __DIR__ . '/src/InvoiceOption/Service/OptionsService.php',
    'InvoiceOption\Service\Factory\OptionServiceFactory'       => __DIR__ . '/src/InvoiceOption/Service/Factory/OptionServiceFactory.php',
    'InvoiceOption\Controller\UpdateController'                => __DIR__ . '/src/InvoiceOption/Controller/UpdateController.php',
    'InvoiceOption\Controller\IndexController'                 => __DIR__ . '/src/InvoiceOption/Controller/IndexController.php',
    'InvoiceOption\Controller\Factory\IndexControllerFactory'  => __DIR__ . '/src/InvoiceOption/Controller/Factory/IndexControllerFactory.php',
    'InvoiceOption\Controller\Factory\UpdateControllerFactory' => __DIR__ . '/src/InvoiceOption/Controller/Factory/UpdateControllerFactory.php',
    'InvoiceOption\Form\OptionForm'                            => __DIR__ . '/src/InvoiceOption/Form/OptionForm.php',
    'InvoiceOption\Mapper\Factory\OptionMapperFactory'         => __DIR__ . '/src/InvoiceOption/Mapper/Factory/OptionMapperFactory.php',
    'InvoiceOption\Mapper\OptionMapperInterface'               => __DIR__ . '/src/InvoiceOption/Mapper/OptionMapperInterface.php',
    'InvoiceOption\Mapper\OptionMapper'                        => __DIR__ . '/src/InvoiceOption/Mapper/OptionMapper.php',
    'InvoiceOption\Hydrator\OptionHydrator'                    => __DIR__ . '/src/InvoiceOption/Hydrator/OptionHydrator.php',
    'InvoiceOption\Entity\OptionEntity'                        => __DIR__ . '/src/InvoiceOption/Entity/OptionEntity.php',
    'InvoiceOption\Module'                                     => __DIR__ . '/Module.php',
);
