<style>
@media print {
	footer {
		page-break-after: always;
	}
}
</style>
<section class="invoice small">
	<div class="row">
		<div class="col-xs-12 text-center">
			<h4><?php echo strtoupper($this->clientEntity->getClientName()); ?></h4>
			<hr style="margin-top: -8px; margin-bottom: -8px;" />
			<h4><?php echo strtoupper($this->estimateEntity->getEstimateTitle()); ?></h4>
		</div>
	</div>
	<br /> <br />
	<div class="row">
		<div class="col-xs-12 text-center">
			<h4><?php echo strtoupper($this->locationEntity->getLocationStreet()); ?></h4>
			<h4 style="margin-top: -8px; margin-bottom: -8px;"><?php echo strtoupper($this->locationEntity->getLocationCity()); ?>, <?php echo strtoupper($this->locationEntity->getLocationState()); ?> <?php echo strtoupper($this->locationEntity->getLocationZip()) ;?></h4>
			<h4><?php echo $this->phoneEntity->getPhoneNum(); ?></h4>
		</div>
	</div>
	<br /> <br />
	<div class="row">
		<div class="col-xs-12 text-center">
			<h4><?php echo strtoupper($this->translate('Created'));?> <?php echo date($this->appConfig()->getConfigDateShort(), $this->estimateEntity->getEstimateDateDue()); ?></h4>
			<h4 style="margin-top: -8px; margin-bottom: -8px;"><?php echo strtoupper($this->translate('by')); ?> <?php echo strtoupper($this->appConfig()->getConfigCompanyName()); ?></h4>
			<h4><?php echo $this->appConfig()->getConfigCompanyPhone(); ?></h4>
		</div>
	</div>
	<br /> <br />
	<div class="row">
		<div class="col-xs-12">
			<p><?php echo $this->estimateEntity->getEstimateOverview(); ?></p>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-xs-12">
			<p><?php echo $this->translate('This estimate is copy written by')?> <?php echo $this->appConfig()->getConfigCompanyName(); ?> <?php echo $this->translate('and may not be reproduced or copied.'); ?></p>
		</div>
	</div>

	<footer></footer>
</section>

<section class="invoice small">
<?php if($this->optionEntitys->count() == 0):?>
    <div class="alert alert-info">
		<p>
			<i class="fa fa-info-circle"></i> <?php echo $this->translate('This estimate has no options yet.'); ?></p>
	</div>
<?php else: ?>
	<?php foreach($this->optionEntitys as $optionEntity): ?>
					<div class="row">
		<div class="col-xs-12">
			<h4 class="text-center"><?php echo strtoupper($optionEntity->getEstimateOptionTitle()); ?></h4>
			<hr />
			<p><?php echo $optionEntity->getEstimateOptionDecription(); ?></p>
							<?php if($optionEntity->getItemEntity()->count() == 0): ?>
							<div class="alert alert-info">
				<p>
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('This option has no items.'); ?></p>
			</div>
							<?php else: ?>
							<?php $total = 0; ?>
							<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th class="col-xs-1"><?php echo $this->translate('Type'); ?></th>
							<th class="col-xs-1"><?php echo $this->translate('Quantity'); ?></th>
							<th><?php echo $this->translate('Description'); ?></th>
							<th class="col-xs-1 text-right"><?php echo $this->translate('Amount'); ?></th>
							<th class="col-xs-1 text-right"><?php echo $this->translate('Total'); ?></th>
						</tr>
					</thead>
					<tbody>
                					<?php foreach($optionEntity->getItemEntity() as $itemEntity): ?>
                					<tr>
							<td><?php echo  $this->translate($itemEntity->getEstimateOptionItemType());?></td>
							<td><?php echo $itemEntity->getEstimateOptionItemQty(); ?></td>
							<td><?php echo $itemEntity->getEstimateOptionTitle(); ?></td>
							<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
							<td class="text-right"><?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>

						</tr>
                					<?php $total = $total + $itemEntity->getEstimateOptionItemTotal(); ?>
                					<?php endforeach; ?>
                					</tbody>
					<tfoot>
						<tr>
							<th colspan="4" class="text-right"><?php echo $this->translate('Total'); ?></th>
							<th class="text-right"><?php echo $this->currencyFormat($total, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></th>

						</tr>
					</tfoot>
				</table>
			</div>
							<?php endif; ?>
						</div>
	</div>
	<br />
	<?php endforeach; ?>					
<?php endif;?>
<footer></footer>
</section>

<section class="invoice small">
<?php if($this->optionEntitys->count() == 0):?>
					<div class="alert alert-info">
		<p>
			<i class="fa fa-info-circle"></i> <?php echo $this->translate('This estimate has no options yet. Click new and create one.'); ?></p>
	</div>
				<?php else: ?>
				<?php $total = 0; ?>
				<?php foreach($this->optionEntitys as $key => $optionEntity): ?>
					<div class="row">
		<div class="col-xs-12">
			<h4 class="text-center"><?php echo strtoupper($optionEntity->getEstimateOptionTitle()); ?> <?php echo $this->translate('SPECS & DETAILS')?></h4>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p><?php echo $optionEntity->getEstimateOptionDecription(); ?></p>
		</div>
	</div>
					<?php foreach($optionEntity->getItemEntity() as $itemEntity): ?>
					<div class="row">
		<div class="col-xs-12">
			<p><?php echo $itemEntity->getEstimateOptionItemDescription(); ?></p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p>
				<b><?php echo $this->translate('Amount'); ?></b> <?php echo $this->currencyFormat($itemEntity->getEstimateOptionItemTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
		</div>
	</div>
					<?php $total = $total + $itemEntity->getEstimateOptionItemTotal(); ?>
					<?php endforeach; ?>
					<div class="row">
		<div class="col-xs-12">
			<p>
				<b><?php echo $this->translate('This Option Total Cost'); ?></b> <?php echo $this->currencyFormat($total, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
		</div>
	</div>
					<?php if(count($this->optionEntitys) > $key): ?>
					<hr />
					<?php endif; ?>
				<?php endforeach; ?>
				<?php endif; ?>	

	<footer></footer>
</section>