<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Acl\Service\AclService'                => __DIR__ . '/src/Acl/Service/AclService.php',
    'Acl\Service\AclServiceInterface'       => __DIR__ . '/src/Acl/Service/AclServiceInterface.php',
    'Acl\Service\Factory\AclServiceFactory' => __DIR__ . '/src/Acl/Service/Factory/AclServiceFactory.php',
    'Acl\Mapper\AclMapper'                  => __DIR__ . '/src/Acl/Mapper/AclMapper.php',
    'Acl\Mapper\Factory\AclMapperFactory'   => __DIR__ . '/src/Acl/Mapper/Factory/AclMapperFactory.php',
    'Acl\Mapper\AclMapperInterface'         => __DIR__ . '/src/Acl/Mapper/AclMapperInterface.php',
    'Acl\Hydrator\AclHydrator'              => __DIR__ . '/src/Acl/Hydrator/AclHydrator.php',
    'Acl\Entity\AclEntity'                  => __DIR__ . '/src/Acl/Entity/AclEntity.php',
    'Acl\Module'                            => __DIR__ . '/Module.php',
);
