<div class="box box-primary">
	<div class="box-header">
		<h3 class="box-title"><i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Signature')?></h3>
		<div class="box-tools">
		<?php if(! $this->workorderSignature): ?>
			<a href="#" title="<?php echo $this->translate('Sign Work Order');?>" class="btn btn-box-tool" data-toggle="modal" data-target="#signatureModal">
				<i class="fa fa-plus"></i> <?php echo $this->translate('New')?>
			</a>
		<?php endif; ?>
		</div>
    </div>
    <div class="box-body">
    	<?php if(! $this->workorderSignature): ?>
		<div class="alert alert-info">
			<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No signature'); ?>
		</div>
		<?php else: ?>
		<div class="row">
			<div class="col-xs-12">
				<img src="data:<?php echo $this->workorderSignature; ?>" class="mg-responsive"  style="max-width:99%" alt="<?php echo $this->translate('Work order signature'); ?>" />
			</div>
		</div>
		<?php endif;?>
	</div>
</div>