<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-group"></i>
					<?php echo $this->mspEntity->getName(); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<div class="box-body">
				<ul class="nav nav-tabs">
					<li role="presentation" class="active"><a href="#"><?php echo $this->translate('Devices')?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Users'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Software'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Groups'); ?></a></li>
				</ul>
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name'); ?>
							<th><?php echo $this->translate('Model'); ?>
							<th><?php echo $this->translate('Manufacture OS'); ?>
							<th><?php echo $this->translate('Domain'); ?>
							<th><?php echo $this->translate('Last seen'); ?>
							<th><?php echo $this->translate('Type'); ?>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $deviceEntity): ?>
						<tr <?php if(!$deviceEntity->getIsOnline()):?> class="text-danger"<?php endif;?>>
							<td><a href="<?php echo $this->url('panorama-view-device', array('cid' => $this->mspEntity->getCid(), 'deviceId' => $deviceEntity->getDeviceId()));?>" 
								title="<?php echo $this->translate('View device'); ?>">
								<?php echo $deviceEntity->getName(); ?>
								<?php if(!$deviceEntity->getIsOnline()):?>
								<span class="text-danger pull-right"><i class="fa fa-warning"></i> <?php echo $this->translate('Off-line'); ?></span>
								<?php endif;?>
								</a></td>
							<td><?php echo $deviceEntity->getModel(); ?></td>
							<td><?php echo $deviceEntity->getManufacturer(); ?></td>
							<td><?php echo $deviceEntity->getDomain(); ?></td>
							<td><?php echo $deviceEntity->getLastSeen();?></td>
							<td><?php echo $deviceEntity->getDeviceType();?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>