<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('New Ledger Item'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Pay From'); ?>:</b> <?php echo $this->accountEntity->getAccountName(); ?></p>
					</div>
				</div>
				
				<div class="row">
              		<div class="col-xs-12 col-sm-6">
						<?php $element = $this->form->get('accountId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	
              	
              	<div id="accountLedgerCreditAmountRow">
                  	<div class="row">
                  		<div class="col-xs-12 col-sm-2">
    						<?php $element = $this->form->get('accountLedgerCreditAmount'); ?>
    						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
    							<label class="control-label"><?php echo $element->getLabel() ?></label>
    							<?php echo $this->formElement($element); ?>
    							<?php if($this->formElementErrors($element)): ?>
    								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
    							<?php endif; ?>
    						</div>
                  		</div>
                  	</div>
              	</div>
              	
              	<div id="accountLedgerDebitAmountRow">
                  	<div class="row">
                  		<div class="col-xs-12 col-sm-2">
    						<?php $element = $this->form->get('accountLedgerDebitAmount'); ?>
    						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
    							<label class="control-label"><?php echo $element->getLabel() ?></label>
    							<?php echo $this->formElement($element); ?>
    							<?php if($this->formElementErrors($element)): ?>
    								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
    							<?php endif; ?>
    						</div>
                  		</div>
                  	</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-8">
						<?php $element = $this->form->get('accountLedgerMemo'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				
				<?php echo $this->formElement($this->form->get('accountLedgerType')); ?>
				<?php echo $this->formElement($this->form->get('fromAccountId')); ?>
				<?php echo $this->formElement($this->form->get('accountLedgerId')); ?>
				<?php echo $this->formElement($this->form->get('accountLedgerBalance')); ?>
				<?php echo $this->formElement($this->form->get('accountLedgerCreate')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>

<script>
	$('#accountLedgerDebitAmountRow').hide();

	$('#accountLedgerType').change(function(){

		if(this.value == 'Deposit') {
			$('#accountLedgerDebitAmountRow').hide();
			$('#accountLedgerCreditAmountRow').show();
		} else {
			$('#accountLedgerDebitAmountRow').show();
			$('#accountLedgerCreditAmountRow').hide();
		}
	});
</script>