<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Auth'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('auth-create');?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('E-Mail');?></th>
							<th><?php echo $this->translate('Name');?></th>
							<th><?php echo $this->translate('Type');?></th>
							<th><?php echo $this->translate('Role');?></th>
							<th><?php echo $this->translate('Last Sign In');?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $authEntity): ?>
						<tr>
							<td><a href="<?php echo $this->url('auth-view', array('authId' => $authEntity->getAuthId())); ?>" title="<?php echo $this->translate('View this auth'); ?>"><?php echo $authEntity->getAuthEmail(); ?></a></td>
							<td><?php echo $authEntity->getAuthName(); ?></td>
							<td><?php echo $authEntity->getAuthType(); ?></td>
							<td><?php echo ucwords($authEntity->getAuthRole()); ?></td>
							<td><?php echo ($authEntity->getAuthLastLogin() > 0) ? $authEntity->getAuthLastLogin() : $this->translate('Never Signed In'); ?></td>
							<td class="text-right">
								<a href="<?php echo $this->url('auth-delete', array('authId' => $authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Delete this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
								<a href="<?php echo $this->url('auth-update', array('authId' => $authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Edit this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>