<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('Labor'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('labor-delete', array('laborId' => $this->laborEntity->getLaborId()));?>" title="<?php echo $this->translate('Delete this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('labor-update', array('laborId' => $this->laborEntity->getLaborId()));?>" title="<?php echo $this->translate('Edit this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username"><?php echo $this->laborEntity->getLaborName(); ?></h3>
				<p class="text-muted"><?php echo $this->currencyFormat($this->laborEntity->getLaborAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('Labor Id')?></b> <a class="pull-right"><?php echo $this->laborEntity->getLaborId(); ?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>	
		