<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<li class="treeview <?php if($this->activeMenuItem == 'account'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-table"></i> <span><?php echo $this->translate('Accounting'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<?php echo $this->navigation('accountingMenu')->menu()->setPartial('partials/accounting-menu'); ?>
</li>