<ul class="treeview-menu">
<?php foreach($this->container as $key => $page): ?>

	<?php if (!$this->navigation()->accept($page)) continue; ?>
	
	<li <?php if ($page->isActive()):?> class="active"<?php endif;?>>
		<a href="<?php echo $page->getHref() ?>" title="<?php echo $this->escapeHtml($this->translate($page->getLabel())); ?>">
			<i class="<?php echo $page->get("icon"); ?>"></i>
			<?php echo $this->escapeHtml($this->translate($page->getLabel())); ?>
		</a>
	</li>
<?php endforeach;?>
</ul>