<?php if($this->workorderHistoryEntitys->count() == 0): ?>
	<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No History'); ?></p>
				</div>
				<?php else: ?>
				<table class="table table-bordered table-hover" id="HistoryTable">
					<thead>
						<tr>
							<th>Date</th>
							<th>Employee</th>
							<th>Note</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->workorderHistoryEntitys as $historyEntity): ?>
					<tr>
						<td><?php echo date($this->appConfig()->getConfigDateLong(), $historyEntity->getHistoryEntity()->getHistoryTime()); ?></td>
						<td><?php echo $historyEntity->getHistoryEntity()->getAuthEntity()->getAuthName(); ?></td>
						<td><?php echo $historyEntity->getHistoryEntity()->getHistoryNote(); ?></td>
					</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
				<?php endif;?>