<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->translate('Host Attribute Type'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('host-attribute-delete', array('hostAttributeId' => $this->attributeEntity->getHostAttributeId())); ?>" title="<?php echo $this->translate('Delete this host attribute'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('host-attribute-update', array('hostAttributeId' => $this->attributeEntity->getHostAttributeId())); ?>" title="<?php echo $this->translate('Edit this host attribute'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username"><?php echo $this->attributeEntity->getHostAttributeName(); ?></h3>
				<p class="text-muted"><?php echo $this->attributeEntity->getHostAttributeType();?></p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->translate('Attribute Values'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('host-attribute-value-create', array('hostAttributeId' => $this->attributeEntity->getHostAttributeId()));?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<?php if($this->paginator->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
    				<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This attribute has no values'); ?></p>
    			</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
    			<table class="table table-hover">
    				<thead>
    					<tr>
    						<th><?php echo $this->translate('Value'); ?></th>
    						<th></th>
    					</tr>
    				</thead>
    				<tbody>
    				<?php foreach($this->paginator as $valueEntity): ?>
    					<tr>
    						<td>
    							<a href="" title="<?php echo $this->translate('View this attribute value');?>">
    								<?php echo $valueEntity->getHostAttributeValueName()?>
    							</a>
    						</td>
    						<td class="text-right">
    							<a href="<?php echo $this->url('host-attribute-value-delete', array('hostAttributeId' => $valueEntity->getHostAttributeId(), 'hostAttributeValueId' => $valueEntity->getHostAttributeValueId())); ?>" title="<?php echo $this->translate('Delete this host attribute value'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
								<a href="<?php echo $this->url('host-attribute-value-update', array('hostAttributeId' => $valueEntity->getHostAttributeId(), 'hostAttributeValueId' => $valueEntity->getHostAttributeValueId())); ?>" title="<?php echo $this->translate('Edit this host attribute value'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
    						</td>
    					</tr>
    				<?php endforeach; ?>
    				</tbody>
				</table>
				
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
    				<?php echo $this->Paginator(
    	                        $this->itemCountPerPage,
    	                        $this->itemCount,
    	                        $this->pageCount,
    	                        $this->page,
    	                        $this->routeParams,
    	                        $this->queryParams); ?>
    	        	</div>
    			</div>
			</div>
			
			<?php endif; ?>
		</div>
	</div>
</div>