<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa phone"></i>
					<?php echo $this->translate('New Call Log'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
					<div class="col-xs-12 col-sm-8">
						<div class="row">
                      		<div class="col-xs-12">
        						<?php $element = $this->form->get('employeeId'); ?>
        						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        							<label class="control-label"><?php echo $element->getLabel() ?></label>
        							<?php echo $this->formElement($element); ?>
        							<?php if($this->formElementErrors($element)): ?>
        								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        							<?php endif; ?>
        						</div>
                      		</div>
                      	</div>
                      	
                      	<div class="row">
                      		<div class="col-xs-12">
        						<?php $element = $this->form->get('callLogDetail'); ?>
        						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        							<label class="control-label"><?php echo $element->getLabel() ?></label>
        							<?php echo $this->formElement($element); ?>
        							<?php if($this->formElementErrors($element)): ?>
        								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        							<?php endif; ?>
        						</div>
                      		</div>
                      	</div>
                      	
                      	<div class="row">
                      		<div class="col-xs-12 col-sm-4">
        						<?php $element = $this->form->get('callLogTime'); ?>
        						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        							<label class="control-label"><?php echo $element->getLabel() ?></label>
        							<?php echo $this->formElement($element); ?>
        							<?php if($this->formElementErrors($element)): ?>
        								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        							<?php endif; ?>
        						</div>
                      		</div>
                      	</div>
					</div>
					
					<div class="col-xs-12 col-sm-4">
						<div class="box box-default">
							<div class="box-body">
								<div class="row">
									<div class="col-xs-12">
										<?php $element = $this->form->get('callLogRequireCallBack'); ?>
                                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                                            <?php echo $this->formElement($element); ?>
                                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                                            <?php if($this->formElementErrors($element)): ?>
                                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                                            <?php endif; ?>
                                        </div>
									</div>
								</div>
								
								<div class="row">
									<div class="col-xs-12">
										<?php $element = $this->form->get('callLogWillCallBack'); ?>
                                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                                            <?php echo $this->formElement($element); ?>
                                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                                            <?php if($this->formElementErrors($element)): ?>
                                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                                            <?php endif; ?>
                                        </div>
									</div>
								</div>
								
								<div class="row">
									<div class="col-xs-12">
										<?php $element = $this->form->get('callLogVoiceMail'); ?>
                                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                                            <?php echo $this->formElement($element); ?>
                                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                                            <?php if($this->formElementErrors($element)): ?>
                                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                                            <?php endif; ?>
                                        </div>
									</div>
								</div>
								
								<div class="row">
									<div class="col-xs-12">
										<?php $element = $this->form->get('callLogUrgent'); ?>
                                        <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
                                            <?php echo $this->formElement($element); ?>
                                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                                            <?php if($this->formElementErrors($element)): ?>
                                                    <span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
                                            <?php endif; ?>
                                        </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<?php echo $this->formElement($this->form->get('clientId')); ?>
				<?php echo $this->formElement($this->form->get('callLogId')); ?>
				<?php echo $this->formElement($this->form->get('callLogRead')); ?>
				<?php echo $this->formElement($this->form->get('callLogCreatedBy')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $('#callLogTime').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY h:i a'});
	  $("#callLogDetail").wysihtml5();
  });
 </script>