<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Delete Payment'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following payment?'); ?></p>
				</div>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('Date'); ?>:</b>
						<a class="pull-right"><?php echo date($this->appConfig()->getConfigDateShort(), $this->paymentEntity->getInvoicePaymentDate()); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Method'); ?></b>
						<a class="pull-right"><?php echo $this->paymentEntity->getOptionEntity()->getPaymentOptionName(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Detail'); ?></b>
						<a class="pull-right"><?php echo $this->paymentEntity->getInvoicePaymentDetail(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Amount'); ?></b>
						<a class="pull-right"><?php echo $this->currencyFormat($this->paymentEntity->getInvoicePaymentAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></a>
					</li>
				</ul>
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>