<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'account/index/index'         => __DIR__ . '/view/account/index/index.phtml',
    'account/delete/index'        => __DIR__ . '/view/account/delete/index.phtml',
    'account/update/index'        => __DIR__ . '/view/account/update/index.phtml',
    'account/create/index'        => __DIR__ . '/view/account/create/index.phtml',
    'account/view/index'          => __DIR__ . '/view/account/view/index.phtml',
    'partials/account-aside-menu' => __DIR__ . '/view/partials/account-aside-menu.phtml',
);
