<div class="box box-primary">
	<div class="box-header">
		<h3 class="box-title"><i class="fa fa-desktop"></i> <?php echo $this->translate('Support Tickets')?></h3>
		<div class="box-tools">
		
		</div>
	</div>
	<div class="box-body">
		<?php if($this->ticketEntitys->count() == 0):?>
		<div class="alert alert-info">
			<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No tickets'); ?>
		</div>
		<?php else: ?>
		<ul class="list-group list-group-unbordered">
		<?php foreach($this->ticketEntitys as $ticketEntity): ?>
			<li class="list-group-item">
				<div class="row">
					<div class="col-xs-12">
						<p>
							<a href="<?php echo $this->url('ticket-view', array('clientId' => $ticketEntity->getClientId(), 'ticketId' => $ticketEntity->getTicketId())); ?>" title="<?php echo $this->translate('View this ticket'); ?>">
								<?php echo $ticketEntity->getTicketTitle();?>
							</a>	
							<span class="pull-right badge"><?php echo $ticketEntity->getTicketStatus(); ?></span>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<b><?php echo $this->translate('Created'); ?>:</b>
						<span class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $ticketEntity->getTicketDateOpen()); ?></span>
					</div>
				</div>
			</li>
		<?php endforeach;?>
		</ul>
		<?php endif; ?>
	</div>
</div>