<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-bank"></i>
					<?php echo $this->translate('Account Types'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('account-type-delete', array('accountTypeId' => $this->typeEntity->getAccountTypeId())); ?>" title="<?php echo $this->translate('Delete this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('account-type-update', array('accountTypeId' => $this->typeEntity->getAccountTypeId())); ?>" title="<?php echo $this->translate('Edit this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username"><?php echo $this->typeEntity->getAccountTypeName(); ?></h3>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-bank"></i>
					<?php echo $this->translate('Accounts'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no accounts of this type'); ?>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name'); ?></th>
							<th><?php echo $this->translate('Type'); ?></th>
							<th><?php echo $this->translate('Created'); ?></th>
							<th class="text-right"><?php echo $this->translate('Balance'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $accountEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('account-view', array('accountId' => $accountEntity->getAccountId())); ?>" title="<?php echo $this->translate('View this account'); ?>">
									<?php echo $accountEntity->getAccountName(); ?>
								</a>
							</td>
							<td><?php echo $accountEntity->getTypeEntity()->getAccountTypeName(); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateShort(), $accountEntity->getAccountCreated()); ?></td>
							<td class="text-right"><?php echo $this->currencyFormat($accountEntity->getAccountBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
    					<?php echo $this->Paginator(
    	                   $this->itemCountPerPage,
    	                   $this->itemCount,
    	                   $this->pageCount,
    	                   $this->page,
    	                   $this->routeParams,
    	                   $this->queryParams); 
    					?>
    	        	</div>
    			</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>