<?php if($this->timeEntitys->count() == 0): ?>
<div class="alert alert-info">
	<i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no times.'); ?>
</div>
<?php else: ?>
<ul class="list-group list-group-unbordered">
	<li class="list-group-item hidden-xs">
		<div class="row">
			<div class="col-xs-3">
    			<b><?php echo $this->translate('Employee'); ?></b>
    		</div>
    		<div class="col-xs-2">
    			<b><?php echo $this->translate('In'); ?></b>
    		</div>
    		<div class="col-xs-2">
    			<b><?php echo $this->translate('Out'); ?></b>
    		</div>
    		<div class="col-xs-1">
    			<b><?php echo $this->translate('Time'); ?></b>
    		</div>
    		<div class="col-xs-1">
    			<b><?php echo $this->translate('Rate'); ?></b>
    		</div>
    		<div class="col-xs-1">
    			<b><?php echo $this->translate('Total'); ?></b>
    		</div>
    	</div>
    </li>
    <?php foreach($this->timeEntitys as $timeEntity): ?>
    <li class="list-group-item">
    	<div class="row small">
    		<div class="col-xs-3">
    			<?php $employeeEntity = $timeEntity->getEmployeeEntity(); ?>
    			<?php if($this->displayLinks): ?>
    			<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'employee-view') ):?>
        			<a href="<?php echo $this->url('employee-view', array('employeeId' => $employeeEntity->getEmployeeId()));?>" title="<?php echo $this->translate('View this employee'); ?>" class="">
        				<?php echo $employeeEntity->getEmployeeName(); ?>
        			</a>
        		<?php else:?>
    				<?php echo $employeeEntity->getEmployeeName(); ?>
    			<?php endif;?>
    			<?php else: ?>
    				<?php echo $employeeEntity->getEmployeeName(); ?>
    			<?php endif;?>
    		</div>
    		<div class="col-xs-2">
    			<?php echo date($this->appConfig()->getConfigDateLong(), $timeEntity->getWorkorderTimeIn()); ?>
    		</div>
    		<div class="col-xs-2">
    			<?php echo date($this->appConfig()->getConfigDateLong(), $timeEntity->getWorkorderTimeOut()); ?>
    		</div>
    		<div class="col-xs-1 ">
    			<?php echo number_format(($timeEntity->getWorkorderTimeTotal() / 60) / 60, 2); ?>
    		</div>
    		<div class="col-xs-1 ">
    			<?php echo $this->currencyFormat($timeEntity->getLaborRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
    		</div>
    		<div class="col-xs-2">
    			<?php echo $this->currencyFormat(number_format(($timeEntity->getWorkorderTimeTotal() / 60) / 60, 2) *  $timeEntity->getLaborRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
    		</div>
    		<div class="col-xs-1">
    			<?php if($this->workorderEntity->getWorkorderStatus() == 'Active' && $this->displayLinks): ?>
    			<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-time-delete') ):?>
        			<a href="<?php echo $this->url('workorder-time-delete', array('clientId' => $this->workorderEntity->getClientId(), 'workorderId' => $this->workorderEntity->getWorkorderId(), 'workorderTimeId' => $timeEntity->getWorkorderTimeId())); ?>" 
        				title="<?php echo $this->translate('Delete this time'); ?>" class="btn btn-box-tool pull-right" style="margin-top:-4px;">
        				<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
        			</a>
        		<?php endif;?>
    			<?php endif; ?>
    		</div>
    	</div>
    </li>
    <?php endforeach; ?>
</ul>
  <?php endif;?>