<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->translate('Host Type'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('host-type-create');?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Host Type'); ?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->typeEntitys as $typeEntity): ?>
						<tr>
							<td><a href="<?php echo $this->url('host-type-view', array('hostTypeId' => $typeEntity->getHostTypeId())); ?>" title="<?php echo $this->translate('View host type'); ?>"><?php echo $typeEntity->getHostTypeName(); ?></a></td>
							<td class="text-right">
								<a href="<?php echo $this->url('host-type-delete', array('hostTypeId' => $typeEntity->getHostTypeId())); ?>" title="<?php echo $this->translate('Delete this host type'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
								<a href="<?php echo $this->url('host-type-update', array('hostTypeId' => $typeEntity->getHostTypeId())); ?>" title="<?php echo $this->translate('Edit this host type'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							</td>
						</tr>
					<?php endforeach; ?>	
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
</div>