<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">	
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('Bill Payment'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<div class="box-body">
				<div class="row">
        			<div class="col-xs-12">
        				<h3 class="profile-username"><?php echo $this->vendorEntity->getVendorName(); ?></h3>
        			</div>
        		</div>
				<ul class="list-group list-group-unbordered">
					
        			<li class="list-group-item">
        				<div class="row">
        					<div class="col-xs-12 col-sm-3">
        						<p><b><?php echo $this->translate('Date Due'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateShort(),$this->billEntity->getVendorBillDateDue()); ?></p>
        					</div>
        					<div class="col-xs-12 col-sm-3">
        						<p><b><?php echo $this->translate('Amount Due'); ?>:</b> <?php echo $this->currencyFormat($this->billEntity->getVendorBillAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
        					</div>
        					<div class="col-xs-12 col-sm-3">
        						<p><b><?php echo $this->translate('Balance'); ?>:</b> <?php echo $this->currencyFormat($this->billEntity->getVendorBillBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
        					</div>
        					<div class="col-xs-12 col-sm-3">
        						<p><b><?php echo $this->translate('Status'); ?>:</b> <?php echo $this->billEntity->getVendorBillStatus(); ?></p>
        					</div>
        				</div>
        			</li>
        		</ul>
			
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('accountId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('vendorPaymentAmount'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('vendorPaymentDate'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	<?php echo $this->formElement($this->form->get('vendorId')); ?>
              	<?php echo $this->formElement($this->form->get('vendorBillId')); ?>
              	<?php echo $this->formElement($this->form->get('vendorPaymentId')); ?>
				<?php echo $this->formElement($this->form->get('accountLedgerId')); ?>
				<?php echo $this->formElement($this->form->get('vendorPaymentActive')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $('#vendorPaymentDate').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
  });
 </script>