<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to remove the following host from this subscription?'); ?></p>
				</div>
				
				<table class="table table-hover">
                	<thead>
                		<tr>
                			<th><?php echo $this->translate('Host'); ?></th>
                			<th><?php echo $this->translate('Host Type'); ?></th>
                			<th></th>
                		</tr>
                	</thead>
                	<tbody>
                		<tr>
                			<td>
                				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'host-view') ):?>
                				<a href="<?php echo $this->url('host-view', array('clientId' => $this->entity->getHostEntity()->getClientId(), 'hostId' => $this->entity->getHostId())); ?>" 
                					title="<?php echo $this->translate('View this host'); ?>">
                					<?php echo $this->entity->getHostEntity()->getHostName(); ?>
                				</a> 
                				<?php else: ?>
                					<?php echo $this->entity->getHostEntity()->getHostName(); ?>
                				<?php endif; ?>
                			</td>
                			<td><?php echo $this->entity->getHostEntity()->getTypeEntity()->getHostTypeName(); ?></td>
                			<td class="text-right">
                				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'subscription-host-delete') ):?>
                				<a href="<?php echo $this->url('subscription-host-delete', array('clientId' => $this->entity->getHostEntity()->getClientId(), 'subscriptionHostId' => $this->entity->getSubscriptionHostId(), 'subscriptionId' => $this->entity->getSubscriptionId())); ?>" 
                					title="<?php echo $this->translate('Remove host from subscription'); ?>" class="btn btn-box-tool">
                						<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
                				</a>
                				<?php endif; ?>
                			</td>
                		</tr>
                	</tbody>
                </table>
				
				
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>
			