<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
 	<div class="col-md-3 col-sm-6 col-xs-12">
 	<div class="info-box">
 			<span class="info-box-icon bg-aqua"><i class="fa fa-wrench fa-fw"></i></span>
 			<div class="info-box-content">
 				<a href="#openWorkorders" title="<?php echo $this->translate('View open work orders'); ?>">
 					<span class="info-box-text"><?php echo $this->translate('Work Orders')?></span>
 					<span class="info-box-number"></span>
 				</a>
 			</div>
 		</div>
 	</div>
 	
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-green"><i class="fa fa-envelope fa-fw"></i></span>
 			<div class="info-box-content">
 				<a href="#openMessages" title="<?php echo $this->translate('View messages'); ?>">
 					<span class="info-box-text">Messages</span>
 					<span class="info-box-number">0</span>
 				</a>
 			</div>
 		</div>
 	</div>
 	
 	<!-- fix for small devices only -->
 	<div class="clearfix visible-sm-block"></div>
 	
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-red"><i class="fa fa-bell fa-fw"></i></span>
 			<div class="info-box-content">
 				<a href="#openHostAlerts" title="<?php echo $this->translate('View host alerts'); ?>">
 					<span class="info-box-text">Host Alerts</span>
 					<span class="info-box-number">0</span>
 				</a>
 			</div>
 		</div>
 	</div>
 	
 	<div class="col-md-3 col-sm-6 col-xs-12">
 		<div class="info-box">
 			<span class="info-box-icon bg-yellow"><i class="fa fa-flag f-fw"></i></span>
 			<div class="info-box-content">
 				<a href="#openTasks" title="<?php echo $this->translate('View open tasks'); ?>">
 					<span class="info-box-text"><?php echo $this->translate('Tasks'); ?></span>
 					<span class="info-box-number"></span>
 				</a>
 			</div>
 		</div>
 	</div>
 </div>
 
 <div class="row">
 	<div class="col-xs-12 col-sm-6">
 		<section id="employeeDetails"><?php echo $this->getEmployeeDetails($this->employeeId);?></section>
 	</div>
 	<div class="col-xs-12 col-sm-6">
 		<section id="authDetails"><?php echo $this->getEmployeeAuthDetails($this->authId);?></section>
 	</div>
 </div>
 
 <div class="row">
 	<div class="col-sm-4 col-xs-12">
 		<section id="openEmployeeTasks"><?php echo $this->getEmployeeTasks($this->employeeId);?></section>
 		
 		<section id="openCallLogs"><?php echo $this->getEmployeeCallLogs($this->employeeId); ?></section>
 		
 		<section id="openSupportTickets"><?php echo $this->Ticket(0, 'Open'); ?></section>
 	</div>
 	<div class="col-sm-8 col-xs-12">
 		<section id="openWorkorders"><?php echo $this->getEmployeeWorkorders($this->employeeId);?></section>
 		
 		<section id="openMessages"><?php echo $this->getEmployeeMessages($this->employeeId); ?></section>
 		
 		<section id="openHostAlerts">
 		<?php if($this->appConfig()->getConfigPanoramaKey()): ?>
 			<?php echo $this->GetAllIssues(); ?>
 		<?php endif;?>
 		</section>
 		
 	</div>
 </div>