<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-bank"></i>
					<?php echo $this->translate('View Account Ledger Item'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<h3 class="profile-username">
					<?php echo $this->accountEntity->getAccountName(); ?>
					<span class="badge pull-right"><?php echo $this->currencyFormat($this->accountEntity->getAccountBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></span>
				</h3>
				<p class="text-muted"><?php echo $this->accountEntity->getTypeEntity()->getAccountTypeName(); ?>
					<span class="pull-right small"><?php echo $this->accountEntity->getAccountNumber(); ?></span>
				</p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item"><?php echo $this->accountEntity->getAccountDescription(); ?></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-bank"></i>
					<?php echo $this->translate('Ledger Item'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Date'); ?>: </b> <?php echo $this->ledgerEntity->getAccountLedgerCreate(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Type'); ?>: </b> <?php echo $this->ledgerEntity->getAccountLedgerType(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Account'); ?>: </b> 
							<a href="<?php echo $this->url('account-view', array('accountId' => $this->ledgerEntity->getFromAccountId()));?>" title="<?php echo $this->translate('View this account'); ?>">
								<?php echo $this->ledgerEntity->getAccountEntity()->getAccountName(); ?>
							</a>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Type'); ?>: </b> <?php echo $this->ledgerEntity->getAccountLedgerType(); ?></p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Debit'); ?>: </b> <?php echo $this->currencyFormat($this->ledgerEntity->getAccountLedgerDebitAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Credit'); ?>: </b> <?php echo $this->currencyFormat($this->ledgerEntity->getAccountLedgerCreditAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Memo'); ?>:</b> <?php echo $this->ledgerEntity->getAccountLedgerMemo(); ?></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>