<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-life-ring" aria-hidden="true"></i>
					<?php echo $this->translate('New Support Ticket Note'); ?>
				</h3>
				<div class="box-tools">
					
				</div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('ticketNoteText'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<?php if($this->identity()->getAuthType() == 'Employee'): ?>
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('ticketNoteClientView'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				<?php else:?>
				<?php echo $this->formElement($this->form->get('ticketNoteClientView')); ?>
				<?php endif; ?>
				
				<?php echo $this->formElement($this->form->get('ticketNoteId')); ?>
				<?php echo $this->formElement($this->form->get('ticketId')); ?>
				<?php echo $this->formElement($this->form->get('authId')); ?>
				<?php echo $this->formElement($this->form->get('ticketNoteDateCreate')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $("#ticketNoteText").wysihtml5();
  });
 </script>