<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('Delete Labor Rate'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
    				<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following labor rate?'); ?></p>
    			</div>
    			<h3 class="profile-username"><?php echo $this->laborEntity->getLaborName(); ?></h3>
    			<p class="text-muted"><?php echo $this->currencyFormat($this->laborEntity->getLaborAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
    			<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>	
		