<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Delete Work Order Time'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following work order time?'); ?></p>
				</div>
				<h3 class="profile-username"><?php echo $this->workorderTimeEntity->getEmployeeEntity()->getEmployeeName(); ?></h3>
				<p class="text-muted"><?php echo $this->workorderTimeEntity->getLaborName(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('In'); ?>:</b>
						<span class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderTimeEntity->getWorkorderTimeIn()); ?></span>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Out'); ?>:</b>
						<span class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderTimeEntity->getWorkorderTimeOut()); ?></span>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Time'); ?>:</b>
						<span class="pull-right"><?php echo number_format(($this->workorderTimeEntity->getWorkorderTimeTotal() / 60) / 60, 2); ?></span>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Rate'); ?>:</b>
						<span class="pull-right"><?php echo $this->currencyFormat($this->workorderTimeEntity->getLaborRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></span>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Total'); ?>:</b>
						<span class="pull-right"><?php echo $this->currencyFormat(number_format(($this->workorderTimeEntity->getWorkorderTimeTotal() / 60) / 60, 2) *  $this->workorderTimeEntity->getLaborRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></span>
					</li>
				</ul>
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                 </form>
			</div>
		</div>
	</div>
</div>