<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AclResource\Service\ResourceService'                => __DIR__ . '/src/AclResource/Service/ResourceService.php',
    'AclResource\Service\Factory\ResourceServiceFactory' => __DIR__ . '/src/AclResource/Service/Factory/ResourceServiceFactory.php',
    'AclResource\Service\ResourceServiceInterface'       => __DIR__ . '/src/AclResource/Service/ResourceServiceInterface.php',
    'AclResource\Mapper\ResourceMapper'                  => __DIR__ . '/src/AclResource/Mapper/ResourceMapper.php',
    'AclResource\Mapper\Factory\ResourceMapperFactory'   => __DIR__ . '/src/AclResource/Mapper/Factory/ResourceMapperFactory.php',
    'AclResource\Mapper\ResourceMapperInterface'         => __DIR__ . '/src/AclResource/Mapper/ResourceMapperInterface.php',
    'AclResource\Hydrator\ResourceHydrator'              => __DIR__ . '/src/AclResource/Hydrator/ResourceHydrator.php',
    'AclResource\Entity\ResourceEntity'                  => __DIR__ . '/src/AclResource/Entity/ResourceEntity.php',
    'AclResource\Module'                                 => __DIR__ . '/Module.php',
);
