<div class="row">
	<div class="col-xs-12">
		<div class="box <?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>box-primary<?php else: ?>box-danger<?php endif; ?>">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('View Work Order'); ?>
				</h3>
				<div class="box-tools hidden-xs">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-print') ):?>
					<a href="<?php echo $this->url('workorder-print', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" target="_blank" title="<?php echo $this->translate('Print this work order'); ?>" class="btn btn-box-tool"><i class="fa fa-print"></i> <?php echo $this->translate('Print'); ?></a>
					<?php endif; ?>
					
					<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-credit-create') ):?>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#creditModal" title="<?php echo $this->translate('Add credit to this work order'); ?>" class="btn btn-box-tool"><i class="fa fa-dollar"></i> <?php echo $this->translate('Credit'); ?></a>
					<?php endif; ?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-complete') ):?>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#completeModal" title="<?php echo $this->translate('Complete this work order'); ?>" class="btn btn-box-tool"><i class="fa fa-check-circle"></i> <?php echo $this->translate('Complete'); ?></a>
					<?php endif; ?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-delete') ):?>
					<a href="<?php echo $this->url('workorder-delete', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Delete this work order'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<?php endif; ?>
					
					<?php endif;?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-update') ):?>
					<a href="<?php echo $this->url('workorder-update', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Edit this work order'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username">
					<?php echo $this->translate('Work Order #'); ?> <?php echo $this->workorderEntity->getWorkorderId(); ?>
					<span class="pull-right badge"><?php echo $this->workorderEntity->getWorkorderStatus(); ?></span>
				</h3>
				<p><?php echo $this->workorderEntity->getWorkorderDescription(); ?></p>
				<hr />
				<div class="row">
					<div class="col-xs-12 col-sm-9">
						<p>
    						<b><?php echo $this->translate('Location'); ?>:</b>
    						<?php if(! $this->workorderEntity->getLocationEntity()):?>
    							<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing location.')?></span>
    						<?php else: ?>
    							<?php $locationEntity = $this->workorderEntity->getLocationEntity(); ?>
    							<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
    							<a href="<?php echo $this->url('location-view', array('clientId' => $this->clientId, 'locationId' => $locationEntity->getLocationId())); ?>" title="<?php echo $this->translate('View this location'); ?>">
    							<?php echo $locationEntity->getLocationStreet();?> <?php echo $locationEntity->getLocationCity(); ?>, <?php echo $locationEntity->getLocationState();?> <?php echo $locationEntity->getLocationZip(); ?>
    							</a>
    							<?php else: ?>
    							<?php echo $locationEntity->getLocationStreet();?> <?php echo $locationEntity->getLocationCity(); ?>, <?php echo $locationEntity->getLocationState();?> <?php echo $locationEntity->getLocationZip(); ?>
    							<?php endif;?>
							<?php endif; ?>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Phone'); ?>:</b>
    						<?php if(! $this->workorderEntity->getPhoneEntity()) :?>
    							<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing phone.')?></span>
    						<?php else: ?>
    							<?php $phoneEntity = $this->workorderEntity->getPhoneEntity(); ?>
    							
    							<a href="tel:<?php echo $phoneEntity->getPhoneNum();?>" title="<?php echo $this->translate('call this phone number'); ?>">
    								<?php echo $phoneEntity->getPhoneNum();?>
    							</a>
    							
    						<?php endif; ?>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Scheduled')?>:</b> 
    						<?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderEntity->getWorkorderDateScheduled()); ?>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Created'); ?>:</b>
    						<?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderEntity->getWorkorderDateCreate()); ?>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Closed'); ?>:</b>
    						
    						<?php if($this->workorderEntity->getWorkorderStatus() == "Closed"): ?>
    							<?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderEntity->getWorkorderDateClose()); ?>
    						<?php else: ?>
    							
    							<?php echo $this->translate($this->workorderEntity->getWorkorderStatus()); ?>
    						<?php endif;?>
    					</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Contact'); ?>:</b>
    						<?php if(! $this->workorderEntity->getUserEntity()): ?>
    							<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing contact.')?></span>
    						<?php else: ?>
    							<?php $userEntity = $this->workorderEntity->getUserEntity(); ?>
    							<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
    							<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $userEntity->getUserId()));?>" title="<?php echo $this->translate('View this user'); ?>">
    								<?php echo $userEntity->getUserNameFirst(); ?> <?php echo $userEntity->getUserNameLast(); ?>
    							</a>
    							<?php else: ?>
    								<?php echo $userEntity->getUserNameFirst(); ?> <?php echo $userEntity->getUserNameLast(); ?>
    							<?php endif; ?>
    						<?php endif;?>
    					</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<p>
    						<b><?php echo $this->translate('Ends'); ?>:</b>
    						 <?php if($this->workorderEntity->getWorkorderDateEnd() == 0):?>
    						 	<span class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->translate('Missing end date'); ?></span>
    						 <?php else: ?>
    						 <?php echo date($this->appConfig()->getConfigDateLong(), $this->workorderEntity->getWorkorderDateEnd()); ?>
    						 <?php endif;?>
    						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
							<b><?php echo $this->translate('Labor'); ?>:</b>
						 	<?php echo $this->currencyFormat($this->workorderEntity->getWorkorderLabor(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
							<b><?php echo $this->translate('Parts'); ?>:</b>
							<?php echo $this->currencyFormat($this->workorderEntity->getWorkorderParts(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
						</p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p>
							<b><?php echo $this->translate('Credit'); ?>:</b>
							<span class="<?php ($this->creditTotal > 0) ? 'text-success' : 'text-danger'; ?>">
							<?php echo $this->currencyFormat($this->creditTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
							</span>
						</p>
					</div>
				</div>
				
			</div>
			<div class="box-footer visible-xs">
				<a href="<?php echo $this->url('workorder-print', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Print this work order'); ?>" class="btn btn-sm btn-flat btn-default"><i class="fa fa-print"></i> <?php echo $this->translate('Print'); ?></a>
				<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>  			
    			<a href="javascript:void(0);" data-toggle="modal" data-target="#creditModal" title="<?php echo $this->translate('Credit this work order'); ?>" class="btn btn-sm btn-flat btn-default"><i class="fa fa-dollar"></i> <?php echo $this->translate('Credit'); ?></a>
    			<a href="javascript:void(0);" data-toggle="modal" data-target="#completeModal" title="<?php echo $this->translate('Complete this work order'); ?>" class="btn btn-sm btn-flat btn-default"><i class="fa fa-check-circle"></i> <?php echo $this->translate('Complete'); ?></a>
    			<a href="<?php echo $this->url('workorder-delete', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Delete this work order'); ?>" class="btn btn-sm btn-flat btn-default"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
    			<?php endif;?>
    			<a href="<?php echo $this->url('workorder-update', array('workorderId' => $this->workorderEntity->getWorkorderId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Edit this work order'); ?>" class="btn btn-sm btn-flat btn-default"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>		
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-8">
		<!-- Notes -->
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title"><i class="fa fa-list-alt"></i> <?php echo $this->translate('Notes')?></h3>
				<div class="box-tools">
					<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-note-create') ):?>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#noteModal" title="<?php echo $this->translate('Add new note'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<?php echo $this->getWorkorderNotes($this->workorderEntity); ?>
    		</div>
		</div>
		
		<!-- Times -->
		<div class="box box-primary">
		
			<div class="box-header">
				<h3 class="box-title"><i class="fa fa-clock-o"></i> <?php echo $this->translate('Times')?></h3>
				<div class="box-tools">
					<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-time-create') ):?>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#timeModal" title="<?php echo $this->translate('Add new time'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
					<?php endif;?>
				</div>
			</div>
			
			<div class="box-body">
				<?php echo $this->getWorkorderTimes($this->workorderEntity);?>
    		</div>
		</div>
					
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title"><i class="fa fa-hdd-o"></i> <?php echo $this->translate('Parts')?></h3>
				<div class="box-tools">
					<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-part-create') ):?>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#partModal" title="<?php echo $this->translate('Add new part'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
					<?php endif;?>
				</div>
			</div>
			<div class="box-body">
				<?php echo $this->getWorkorderParts($this->workorderEntity);?>
    		</div>
		</div>
	</div>
	
	<div class="col-xs-12 col-sm-4">
	
		<div class="box box-primary">
    		<div class="box-header">
    			<h3 class="box-title"><i class="fa fa-user"></i> <?php echo $this->translate('Employee')?></h3>
    			<div class="box-tools">
    			<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
    				<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'employee-view') ):?>
    				<a href="javascript:void(0);" data-toggle="modal" data-target="#employeeModal" title="<?php echo $this->translate('Add new employee'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
    				<?php endif; ?>
    			<?php endif;?>
    			</div>
    		</div>
    		<div class="box-body">
    			<?php if($this->workorderEmployeEntitys->count() == 0): ?>
    				<div class="alert alert-info">
    					<i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no employees.'); ?>
    				</div>
    			<?php else:?>
    			<ul class="list-group list-group-unbordered">
    				<?php foreach($this->workorderEmployeEntitys as $workorderEmployeEntity): ?>
    				<li class="list-group-item">
    					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'employee-view') ):?>
        					<a href="<?php echo $this->url('employee-view', array('employeeId' => $workorderEmployeEntity->getEmployeeEntity()->getEmployeeId()));?>" title="<?php echo $this->translate('View this employee');?>">
        						<?php echo $workorderEmployeEntity->getEmployeeEntity()->getEmployeeName(); ?>
        					</a>
        				<?php else: ?>
    						<?php echo $workorderEmployeEntity->getEmployeeEntity()->getEmployeeName(); ?>
    					<?php endif;?>
    					
    					<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
        					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'employee-view') ):?>
        						<a href="" title="<?php echo $this->translate('Remove this employee'); ?>" class="btn btn-box-tool pull-right" style="margin-top:-4px;"><i class="fa fa-times"></i> <?php echo $this->translate('Remove'); ?></a>
        					<?php endif; ?>
    					<?php endif; ?>
    				</li>
    				<?php endforeach; ?>
    			</ul>
    			<?php endif;?>
    		</div>
    	</div>
    	
    	<div class="box box-primary">
    		<div class="box-header">
    			<h3 class="box-title"><i class="fa fa-credit-card"></i> <?php echo $this->translate('Invoice')?></h3>
    		</div>
    		<div class="box-body">
    			<?php if($this->workorderEntity->getInvoiceId() == 0): ?>
    			<div class="alert alert-info">
    				<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No Invoice'); ?></p>
    			</div>
    			<?php else: ?>
    			<p>
    				<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'invoice-view') ):?>
    				<a href="<?php echo $this->url('invoice-view', array('clientId' => $this->clientId, 'invoiceId' => $this->workorderEntity->getInvoiceId()));?>" title="<?php echo $this->translate('View this invoice');?>">
    					<?php echo $this->translate('Invoice #');?><?php echo $this->workorderEntity->getInvoiceId();?>
    				</a>
    				<?php else: ?>
    					<?php echo $this->translate('Invoice #');?><?php echo $this->workorderEntity->getInvoiceId();?>
    				<?php endif; ?>
    			</p>
    			<?php endif;?>
    		</div>
    	</div>

		<div class="box box-primary">
    		<div class="box-header">
    			<h3 class="box-title"><i class="fa fa-dollar"></i> <?php echo $this->translate('Credits')?></h3>
    		</div>
    		<div class="box-body">
    			<?php echo $this->getWorkorderCredit($this->workorderEntity);?>
    		</div>
    	</div>

    	<div class="box box-primary">
    		<div class="box-header">
    			<h3 class="box-title"><?php echo $this->translate('Files')?></h3>
    			<div class="box-tools">
    				<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
    				<a href="" title="<?php echo $this->translate('Add new file'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
    				<?php endif;?>
    			</div>
    		</div>
    		<div class="box-body">
    			<div class="alert alert-info">
    				<i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no files.'); ?>
    			</div>
    		</div>
    	</div>
	</div>
</div>

<?php if($this->workorderEntity->getWorkorderStatus() == 'Active'): ?>
<?php echo $this->form()->openTag($this->noteForm); ?>
<!-- note modal -->
<div class="modal fade" id="noteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-list-alt"></i> <?php echo $this->translate('Work Order Note')?></h4>
      </div>
      <div class="modal-body">
       	<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->noteForm->getMessages())); ?>
       	
       	<div class="row">
        	<div class="col-xs-12">
				<?php $element = $this->noteForm->get('workorderNotesNote'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
       </div>
       
       <div class="row">
        	<div class="col-xs-12 col-sm-4">
				<?php $element = $this->noteForm->get('workorderNotesDate'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
       </div>
       	
       	<div class="row">
        	<div class="col-xs-12 col-sm-4">
				<?php $element = $this->noteForm->get('employeeId'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
       </div>
       	
       	<?php echo $this->formElement($this->noteForm->get('workorderId')); ?>
       	<?php echo $this->formElement($this->noteForm->get('workorderNotesId')); ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
        <?php echo $this->formSubmit($this->noteForm->get('submit')); ?>
      </div>
    </div>
  </div>
</div>
<?php echo $this->form()->closeTag(); ?>


<!-- time modal -->
<?php echo $this->form()->openTag($this->timeForm); ?>
<div class="modal fade" id="timeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-clock-o"></i> <?php echo $this->translate('Work Order Time')?></h4>
      </div>
      <div class="modal-body">
        <?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->timeForm->getMessages())); ?>
        
        <div class="row">
        	<div class="col-xs-12 col-sm-6">
				<?php $element = $this->timeForm->get('workorderTimeIn'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-6">
				<?php $element = $this->timeForm->get('laborId'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-6">
				<?php $element = $this->timeForm->get('employeeId'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
       
        <?php echo $this->formElement($this->timeForm->get('workorderId')); ?>
       	<?php echo $this->formElement($this->timeForm->get('workorderTimeId')); ?>
       	<?php echo $this->formElement($this->timeForm->get('workorderTimeOut')); ?>
       	<?php echo $this->formElement($this->timeForm->get('workorderTimeTotal')); ?>
       	<?php echo $this->formElement($this->timeForm->get('laborName')); ?>
       	<?php echo $this->formElement($this->timeForm->get('laborRate')); ?>
       	<?php echo $this->formElement($this->timeForm->get('laborTotal')); ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
        <?php echo $this->formSubmit($this->timeForm->get('submit')); ?>
      </div>
    </div>
  </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<!-- part modal -->
<?php echo $this->form()->openTag($this->partForm); ?>
<div class="modal fade" id="partModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-hdd-o"></i> <?php echo $this->translate('Work Order Part')?></h4>
      </div>
      <div class="modal-body">
        <?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->partForm->getMessages())); ?>
        
        <div class="row">
        	<div class="col-xs-12 col-sm-2">
				<?php $element = $this->partForm->get('workorderPartsQty'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
        
        <div class="row">
        	<div class="col-xs-12">
				<?php $element = $this->partForm->get('workorderPartsDescription'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-2">
				<?php $element = $this->partForm->get('workorderPartsAmount'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
        
        <?php echo $this->formElement($this->partForm->get('workorderId')); ?>
       	<?php echo $this->formElement($this->partForm->get('workorderPartsId')); ?>
       	<?php echo $this->formElement($this->partForm->get('workorderPartsTotal')); ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
         <?php echo $this->formSubmit($this->partForm->get('submit')); ?>
      </div>
    </div>
  </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<!-- employee modal -->
<div class="modal fade" id="employeeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-user"></i> <?php echo $this->translate('Work Order Employee')?></h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
      </div>
    </div>
  </div>
</div>


<!-- complete modal -->
<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-complete') ):?>
<?php echo $this->form()->openTag($this->completeForm); ?>
<div class="modal fade" id="completeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-user"></i> <?php echo $this->translate('Complete Work Order')?></h4>
      </div>
      <div class="modal-body">
        <?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->completeForm->getMessages())); ?>
        
       
        
        <div class="row">
        	<div class="col-xs-12 col-sm-4">
				<?php $element = $this->completeForm->get('workorderDateClose'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
			<div class="col-md-12">
				<?php $element = $this->completeForm->get('createInvoice'); ?>
					<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
    					<?php echo $this->formElement($element); ?>
    					<label class="control-label"><?php echo $element->getLabel() ?></label>
    					<?php if($this->formElementErrors($element)): ?>
    						<span class="text-danger"><?php echo $this->formElementErrors($element) ?></span>
    					<?php endif; ?>
					</div>
			</div>
		</div>
         
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
        <?php echo $this->formSubmit($this->partForm->get('submit')); ?>
      </div>
    </div>
  </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<?php endif;?>
<?php endif; ?>

<!-- credit form -->
<?php echo $this->form()->openTag($this->creditForm); ?>
<div class="modal fade" id="creditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-dollar"></i> <?php echo $this->translate('Add Credit To Work Order')?></h4>
      </div>
      <div class="modal-body">
        <?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->completeForm->getMessages())); ?>
        
        <div class="row">
        	<div class="col-xs-12 col-sm-4">
				<?php $element = $this->creditForm->get('paymentOptionId'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-3">
				<?php $element = $this->creditForm->get('workorderCreditType'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-2">
				<?php $element = $this->creditForm->get('workorderCreditAmount'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-6">
				<?php $element = $this->creditForm->get('workorderCreditDetail'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
         
         <div class="row">
        	<div class="col-xs-12 col-sm-6">
				<?php $element = $this->creditForm->get('accountId'); ?>
				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
					<label class="control-label"><?php echo $element->getLabel() ?></label>
					<?php echo $this->formElement($element); ?>
					<?php if($this->formElementErrors($element)): ?>
						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
					<?php endif; ?>
				</div>
           </div>
         </div>
        
        <?php echo $this->formElement($this->creditForm->get('workorderId')); ?>
        <?php echo $this->formElement($this->creditForm->get('accountLedgerId')); ?>
        <?php echo $this->formElement($this->creditForm->get('workorderCreditDate')); ?>
        <?php echo $this->formElement($this->creditForm->get('workorderCreditAmountLeft')); ?>
        <?php echo $this->formElement($this->creditForm->get('workorderCreditId')); ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
        <?php echo $this->formSubmit($this->creditForm->get('submit')); ?>
      </div>
    </div>
  </div>
</div>
<?php echo $this->form()->closeTag(); ?>
       

<script>
  $(function () {
	  $('#workorderNotesDate').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
	  $('#workorderDateClose').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
	  $('#workorderTimeIn').daterangepicker({timePicker: true, timePickerIncrement: 15, format: 'MM/DD/YYYY h:mm A'});
	  $("#workorderNotesNote").wysihtml5();
  });
 </script>