<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Location\Service\LocationServiceInterface'           => __DIR__ . '/src/Location/Service/LocationServiceInterface.php',
    'Location\Service\LocationService'                    => __DIR__ . '/src/Location/Service/LocationService.php',
    'Location\Service\Factory\LocationServiceFactory'     => __DIR__ . '/src/Location/Service/Factory/LocationServiceFactory.php',
    'Location\Controller\ViewController'                  => __DIR__ . '/src/Location/Controller/ViewController.php',
    'Location\Controller\CreateController'                => __DIR__ . '/src/Location/Controller/CreateController.php',
    'Location\Controller\UpdateController'                => __DIR__ . '/src/Location/Controller/UpdateController.php',
    'Location\Controller\Factory\CreateControllerFactory' => __DIR__ . '/src/Location/Controller/Factory/CreateControllerFactory.php',
    'Location\Controller\Factory\ViewControllerFactory'   => __DIR__ . '/src/Location/Controller/Factory/ViewControllerFactory.php',
    'Location\Controller\Factory\UpdateControllerFactory' => __DIR__ . '/src/Location/Controller/Factory/UpdateControllerFactory.php',
    'Location\Validator\HasPrimary'                       => __DIR__ . '/src/Location/Validator/HasPrimary.php',
    'Location\Form\LocationForm'                          => __DIR__ . '/src/Location/Form/LocationForm.php',
    'Location\Form\Factory\LocationFormFactory'           => __DIR__ . '/src/Location/Form/Factory/LocationFormFactory.php',
    'Location\Mapper\LocationMapperInterface'             => __DIR__ . '/src/Location/Mapper/LocationMapperInterface.php',
    'Location\Mapper\Factory\LocationMapperFactory'       => __DIR__ . '/src/Location/Mapper/Factory/LocationMapperFactory.php',
    'Location\Mapper\LocationMapper'                      => __DIR__ . '/src/Location/Mapper/LocationMapper.php',
    'Location\Hydrator\LocationHydrator'                  => __DIR__ . '/src/Location/Hydrator/LocationHydrator.php',
    'Location\Entity\LocationEntity'                      => __DIR__ . '/src/Location/Entity/LocationEntity.php',
    'Location\Module'                                     => __DIR__ . '/Module.php',
);
