<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
					<div class="col-xs-12 col-sm-6">
    					<div class="row">
							<div class="col-xs-12">
								<?php $element = $this->form->get('hostId'); ?>
								<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
									<label class="control-label"><?php echo $element->getLabel() ?></label>
									<?php echo $this->formElement($element); ?>
									<?php if($this->formElementErrors($element)): ?>
										<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
									<?php endif; ?>
            					</div>
							</div>
						</div>
					</div>
				</div>
				
				<?php echo $this->formElement($this->form->get('subscriptionHostId')); ?>
				<?php echo $this->formElement($this->form->get('subscriptionId')); ?>
				<?php echo $this->formElement($this->form->get('subscriptionHostCreated')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>	
			</div>
		</div>
	</div>
</div>
			