<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Create Work Order'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('workorderDescription'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				
				<div class="row">
              		<div class="col-xs-12 col-sm-6">
						<?php $element = $this->form->get('locationId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-6">
						<?php $element = $this->form->get('workorderDateScheduled'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->form->get('workorderStatus'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->workorderEmployeeForm->get('employeeId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				
				<?php echo $this->formElement($this->form->get('workorderId')); ?>
				<?php echo $this->formElement($this->form->get('clientId')); ?>
				<?php echo $this->formElement($this->form->get('userId')); ?>
				<?php echo $this->formElement($this->form->get('phoneId')); ?>
				<?php echo $this->formElement($this->form->get('workorderLabor')); ?>
				<?php echo $this->formElement($this->form->get('workorderParts')); ?>
				<?php echo $this->formElement($this->form->get('workorderDateCreate')); ?>
				<?php echo $this->formElement($this->form->get('workorderDateEnd')); ?>
				<?php echo $this->formElement($this->form->get('workorderDateClose')); ?>
				<?php echo $this->formElement($this->form->get('invoiceId')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $('#workorderDateScheduled').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
	  $("#workorderDescription").wysihtml5();
  });
 </script>