<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-tasks"></i>
					<?php echo $this->translate('Tasks'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('task-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new task'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<ul class="list-group list-group-unbordered">
				
    				<li class="list-group-item">
            			<form class="form-inline">
                			<div class="row">
                				<div class="col-xs-12">
                					<div class="form-group">
                        				<select class="form-control input-sm" name="taskStatus" id="taskStatus">
                        					<option value=""><?php echo $this->translate('Status'); ?></option>
                        					<option value="Active" <?php if($this->taskStatus == 'Active'):?> selected <?php endif?>><?php echo $this->translate('Active'); ?></option>
                        					<option value="Closed" <?php if($this->taskStatus == 'Closed'):?> selected <?php endif?>><?php echo $this->translate('Closed'); ?></option>
                        				</select>
                    				</div>
                    				<div class="form-group">
                						<div class="input-group input-group-sm">
                							<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="<?php echo $this->translate('Search'); ?>" value="<?php echo $this->keyword; ?>">
                    						<div class="input-group-btn">
                    							<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    						</div>
                						</div>
                					</div>
                				</div>
                			</div>
                		</form>
            		</li>
					<?php if($this->paginator->count() == 0): ?>
					<li class="list-group-item">
						<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> 
        					<?php if($this->taskStatus):?>
        						<?php echo $this->translate("There where no {$this->taskStatus} clients found"); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php else:?>
        						<?php echo $this->translate('There where no tasks found'); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php endif; ?>
        				</div>
					</li>
					<?php else: ?>
					<?php foreach($this->paginator as $taskEntity): ?>
					<li class="list-group-item">
						<div class="row">
							<div class="col-xs-12">
								<h3 class="profile-username">
									<a href="<?php echo $this->url('task-view', array('clientId' => $this->clientId, 'taskId' => $taskEntity->getTaskId())); ?>" title="<?php echo $this->translate('View this task'); ?>">
										<?php echo $taskEntity->getTaskTitle(); ?>
									</a>
									<span class="pull-right badge"><?php echo $taskEntity->getTaskStatus(); ?></span>
								</h3>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Start')?>: </b> <?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateStart()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('End')?>: </b> <?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateEnd()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Priority')?>: </b> <?php echo $taskEntity->getTaskPriority(); ?>
							</div>
						</div>
					</li>
					<?php endforeach; ?>
					<?php endif;?>
				</ul>
			</div>
		</div>
	</div>
</div>