
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-star"></i>
					<?php echo $this->translate('Manage Client Favorites'); ?>
				</h3>
			</div>
			<div class="box-body box-profile">
				<?php if($this->favoriteEntitys->getTotalItemCount() == 0) :?>
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('You do not have any favorites'); ?></p>
				</div>
				<?php else: ?>
				<ul class="list-group list-group-unbordered">
					<?php foreach($this->favoriteEntitys as $favoriteEntity): ?>
					<li class="list-group-item">
						<a href="<?php echo $this->url('client-view', array('clientId' => $favoriteEntity->getClientId())); ?>" title="<?php echo $this->translate('View this client');?>"><?php echo $favoriteEntity->getClientEntity()->getClientName();?></a>
					
						<a href="<?php echo $this->url('client-favorite-delete', array('clientFavoriteId' => $favoriteEntity->getClientFavoriteId()));?>" title="<?php echo $this->translate('Delete this favorite'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					</li>
					<?php endforeach; ?>
				</ul>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>