<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-clock-o"></i>
					<?php echo $this->translate('Time Clock'); ?>
				</h3>
				<div class="box-tools">
 					<a href="<?php echo $this->url('employee-time-print', array(), array('query' => array('page' => $this->page, 'workorderTimeIn' =>  urlencode($this->start) . ' - ' . urlencode($this->end)))); ?>" title="<?php echo $this->translate('Print time entries'); ?>" class="btn btn-box-tool" target="_blank"><i class="fa fa-print"></i> <?php echo $this->translate('Print'); ?></a>
 				</div>
			</div>
			<div class="box-body">
				<form class="form-inline" method="get">
    				<div class="row">
            			<div class="col-xs-12 col-sm-4">
    						<div class="form-group ">
    							<div class="input-group input-group-sm">
    								<input type="text" name="workorderTimeIn" class="form-control" id="workorderTimeIn" required="required" value="<?php echo $this->start;?> - <?php echo $this->end; ?>" size="50">									
               						<div class="input-group-btn">
                    					<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    				</div>
               					</div>
               				</div>
    					</div>
    				</div>
    			</form>
			</div>
			<?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
						<div class="alert alert-info">
							<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no time entries for '); ?> <?php echo $this->start; ?> - <?php echo $this->end; ?></p>
						</div>
					</div>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Work Order'); ?></th>
							<th><?php echo $this->translate('Client'); ?></th>
							<th><?php echo $this->translate('Time In'); ?></th>
							<th><?php echo $this->translate('Time Out'); ?></th>
							<th class="text-right"><?php echo $this->translate('Time Total'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $timeEntity): ?>
						<tr>
							<td>
								
								<a href="<?php echo $this->url('workorder-view', array('clientId' => $timeEntity->getWorkorderEntity()->getClientId(), 'workorderId' => $timeEntity->getWorkorderEntity()->getWorkorderId()));?>" title="<?php echo $this->translate('View this work order'); ?>">
									<?php echo $this->translate('Work Order #'); ?><?php echo $timeEntity->getWorkorderId(); ?>
								</a>
							</td>
							<td><a href="<?php echo $this->url('client-view', array('clientId' => $timeEntity->getWorkorderEntity()->getClientId()));?>" title="<?php echo $this->translate('View this client'); ?>">
									<?php echo $timeEntity->getWorkorderEntity()->getClientEntity()->getClientName();?>
								</a>
							</td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $timeEntity->getWorkorderTimeIn()); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $timeEntity->getWorkorderTimeOut()); ?></td>
							<td class="text-right"><?php echo number_format(($timeEntity->getWorkorderTimeTotal() / 60) / 60, 2); ?> <?php echo $this->translate('hrs'); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
					<tfoot>
						<tr>
							<th class="text-right" colspan="4"><?php echo $this->translate('Total'); ?></th>
							<th class="text-right"><?php echo number_format(($this->totalTime / 60) / 60, 2); ?> <?php echo $this->translate('hrs'); ?></th>
						</tr>
					</tfoot>
				</table>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
						<?php echo $this->Paginator(
	                        $this->itemCountPerPage,
	                        $this->itemCount,
	                        $this->pageCount,
	                        $this->page,
	                        $this->routeParams,
	                        $this->queryParams); 
					    ?>
					</div>
				</div>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>
<script>
  $(function () {
	$('#workorderTimeIn').daterangepicker({timePicker: true, timePickerIncrement: 15, format: 'MM/DD/YYYY h:mm A'});
  });
</script>