<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-lock"></i>
					<?php echo $this->translate('Passwords'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'password-create') ):?>
					<a href="<?php echo $this->url('password-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new password'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
    					<form class="form-inline">
        					<div class="input-group input-group-sm" style="width: 250px;">
        						<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="Search" value="<?php echo $this->keyword; ?>">
            					<div class="input-group-btn">
            						<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            					</div>
        					</div>
        				</form>
        			</li>
        			<?php if($this->paginator->count() == 0): ?>
        			<li class="list-group-item">
        				<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There where no passwords found.'); ?>
        				</div>
        			</li>
        			<?php else: ?>
					<?php foreach($this->paginator as $passwordEntity): ?>
						<li class="list-group-item">
							<div class="row">
    							<div class="col-xs-12">
    								<h3 class="profile-username">
    									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'password-view') ):?>
    									<a href="<?php echo $this->url('password-view', array('passwordId' => $passwordEntity->getPasswordId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('View this password')?>">
    										<?php echo $passwordEntity->getPasswordLocation(); ?>
    									</a>
    									<?php else: ?>
    										<?php echo $passwordEntity->getPasswordLocation(); ?>
    									<?php endif; ?>
    								</h3>
    							</div>
							</div>
							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<b><?php echo $this->translate('Title'); ?>:</b> <?php echo $passwordEntity->getPasswordTitle(); ?>
								</div>
								<div class="col-xs-12 col-sm-6">
									<b><?php echo $this->translate('Username'); ?>:</b> <?php echo $passwordEntity->getPasswordUsername(); ?>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
					
				</ul>
				<?php if($this->pageCount > 1): ?>
				<div class="row">
					<div class="col-xs-12">
						<?php echo $this->Paginator(
	                        $this->itemCountPerPage,
	                        $this->itemCount,
	                        $this->pageCount,
	                        $this->page,
	                        $this->routeParams,
	                        $this->queryParams); ?>
					</div>
				</div>
			</div>
			<?php endif; ?>
			<?php endif; ?>
		</div>
	</div>
</div>