<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->appConfig()->getConfigCompanyNameShort())->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/timepicker/bootstrap-timepicker.min.css'))
            ->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
            ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
            ->prependStylesheet($this->basePath('font-awesome-4.6.3/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
            ->prependFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))
            ->prependFile($this->basePath('plugins/chartjs/Chart.min.js'))
            ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('/js/moment.js'))
            ->prependFile($this->basePath('dist/js/app.min.js'))
            ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
            ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('plugins/jQuery/jQuery-2.2.0.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
	<?php if($this->identity()->getEmployeeId() > 0): ?>
	<script>
		var taskReminder = function() {
				$.ajax({
			    type: "get",
			    url: "<?php echo $this->basePath('/api/task/reminder'); ?>",
			    success: function(resp) {
				    taskEntitys = resp.taskEntitys;

				    if(! $.isEmptyObject(taskEntitys)) {
    				    var str = $('#reminderBody').html();
    				    
    				    $(taskEntitys).each(function(index, element) {
    					    
    				    	str += '<a href="/client/'+element.client_id+'/task/view/'+element.task_id+'" title="<?php echo $this->translate('View this task'); ?>">'+element.task_title+'</a>';
    				    });
    				    
    				    $('#reminderBody').html(str);
    				    
    				    $("#reminderModal").modal('show');
				    }
			    }
			});
		};

		var interval = 1000 * 60 * 1;

		setInterval(taskReminder, interval);
	</script>
	<?php endif;?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
		<div class="wrapper">
		
			<header class="main-header">
				<!-- Logo -->
				<a href="<?php echo $this->url('home'); ?>" class="logo">
	                <!-- mini logo for sidebar mini 50x50 pixels -->
					<span class="logo-mini"><b><?php echo $this->appConfig()->getConfigCompanyNameAbv(); ?></b></span>
                    <!-- logo for regular state and mobile devices -->
      				<span class="logo-lg"><b><?php echo $this->appConfig()->getConfigCompanyNameShort(); ?></b></span>
    			</a>
    			
    			<!-- Header Navbar: style can be found in header.less -->
				<nav class="navbar navbar-static-top">
					<!-- Sidebar toggle button-->
					<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
						<span class="sr-only"><?php echo $this->translate('Toggle navigation'); ?></span>
					</a>
					
					
					
					<!-- Navbar Right Menu -->
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<?php if($this->identity()->getEmployeeId() > 0): ?>
							<!-- Messages: style can be found in dropdown.less-->
							<?php echo $this->NavBarMessage(); ?>
							
							<!-- Notifications: style can be found in dropdown.less -->
							<?php echo $this->NavBarNotification(); ?>
							
							<!-- Tasks: style can be found in dropdown.less -->
							<?php echo $this->NavBarTask(); ?>
							<?php endif; ?>
							
							<!-- Auth Nav Bar: style can be found in dropdown.less -->
							<?php echo $this->AuthNavBar(); ?>
							
							<!-- Control Sidebar Toggle Button -->
							<?php if($this->identity()->getEmployeeId() > 0): ?>
							<li>
								<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
							</li>
							<?php endif; ?>
						</ul>
					</div>
				</nav>
			</header>
			
			<!-- Left side column. contains the logo and sidebar -->
  			<aside class="main-sidebar">
  				<!-- sidebar: style can be found in sidebar.less -->
  				<section class="sidebar">
  					<!-- Sidebar auth panel -->
  					<?php echo $this->AuthAside(); ?>
  					
  					
  					
  					<!-- sidebar menu: : style can be found in sidebar.less -->
  					<ul class="sidebar-menu">
  					
  					<?php if($this->identity()->getEmployeeId() > 0): ?>
  						
  						<?php echo $this->EmployeeAsideMenu($this->clientId); ?>
  						
  						<?php echo $this->AccountAsideMenu();?>
  						
  						<?php echo $this->AdminAsideMenu(); ?>
  						
  					<?php else:?>
  						<?php $this->clientId = $this->identity()->getUserEntity()->getClientId();?>
  						<?php echo $this->UserAsideMenu(); ?>
  					<?php endif;?>
  					</ul>
  				</section>
  			</aside>
  			
  			<!-- Content Wrapper. Contains page content -->
  			<div class="content-wrapper">
  				<section class="content-header">
  					<h1><?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle;?></small></h1>
  					
  					<?php echo $this->navigation('navigation')->setAcl($this->acl)->setRole($this->identity()->getAuthRole())->breadcrumbs()->setMinDepth(0)->setPartial('partials/breadcrumbs'); ?>
  				</section>
  				
  				<section class="content">
  					<?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button><p>')
                         ->setMessageSeparatorString('<br />')
                         ->setMessageCloseString('</p></div>');
    
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    ?>
        			<?php echo $this->content; ?>
        		</section>
        	</div>
        	
            <footer class="main-footer">
            	<div class="pull-right hidden-xs">
            		<b><?php echo $this->translate('Version'); ?></b> <?php echo $this->appConfig()->getConfigVersion();?>
            	</div>
            	<strong><?php echo $this->translate('Copyright'); ?> &copy; <?php echo $this->appConfig()->getConfigCopyYear(); ?>-<?php echo date("Y"); ?> <a href="http://<?php echo $this->appConfig()->getConfigHttpAddress(); ?>"><?php echo $this->appConfig()->getConfigCompanyName(); ?></a>.</strong> <?php echo $this->translate('All rights reserved'); ?>.
            </footer>
            
            <!-- Control Sidebar -->
  			<aside class="control-sidebar control-sidebar-dark">
  				<!-- Create the tabs -->
				<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
					<li><a href="#control-sidebar-favorite-tab" data-toggle="tab"><i class="fa fa-star"></i></a></li>
					<li><a href="#control-sidebar-history-tab" data-toggle="tab"><i class="fa fa-history"></i></a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
					<?php echo $this->favorites();?>
					<?php echo $this->getAuthHistory(); ?>
				</div>
  			</aside>
  			 <div class="control-sidebar-bg"></div>
  			 
        </div>
        
        <div class="modal fade" id="reminderModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><i class="fa fa-list-alt"></i> <?php echo $this->translate('Task Due')?></h4>
              </div>
              <div class="modal-body" id="reminderBody">
        		
        		
        		</div>
              	<div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
              </div>
            </div>
          </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
