<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PNM'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->basePath('font-awesome-4.6.3/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('plugins/chartjs/Chart.min.js'))
            ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('dist/js/app.min.js'))
            ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
            ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('plugins/jQuery/jQuery-2.2.0.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="hold-transition skin-blue sidebar-mini">
		<div class="wrapper">
		
			<header class="main-header">
				<!-- Logo -->
				<a href="<?php echo $this->url('home'); ?>" class="logo">
	                <!-- mini logo for sidebar mini 50x50 pixels -->
					<span class="logo-mini"><b>P</b>NM</span>
                    <!-- logo for regular state and mobile devices -->
      				<span class="logo-lg"><b>Pacific</b> NM</span>
    			</a>
    			
    			<!-- Header Navbar: style can be found in header.less -->
				<nav class="navbar navbar-static-top">
					<!-- Sidebar toggle button-->
					<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
						<span class="sr-only"><?php echo $this->translate('Toggle navigation'); ?></span>
					</a>
					
					
					
					<!-- Navbar Right Menu -->
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<!-- Messages: style can be found in dropdown.less-->
							<?php echo $this->NavBarMessage(); ?>
							
							<!-- Notifications: style can be found in dropdown.less -->
							<?php echo $this->NavBarNotification(); ?>
							
							<!-- Tasks: style can be found in dropdown.less -->
							<?php echo $this->NavBarTask(); ?>
							
							
							<!-- Auth Nav Bar: style can be found in dropdown.less -->
							<?php echo $this->AuthNavBar(); ?>
							
							<!-- Control Sidebar Toggle Button -->
							<li>
								<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
							</li>
						</ul>
					</div>
				</nav>
			</header>
			
			<!-- Left side column. contains the logo and sidebar -->
  			<aside class="main-sidebar">
  				<!-- sidebar: style can be found in sidebar.less -->
  				<section class="sidebar">
  					<!-- Sidebar auth panel -->
  					<?php echo $this->AuthAside(); ?>
  					
  					<!-- search form -->
  					<form action="#" method="get" class="sidebar-form">
  						<div class="input-group">
  							<input type="text" name="q" class="form-control" placeholder="<?php echo $this->translate('Search'); ?>...">
  							<span class="input-group-btn">
  								<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
  							</span>
  						</div>
  					</form>
  					
  					<!-- sidebar menu: : style can be found in sidebar.less -->
  					<?php if($this->identity()->getEmployeeId() > 0): ?>
  						<?php echo $this->EmployeeAsideMenu($this->clientId); ?>
  					<?php else:?>
  					
  					<?php endif;?>
  				</section>
  			</aside>
  			
  			<!-- Content Wrapper. Contains page content -->
  			<div class="content-wrapper">
  				<section class="content-header">
  					<h1><?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle;?></small></h1>
  					
  					<?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partials/breadcrumbs'); ?>
  				</section>
  				
  				<section class="content">
        			<?php echo $this->content; ?>
        		</section>
        	</div>
        	
            <footer class="main-footer">
            	<div class="pull-right hidden-xs">
            		<b><?php echo $this->translate('Version'); ?></b> 2.5.0
            	</div>
            	<strong><?php echo $this->translate('Copyright'); ?> &copy; 2003-<?php echo date("Y"); ?> <a href="http://www.pacificnm.com">Pacific Network Management</a>.</strong> <?php echo $this->translate('All rights reserved'); ?>.
            </footer>
            
            <!-- Control Sidebar -->
  			<aside class="control-sidebar control-sidebar-dark">
  			
  			</aside>
  			 <div class="control-sidebar-bg"></div>
  			 
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
