<a id="hostAlerts"></a>
<div class="box box-primary">
	<div class="box-header with-border">
	<h3 class="box-title"><i class="fa fa-bell"></i> <?php echo $this->translate('Host Issues'); ?></h3>
	<div class="box-tools pull-right"></div>
	</div>
		<div class="box-body">
		<?php if(count($this->issueEntitys) == 0):?>
		<div class="alert alert-info">
			<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no host issues'); ?></p>
		</div>
		<?php else: ?>
		<div class="box-body table-responsive no-padding">
		<table class="table table-bordered table-hover table-striped table-condensed">
			<thead>
				<tr>
					<th><?php echo $this->translate('Description'); ?></th>
					<th><?php echo $this->translate('Category'); ?></th>
					<th><?php echo $this->translate('Severity'); ?></th>
					<th><?php echo $this->translate('Date'); ?></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->issueEntitys as $issueEntity): ?>
				<tr>
					<td><a href="" title=""><?php echo $issueEntity->getMessage();?></a></td>
					<td><?php echo $issueEntity->getCategory(); ?></td>
					<td><?php echo $issueEntity->getVulnerability();?></td>
					<td><?php echo date($this->appConfig()->getConfigDateLong(), strtotime($issueEntity->getFirstSeen()));?></td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		<?php endif;?>
	</div>
</div>