<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-group"></i>
					<?php echo $this->mspEntity->getName(); ?>
				</h3>
				<div class="box-tools">
					<?php if($this->panoramaClientEntity):?>
					<a href="<?php echo $this->url('client-view', array('clientId' => $this->panoramaClientEntity->getClientId())); ?>" 
						title="<?php echo $this->translate('View this client'); ?>" class="btn btn-box-tool">
							<i class="fa fa-search"></i> <?php echo $this->translate('View Client')?>
						</a>
					<?php endif;?>
				</div>
			</div>
			<div class="box-body ">
				<ul class="nav nav-tabs">
					<li role="presentation"><a href="<?php echo $this->url('panorama-view', array('cid' => $this->mspEntity->getCid())); ?>"><?php echo $this->translate('Devices')?></a></li>
					<li role="presentation"><a href="<?php echo $this->url('panorama-user', array('cid' => $this->mspEntity->getCid())); ?>" title="<?php echo $this->translate('Users')?>"><?php echo $this->translate('Users'); ?></a></li>
					<li role="presentation" class="active"><a href="<?php echo $this->url('panorama-issue', array('cid' => $this->mspEntity->getCid()));?>" title="<?php echo $this->translate('Issues')?>"><?php echo $this->translate('Issues'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Software'); ?></a></li>
					<li role="presentation"><a href="#"><?php echo $this->translate('Groups'); ?></a></li>
				</ul>
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Description'); ?></th>
							<th><?php echo $this->translate('Category'); ?></th>
							<th><?php echo $this->translate('Severity'); ?></th>
							<th><?php echo $this->translate('Date'); ?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->issueEntitys as $issueEntity): ?>
						<tr>
        					<td><a href="" title=""><?php echo $issueEntity->getMessage();?></a></td>
        					<td><?php echo $issueEntity->getCategory(); ?></td>
        					<td><?php echo $issueEntity->getVulnerability();?></td>
        					<td><?php echo date($this->appConfig()->getConfigDateLong(), strtotime($issueEntity->getFirstSeen()));?></td>
        				</tr>
        				<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php \Zend\Debug\Debug::dump($this->issueEntitys);?>