<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InvoicePayment\Service\PaymentService'                     => __DIR__ . '/src/InvoicePayment/Service/PaymentService.php',
    'InvoicePayment\Service\Factory\PaymentServiceFactory'      => __DIR__ . '/src/InvoicePayment/Service/Factory/PaymentServiceFactory.php',
    'InvoicePayment\Service\PaymentServiceInterface'            => __DIR__ . '/src/InvoicePayment/Service/PaymentServiceInterface.php',
    'InvoicePayment\Controller\DeleteController'                => __DIR__ . '/src/InvoicePayment/Controller/DeleteController.php',
    'InvoicePayment\Controller\CreateController'                => __DIR__ . '/src/InvoicePayment/Controller/CreateController.php',
    'InvoicePayment\Controller\Factory\CreateControllerFactory' => __DIR__ . '/src/InvoicePayment/Controller/Factory/CreateControllerFactory.php',
    'InvoicePayment\Controller\Factory\DeleteControllerFactory' => __DIR__ . '/src/InvoicePayment/Controller/Factory/DeleteControllerFactory.php',
    'InvoicePayment\Form\PaymentForm'                           => __DIR__ . '/src/InvoicePayment/Form/PaymentForm.php',
    'InvoicePayment\Form\Factory\PaymentFormFactory'            => __DIR__ . '/src/InvoicePayment/Form/Factory/PaymentFormFactory.php',
    'InvoicePayment\Mapper\PaymentMapperInterface'              => __DIR__ . '/src/InvoicePayment/Mapper/PaymentMapperInterface.php',
    'InvoicePayment\Mapper\Factory\PaymentMapperFactory'        => __DIR__ . '/src/InvoicePayment/Mapper/Factory/PaymentMapperFactory.php',
    'InvoicePayment\Mapper\PaymentMapper'                       => __DIR__ . '/src/InvoicePayment/Mapper/PaymentMapper.php',
    'InvoicePayment\Hydrator\PaymentHydrator'                   => __DIR__ . '/src/InvoicePayment/Hydrator/PaymentHydrator.php',
    'InvoicePayment\Entity\PaymentEntity'                       => __DIR__ . '/src/InvoicePayment/Entity/PaymentEntity.php',
    'InvoicePayment\Module'                                     => __DIR__ . '/Module.php',
);
