<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-life-ring" aria-hidden="true"></i>
					<?php echo $this->translate('Support Tickets'); ?>
				</h3>
			</div>
			<div class="box-body">
				<ul class="list-group list-group-unbordered">
    				<li class="list-group-item">
    					<form class="form-inline">
                			<div class="row">
                				<div class="col-xs-12">
                				
                					<div class="form-group">
                        				<select class="form-control input-sm" name="ticketStatus" id="ticketStatus">
                        					<option value=""><?php echo $this->translate('Status'); ?></option>
                        					<option value="Active" <?php if($this->ticketStatus == 'New'):?> selected <?php endif?>><?php echo $this->translate('New'); ?></option>
                        					<option value="Active" <?php if($this->ticketStatus == 'Active'):?> selected <?php endif?>><?php echo $this->translate('Active'); ?></option>
                        					<option value="Closed" <?php if($this->ticketStatus == 'Closed'):?> selected <?php endif?>><?php echo $this->translate('Closed'); ?></option>
                        				</select>
                    				</div>
                    				
                    				<div class="form-group">
                						<div class="input-group input-group-sm">
                							<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="<?php echo $this->translate('Search'); ?>" value="<?php echo $this->keyword; ?>">
                    						<div class="input-group-btn">
                    							<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    						</div>
                						</div>
                					</div>
                				
                				</div>
                			</div>
                		</form>
    				</li>
    				<?php if($this->paginator->count() == 0): ?>
					<li class="list-group-item">
        				<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> 
        					<?php if($this->clientStatus):?>
        						<?php echo $this->translate("There where no {$this->ticketStatus} tickets found"); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php else:?>
        						<?php echo $this->translate('There where no tickets found'); ?>
        						<?php if($this->keyword): ?>
        							<?php echo $this->translate("searching with {$this->keyword}"); ?>
        						<?php endif;?>
        					<?php endif; ?>
        				</div>
					</li>
					<?php else: ?>
					<?php foreach($this->paginator as $ticketEntity): ?>
					<li class="list-group-item">
                    	<div class="row">
                        	<div class="col-xs-12">
                        		<h3 class="profile-username">
                        			<a href="<?php echo $this->url('ticket-view', array('clientId' => $this->clientId, 'ticketId' => $ticketEntity->getTicketId())); ?>" title="<?php echo $this->translate('View this ticket'); ?>">
                        				<?php echo $ticketEntity->getTicketTitle();?>
                        			</a>
                        			
                        			<span class="pull-right badge"><?php echo $ticketEntity->getTicketStatus(); ?></span>
                        		</h3>
                        	</div>
                        </div>
                        <div class="row">
                    		<div class="col-xs-12 col-sm-9">
                    			<b><?php echo $this->translate('Created By'); ?>:</b>
                    			<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
                    			<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $ticketEntity->getUserId())); ?>" title="<?php echo $this->translate('View this user');?>">
                    				<?php echo $ticketEntity->getUserEntity()->getUserNameFirst(); ?> <?php echo $ticketEntity->getUserEntity()->getUserNameLast(); ?>
                    			</a>
                    			<?php else: ?>
                    				<?php echo $ticketEntity->getUserEntity()->getUserNameFirst(); ?> <?php echo $ticketEntity->getUserEntity()->getUserNameLast(); ?>
                    			<?php endif; ?>
                    		</div>
                    		<div class="col-xs-12 col-sm-3 text-right">
                    			<b><?php echo $this->translate('Created'); ?>:</b>
                    			<?php echo date($this->appConfig()->getConfigdateLong(), $ticketEntity->getTicketDateOpen()); ?>
                    		</div>
                    	</div>
                    </li>
					<?php endforeach; ?>
					<?php endif;?>
    			</ul>
    			<?php if($this->pageCount > 1): ?>
				<div class="row">
					<div class="col-xs-12">
    				<?php echo $this->Paginator(
    	                        $this->itemCountPerPage,
    	                        $this->itemCount,
    	                        $this->pageCount,
    	                        $this->page,
    	                        $this->routeParams,
    	                        $this->queryParams); ?>
    	        	</div>
    			</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>