<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa phone"></i>
					<?php echo $this->translate('Delete Call Log Note'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following call log note?'); ?></p>
				</div>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<div class="row">
    						<div class="col-xs-12">
    							<p><?php echo $this->noteEntity->getCallLogNoteText();?></p>
    						</div>
    					</div>
    					<div class="row">
    						<div class="col-xs-12">
    							<span class="text-muted small"><?php echo date($this->appConfig()->getConfigDateLong(), $this->noteEntity->getCallLogCreated()); ?></span>
    							<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'employee-view') ):?>
    							<a href="<?php echo $this->url('employee-view', array('employeeId' => $this->noteEntity->getEmployeeEntity()->getEmployeeId()));?>" title="<?php echo $this->translate('View this employee'); ?>"><?php echo $this->noteEntity->getEmployeeEntity()->getEmployeeName();?></a>
    							<?php endif;?>
    						</div>
    					</div>
					</li>
				</ul>
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                 </form>
			</div>
		</div>
	</div>
</div>