<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<?php 
    $totalDeductions = $this->entity->getPayrollTaxFederalIncome() + 
    $this->entity->getPayrollTaxSocialSecurity() +
    $this->entity->getPayrollTaxState() +
    $this->entity->getPayrollTaxMedicare;
    
    $totalPay = $this->entity->getPayrollWages() +
    $this->entity->getPayrollWagesOt() +
    $this->entity->getPayrollWagesVacation() +
    $this->entity->getPayrollWagesSick();
    
    $totalNetPay = $totalPay - $totalDeductions;
    
    $ytdTotalDeductions = $this->ytdFederalIncomeTax + 
    $this->ytdSocialSecurityTax + 
    $this->ytdMedicareTax + 
    $this->ytdStateTax;
?>
<style>
@media print {
    footer {page-break-after: always;}
}
</style>
<section class="invoice small">
	<div class="row">
		<div class="col-xs-8">
			<?php echo $this->appConfig()->getConfigCompanyName();?>
			<p><?php echo $this->appConfig()->getConfigCompanyStreet(); ?><br />
				<?php echo $this->appConfig()->getConfigCompanyCity(); ?>, <?php echo $this->appConfig()->getConfigCompanyState(); ?> <?php echo $this->appConfig()->getConfigCompanyPostal(); ?>
			</p>
		</div>
		<div class="col-xs-4 text-right">
			<h3><?php echo $this->translate('Earnings Statement'); ?></h3>
		</div>
	</div>
					
	<hr />
					
	<div class="row">
		<div class="col-xs-4">
			<p><b><?php echo $this->translate('Employee Name'); ?></b></p>
		</div>
		<div class="col-xs-2 text-center">
			<p><b><?php echo $this->translate('Social Security Id'); ?></b>
		</div>
		<div class="col-xs-2 text-center">
			<p><b><?php echo $this->translate('Employee Id'); ?></b></p>
		</div>
		<div class="col-xs-1 text-center">
			<p><b><?php echo $this->translate('Check'); ?></b></p>
		</div>
		<div class="col-xs-2 text-center">
			<p><b><?php echo $this->translate('Pay Period'); ?></b></p>
		</div>
		<div class="col-xs-1 text-center">
			<p><b><?php echo $this->translate('Pay Date'); ?></b></p>
		</div>
	</div>
					
	<div class="row">
		<div class="col-xs-4"><?php echo $this->entity->getEmployeeEntity()->getEmployeeName(); ?></div>
		<div class="col-xs-2 text-center"><?php echo $this->entity->getEmployeeEntity()->getEmployeeSsn(); ?></div>
		<div class="col-xs-2 text-center"><?php echo $this->entity->getEmployeeId(); ?></div>
		<div class="col-xs-1 text-center"><?php echo $this->entity->getPayrollCheck(); ?></div>
		<div class="col-xs-2 text-center">
			<?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateStart());?> -
			<?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateEnd());?>
		</div>
		<div class="col-xs-1 text-center"><?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getPayrollDateCreate());?></div>
	</div>
					
	<hr />
					
					<div class="row">
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-3">
									<p><b><?php echo $this->translate('Income'); ?></b></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><b><?php echo $this->translate('Rate'); ?></b></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><b><?php echo $this->translate('Hours'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Regular Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHours(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWages(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Over Time Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRateOt(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursOt(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesOt(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Vacation Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursVacation(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesVacation(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<p><?php echo $this->translate("Sick Pay") ;?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollRate(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-center">
									<p><?php echo $this->entity->getPayrollHoursSick(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesSick(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
						</div>
						
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-6">
									<p><b><?php echo $this->translate('Deductions'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><b><?php echo $this->translate('Year To Date'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Federal Income Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxFederalIncome(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdFederalIncomeTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Social Security Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxSocialSecurity(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdSocialSecurityTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('Medicare Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxMedicare(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdMedicareTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $this->translate('State Tax'); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollTaxState(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($this->ytdStateTax, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
							
							<?php if(count($this->payrollDeductionEntitys) > 0): ?>
							<?php foreach($this->payrollDeductionEntitys as $payrollDeductionEntity): ?>
							<div class="row">
								<div class="col-xs-6">
									<p><?php echo $payrollDeductionEntity->getPayrollDeductionTypeEntity()->getPayrollDeductionTypeName(); ?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($payrollDeductionEntity->getPayrollDeductionAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-3 text-right">
									<p><?php echo $this->currencyFormat($payrollDeductionEntity->getPayrollDeductionYtd(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
							<?php $totalDeductions = $totalDeductions + $payrollDeductionEntity->getPayrollDeductionAmount(); ?>
							<?php endforeach;?>
							<?php endif?>
						</div>
					</div>
					
					<hr />
					
					<div class="row">
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('YTD Gross'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('YTD Deductions'); ?></b></p>
								</div>
								<div class="col-xs-4">
									<p><b><?php echo $this->translate('YTD Net Pay'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($this->ytdGross, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($ytdTotalDeductions, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
								<div class="col-xs-4">
									<p><?php echo $this->currencyFormat($this->ytdNet, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></p>
								</div>
							</div>
						</div>
						
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Total'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Deductions'); ?></b></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><b><?php echo $this->translate('Current Net Pay'); ?></b></p>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($totalPay, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($totalDeductions, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
								<div class="col-xs-4 text-center">
									<p><?php echo $this->currencyFormat($this->entity->getPayrollWagesNet(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></p>
								</div>
							</div>
						</div>
					</div>
</section>	
			
		