<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AccountLedger\Service\LedgerServiceInterface'           => __DIR__ . '/src/AccountLedger/Service/LedgerServiceInterface.php',
    'AccountLedger\Service\Factory\LedgerServiceFactory'     => __DIR__ . '/src/AccountLedger/Service/Factory/LedgerServiceFactory.php',
    'AccountLedger\Service\LedgerService'                    => __DIR__ . '/src/AccountLedger/Service/LedgerService.php',
    'AccountLedger\Controller\ViewController'                => __DIR__ . '/src/AccountLedger/Controller/ViewController.php',
    'AccountLedger\Controller\Factory\ViewControllerFactory' => __DIR__ . '/src/AccountLedger/Controller/Factory/ViewControllerFactory.php',
    'AccountLedger\Mapper\LedgerMapperInterface'             => __DIR__ . '/src/AccountLedger/Mapper/LedgerMapperInterface.php',
    'AccountLedger\Mapper\LedgerMapper'                      => __DIR__ . '/src/AccountLedger/Mapper/LedgerMapper.php',
    'AccountLedger\Mapper\Factory\LedgerMapperFactory'       => __DIR__ . '/src/AccountLedger/Mapper/Factory/LedgerMapperFactory.php',
    'AccountLedger\Hydrator\LedgerHydrator'                  => __DIR__ . '/src/AccountLedger/Hydrator/LedgerHydrator.php',
    'AccountLedger\Entity\LedgerEntity'                      => __DIR__ . '/src/AccountLedger/Entity/LedgerEntity.php',
    'AccountLedger\Module'                                   => __DIR__ . '/Module.php',
);
