<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following product from the subscription?'); ?></p>
				</div>
				<table class="table table-bordered table-hover table-striped table-condensed">
               		<thead>
               			<tr>
               				<th><?php echo $this->translate('Quantity'); ?></th>
               				<th><?php echo $this->translate('Product'); ?></th>
               				<th><?php echo $this->translate('Amount'); ?></th>
               				<th><?php echo $this->translate('Total'); ?></th>
               			</tr>
               		</thead>
               		<tbody>
               			<tr>
            				<td><?php echo $this->entity->getSubscriptionProductQty(); ?></td>
            				<td><?php echo $this->entity->getProductEntity()->getProductName(); ?></td>
            				<td>
            					<?php if($this->subscriptionEntity->getSubscriptionScheduleId() == 1): ?>
            					<?php echo $this->currencyFormat($this->entity->getProductEntity()->getProductFeeMonthly(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
            					<?php else: ?>
            					<?php echo $this->currencyFormat($this->entity->getProductEntity()->getProductFeeAnual(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?>
            					<?php endif;?>
            				</td>
            				<td><?php echo $this->currencyFormat(0, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
            			</tr>
               		</tbody>
               	</table>
               	
               	<br />
               	
               	<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>
				