<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Work Orders'); ?>
				</h3>
				
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-create') ):?>
					<a href="<?php echo $this->url('workorder-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new work order');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			
			<div class="box-body">
				<?php if($this->workorderCallLogEntitys->count() == 0): ?>
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No work orders'); ?>
				</div>
				<?php else: ?>
				<ul class="list-group list-group-unbordered">
				<?php foreach($this->workorderCallLogEntitys as $entity): ?>
					<?php $workorderEntity = $entity->getWorkorderEntity();?>
					<li class="list-group-item">
						<div class="row">
							<div class="col-xs-12">
								<h3 class="profile-username">
									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-view') ):?>
									<a href="<?php echo $this->url('workorder-view', array('clientId' => $workorderEntity->getClientId(), 'workorderId' => $workorderEntity->getWorkorderId())); ?>" title="<?php echo $this->translate('View this work order'); ?>"><?php echo $this->translate('Work Order #')?><?php echo $workorderEntity->getWorkorderId(); ?></a>
									<?php else: ?>
									<?php echo $this->translate('Work Order #')?><?php echo $workorderEntity->getWorkorderId(); ?>
									<?php endif; ?>
									<span class="pull-right badge <?php ($workorderEntity->getWorkorderStatus() == 'Active') ? 'text-success' : 'text-danger'; ?>"><?php echo $workorderEntity->getWorkorderStatus(); ?></span>	
								</h3>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<b><?php echo $this->translate('Title'); ?>: </b> <?php echo $workorderEntity->getWorkorderTitle();?>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Scheduled'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateScheduled()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Ends'); ?>:</b> <?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateEnd()); ?>
							</div>
							<div class="col-xs-12 col-sm-4">
								<b><?php echo $this->translate('Contact'); ?>:</b> 
									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
									<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $workorderEntity->getUserEntity()->getUserId()));?>" title="<?php echo $this->translate('View this user'); ?>">
										<?php echo $workorderEntity->getUserEntity()->getUserNameFirst();?> <?php echo $workorderEntity->getUserEntity()->getUserNameLast();?>
									</a>
									<?php else: ?>
										<?php echo $workorderEntity->getUserEntity()->getUserNameFirst();?> <?php echo $workorderEntity->getUserEntity()->getUserNameLast();?>
									<?php endif; ?>
							
									<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-call-log-delete') ):?>
									<a href="<?php echo $this->url('workorder-call-log-delete', array('clientId' => $workorderEntity->getClientId(), 'workorderCallLogId' => $entity->getWorkorderCallLogId())); ?>" title="<?php echo $this->translate('Remove work order'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-times"></i> <?php echo $this->translate('Delete')?></a>
									<?php endif; ?>
							</div>
						</div>
					</li>
				<?php endforeach;?>
				</ul>
				<?php endif;?>
			</div>
		</div>
	</div>
</div>