<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Edit Work Order Note'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">

				<?php echo $this->form()->openTag($this->noteForm); ?>
				
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->noteForm->getMessages())); ?>
       	
               	<div class="row">
                	<div class="col-xs-12">
        				<?php $element = $this->noteForm->get('workorderNotesNote'); ?>
        				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        					<label class="control-label"><?php echo $element->getLabel() ?></label>
        					<?php echo $this->formElement($element); ?>
        					<?php if($this->formElementErrors($element)): ?>
        						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        					<?php endif; ?>
        				</div>
                   </div>
               </div>
               
               <div class="row">
                	<div class="col-xs-12 col-sm-4">
        				<?php $element = $this->noteForm->get('workorderNotesDate'); ?>
        				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        					<label class="control-label"><?php echo $element->getLabel() ?></label>
        					<?php echo $this->formElement($element); ?>
        					<?php if($this->formElementErrors($element)): ?>
        						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        					<?php endif; ?>
        				</div>
                   </div>
               </div>
               	
               	<div class="row">
                	<div class="col-xs-12 col-sm-4">
        				<?php $element = $this->noteForm->get('employeeId'); ?>
        				<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
        					<label class="control-label"><?php echo $element->getLabel() ?></label>
        					<?php echo $this->formElement($element); ?>
        					<?php if($this->formElementErrors($element)): ?>
        						<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
        					<?php endif; ?>
        				</div>
                   </div>
               </div>
               	
               	<?php echo $this->formElement($this->noteForm->get('workorderId')); ?>
               	<?php echo $this->formElement($this->noteForm->get('workorderNotesId')); ?>
               	
               	<?php echo $this->formSubmit($this->noteForm->get('submit')); ?>
               	<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $('#workorderNotesDate').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
	  $("#workorderNotesNote").wysihtml5();
  });
 </script>