<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">	
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('Bill'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->paymentForm->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->form->get('vendorBillDateDue'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><i class="fa fa-asterisk text-muted"></i> <?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->form->get('vendorBillAmount'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><i class="fa fa-asterisk text-muted"></i> <?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('vendorBillMemo'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><i class="fa fa-asterisk text-muted"></i> <?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
              			<p class="text-muted"><i class="fa fa-info-circle"></i> <?php echo $this->translate('If this is a future bill leave payment information blank.')?></p>
              		</div>
              	</div>
              	<div class="row">
              		<div class="col-xs-12 col-sm-6">
						<?php $element = $this->paymentForm->get('accountId'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->paymentForm->get('vendorPaymentAmount'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-4">
						<?php $element = $this->paymentForm->get('vendorPaymentDate'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
				<?php echo $this->formElement($this->form->get('vendorBillId')); ?>
				<?php echo $this->formElement($this->form->get('vendorId')); ?>
				<?php echo $this->formElement($this->form->get('vendorBillDateCreate')); ?>
				<?php echo $this->formElement($this->form->get('vendorBillDatePaid')); ?>
				<?php echo $this->formElement($this->form->get('vendorBillBalance')); ?>
				<?php echo $this->formElement($this->form->get('vendorBillStatus')); ?>
				
				<?php echo $this->formElement($this->paymentForm->get('vendorPaymentId')); ?>
				<?php echo $this->formElement($this->paymentForm->get('accountLedgerId')); ?>
				<?php echo $this->formElement($this->paymentForm->get('vendorPaymentActive')); ?>
				
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
				
			</div>
		</div>
	</div>
</div>

<script>
  $(function () {
	  $('#vendorBillDateDue').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
	  $('#vendorPaymentDate').daterangepicker({singleDatePicker: true, format: 'MM/DD/YYYY'});
  });
 </script>