<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-user"></i>
					<?php echo $this->translate('View Employee'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('employee-delete', array('employeeId' => $this->employeeEntity->getEmployeeId())); ?>" title="<?php echo $this->translate('Delete this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('employee-update', array('employeeId' => $this->employeeEntity->getEmployeeId())); ?>" title="<?php echo $this->translate('Edit this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username"><?php echo $this->employeeEntity->getEmployeeName(); ?></h3>
				<p class="text-muted"><?php echo $this->employeeEntity->getEmployeeTitle(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('E-Mail'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getEmployeeEmail(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Phone'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getEmployeePhone();?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Adddress'); ?></b> <a class="pull-right">
    							<?php echo $this->employeeEntity->getEmployeeStreet();?>
    							<?php echo $this->employeeEntity->getEmployeeCity();?>,
    							<?php echo $this->employeeEntity->getEmployeeState();?>
    							<?php echo $this->employeeEntity->getEmployeePostal();?>
    						</a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Status'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getEmployeeStatus(); ?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('View Auth'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('auth-delete', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Delete this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('auth-update', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Edit this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<a href="<?php echo $this->url('auth-password', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Reset Password'); ?>" class="btn btn-box-tool"><i class="fa fa-lock"></i> <?php echo $this->translate('Password'); ?></a>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username">
					<a href="<?php echo $this->url('auth-view', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php Echo $this->translate('View this auth'); ?>"><?php echo $this->employeeEntity->getAuthEntity()->getAuthName(); ?></a>
				</h3>
				<p class="text-muted"><?php echo $this->employeeEntity->getAuthEntity()->getAuthEmail(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
				 		<b><?php echo $this->translate('Role');?></b> <a class="pull-right"><?php echo $this->employeeEntity->getAuthEntity()->getAuthRole(); ?></a>
				 	</li>
				 	<li class="list-group-item">
				 		<b><?php echo $this->translate('Type'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getAuthEntity()->getAuthType(); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Last Sign In'); ?></b> 
 				 			<a class="pull-right"><?php echo ($this->employeeEntity->getAuthEntity()->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $this->employeeEntity->getAuthEntity()->getAuthLastLogin()) : $this->translate('Never Signed In'); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Ip Address');?></b> <a class="pull-right"><?php echo ($this->employeeEntity->getAuthEntity()->getAuthLastIp() != null) ? $this->employeeEntity->getAuthEntity()->getAuthLastIp() : $this->translate('Never Signed In'); ?></a>
 				 	</li>
				</ul>
			</div>
		</div>	
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-4 ">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-tasks"></i>
					<?php echo $this->translate('Tasks'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<?php if($this->taskEntitys->getTotalItemCount() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('You do not have any active tasks'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Task Title'); ?></th>
							<th><?php echo $this->translate('Start'); ?></th>
							<th><?php echo $this->translate('End'); ?></th>
							<th><?php echo $this->translate('Priority'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->taskEntitys as $taskEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('task-view', array('clientId' => $this->clientId, 'taskId' => $taskEntity->getTaskId())); ?>" title="<?php echo $this->translate('View this task'); ?>">
									<?php echo $taskEntity->getTaskTitle(); ?>
								</a>
							</td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateStart()); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateEnd()); ?></td>
							<td><?php echo $taskEntity->getPriorityEntity()->getTaskPriorityValue(); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif;?>
		</div>
	
	</div>
	<div class="col-xs-12 col-sm-8">
	
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Work Orders'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<?php if($this->workorderEntitys->getTotalItemCount() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('You do not have any active work orders.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Work Order #'); ?></th>
							<th><?php echo $this->translate('Description'); ?></th>
							<th><?php echo $this->translate('Scheduled'); ?></th>	
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->workorderEntitys as $workorderEntity): ?>
						<tr>
							<td><a href="<?php echo $this->url('workorder-view', array('clientId' => $workorderEntity->getWorkorderEntity()->getClientId(), 'workorderId' => $workorderEntity->getWorkorderId()));?>" title="<?php echo $this->translate('View this work order'); ?>"><?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getWorkorderId(); ?></a></td>
							<td><?php echo $workorderEntity->getWorkorderEntity()->getWorkorderDescription(); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderEntity()->getWorkorderDateScheduled()); ?></td>
						</tr>
					<?php endforeach;?>	
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
	</div>
	
</div>



