<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-user"></i>
					<?php echo $this->translate('View Employee'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('employee-delete', array('employeeId' => $this->employeeEntity->getEmployeeId())); ?>" title="<?php echo $this->translate('Delete this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('employee-update', array('employeeId' => $this->employeeEntity->getEmployeeId())); ?>" title="<?php echo $this->translate('Edit this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username"><?php echo $this->employeeEntity->getEmployeeName(); ?></h3>
				<p class="text-muted"><?php echo $this->employeeEntity->getEmployeeTitle(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('E-Mail'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getEmployeeEmail(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Phone'); ?></b>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Birth Day'); ?></b>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Status'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getEmployeeStatus(); ?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('View Auth'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('auth-delete', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Delete this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('auth-update', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Edit this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<a href="<?php echo $this->url('auth-password', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php echo $this->translate('Reset Password'); ?>" class="btn btn-box-tool"><i class="fa fa-lock"></i> <?php echo $this->translate('Password'); ?></a>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username">
					<a href="<?php echo $this->url('auth-view', array('authId' => $this->employeeEntity->getAuthEntity()->getAuthId())); ?>" title="<?php Echo $this->translate('View this auth'); ?>"><?php echo $this->employeeEntity->getAuthEntity()->getAuthName(); ?></a>
				</h3>
				<p class="text-muted"><?php echo $this->employeeEntity->getAuthEntity()->getAuthEmail(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
				 		<b><?php echo $this->translate('Role');?></b> <a class="pull-right"><?php echo $this->employeeEntity->getAuthEntity()->getAuthRole(); ?></a>
				 	</li>
				 	<li class="list-group-item">
				 		<b><?php echo $this->translate('Type'); ?></b> <a class="pull-right"><?php echo $this->employeeEntity->getAuthEntity()->getAuthType(); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Last Sign In'); ?></b> 
 				 			<a class="pull-right"><?php echo ($this->employeeEntity->getAuthEntity()->getAuthLastLogin() > 0) ? date($this->appConfig()->getConfigDateLong(), $this->employeeEntity->getAuthEntity()->getAuthLastLogin()) : $this->translate('Never Signed In'); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Ip Address');?></b> <a class="pull-right"><?php echo ($this->employeeEntity->getAuthEntity()->getAuthLastIp() != null) ? $this->employeeEntity->getAuthEntity()->getAuthLastIp() : $this->translate('Never Signed In'); ?></a>
 				 	</li>
				</ul>
			</div>
		</div>	
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-wrench"></i>
					<?php echo $this->translate('Work Orders'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-tasks"></i>
					<?php echo $this->translate('Tasks'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
		</div>
	</div>
</div>

