<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-user"></i>
					<?php echo $this->translate('View User'); ?>
				</h3>
				<div class="box-tools">
					<?php if(! $this->authEntity): ?>
    					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'auth-create') ):?>
    						<a href="<?php echo $this->url('auth-create', array(), array('query' => array('userId' => $this->userEntity->getUserId()))); ?>" title="<?php echo $this->translate('Grant this user access to the portal');?>" class="btn btn-box-tool"><i class="fa fa-lock"></i> <?php echo $this->translate('Grant Access'); ?></a>
    					<?php endif; ?>
					
					<?php else: ?>
    					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'auth-password') ):?>
    						<a href="<?php echo $this->url('auth-password', array('authId' => $this->authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Reset user password')?>" class="btn btn-box-tool"><i class="fa fa-lock"></i> <?php echo $this->translate('Reset Password'); ?></a>
    					<?php endif;?>
						<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'auth-delete') ):?>
							<a href="<?php echo $this->url('auth-delete', array('authId' => $this->authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Revoke users access to the portal')?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Revoke Access'); ?></a>
						<?php endif;?>
					<?php endif; ?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'user-update') ):?>
					<a href="<?php echo $this->url('user-update', array('clientId' => $this->clientId, 'userId' => $this->userEntity->getUserId()));?>" title="<?php echo $this->translate('Edit this user'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Name');?>:</b> <?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Type');?>:</b> <?php echo $this->userEntity->getUserType(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('E-Mail'); ?>:</b> <?php echo $this->userEntity->getUserEmail();?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Status');?>:</b> <?php echo $this->userEntity->getUserStatus();?></p>
					</div>
				</div>
				<div class="row">
					<?php if(! $this->authEntity): ?>
					<div class="col-xs-12">
						<div class="alert alert-info">
							<p><i class="fa fa-circle-info"></i> <?php echo $this->translate('This user is not allowed to access the portal');?></p>
						</div>
					</div>
					<?php else: ?>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Portal Type'); ?>:</b> <?php echo $this->authEntity->getAuthType(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Role'); ?>: </b> <?php echo $this->authEntity->getAuthRole(); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Last Sign IN'); ?>: </b> <?php echo ($this->authEntity->getAuthLastLogin() ? date($this->appConfig()->getConfigDateLong(), $this->authEntity->getAuthLastLogin()) : $this->translate('Never Signed In')); ?></p>
					</div>
					<div class="col-xs-12 col-sm-3">
						<p><b><?php echo $this->translate('Ip'); ?>: </b> <?php echo $this->authEntity->getAuthLastIp(); ?></p>
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-lock"></i> <?php echo $this->translate('Passwords'); ?>
				</h3>
				<div class="box-tools">
					<a href="" title="" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This user has no passwords'); ?></p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i> <?php echo $this->translate('Hosts'); ?>
				</h3>
				<div class="box-tools">
					<a href="" title="" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('This user is not assigned to any hosts'); ?></p>
				</div>
			</div>
		</div>
	</div>
</div>