<div class="row">
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-aqua"><i class="fa fa-wrench fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text"><?php echo $this->translate('Work Orders')?></span>
				<span class="info-box-number"><?php echo $this->workorderEntitys->getTotalItemCount(); ?></span>
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-green"><i class="fa fa-credit-card fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Un-Paid Invoices</span>
				<span class="info-box-number"><?php echo $this->invoiceEntitys->getTotalItemCount();?></span>
			</div>
		</div>
	</div>
	<?php endif;
	?>
	<!-- fix for small devices only -->
	<div class="clearfix visible-sm-block"></div>
	
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-red"><i class="fa fa-bell fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Host Alerts</span>
				<span class="info-box-number">0</span>
			</div>
		</div>
	</div>
	
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'task-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-yellow"><i class="fa fa-flag f-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text"><?php echo $this->translate('Tasks'); ?></span>
				<span class="info-box-number"><?php echo $this->taskEntitys->getTotalItemCount(); ?></span>
			</div>
		</div>
	</div>
	<?php endif;?>
</div>


<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title"><?php echo $this->translate('Annual Recap Report'); ?></h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8">
						<p class="text-center"><strong>
							
							<?php if($this->identity()->getUser() != 0): ?>
								<?php echo $this->translate('Cost'); ?>:
							<?php else: ?>
								<?php echo $this->translate('Sales'); ?>: 
							<?php endif; ?>
							<?php echo date("Y", time())?></strong>
						</p>
						<div class="chart">
							<canvas id="salesChart" style="height: 180px;"></canvas>
						</div>
					</div>
					<div class="col-md-4">
						<?php echo $this->SalesByLabor($this->clientId); ?>
					</div>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderLaborTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<span class="description-text"><?php echo $this->translate('TOTAL LABOR'); ?></span>
						</div>
					</div>
					
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderPartTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<span class="description-text"><?php echo $this->translate('TOTAL PARTS'); ?></span>
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderRevenuTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<?php if($this->identity()->getUser() != 0): ?>
								<span class="description-text"><?php echo $this->translate('TOTAL COST'); ?></span>
							<?php else: ?>
								<span class="description-text"><?php echo $this->translate('TOTAL REVENUE'); ?></span>
							<?php endif; ?>
							
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block">
							<h5 class="description-header"><?php echo $this->workorderTotalCount; ?></h5>
							<span class="description-text"><?php echo $this->translate('WORK COMPLETIONS'); ?></span>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-12">
		<!-- Client Details -->
		<div class="box box-default">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-user"></i> <?php echo $this->clientEntity->getClientName(); ?></h3>
				<div class="box-tools pull-right">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-update') ):?>
					<a href="<?php echo $this->url('client-update', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Edit this client');?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<?php if(! $this->userEntity): ?>
					<div class="alert alert-danger">
						<p><i class="fa fa-warning"></i> <?php echo $this->translate('Missing primary user.'); ?></p>
					</div>
				<?php else: ?>
				<div class="row">
					
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Primary Contact')?>:</b> 
						<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
							<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $this->userEntity->getUserId()));?>" title="<?php echo $this->translate('View this user'); ?>" class="pull-right">
								<?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?>
							</a>
						<?php else: ?>
							<span class="pull-right"><?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?></span>
						<?php endif;?>
						</p>
					</div>
					<div class="col-xs-12">
						
						<p><b><?php echo $this->translate('Phone')?>:</b> 
						
							<a href="tel:<?php echo $this->clientEntity->getPhoneEntity()->getPhoneNum(); ?>" title="<?php echo $this->translate('Call this phone number')?>" class="pull-right"><?php echo $this->clientEntity->getPhoneEntity()->getPhoneNum(); ?></a>
						</p>
					</div>
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('E-Mail')?>:</b> 
							<a class="pull-right"><?php echo $this->userEntity->getUserEmail(); ?></a>
						</p>
					</div>
				</div>
				
				
				<?php endif; ?>
			</div>
		</div>
		
		<!--  locations -->
		<div class="box box-default">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-globe f-fw"></i> <?php echo $this->translate('Locations'); ?></h3>
				<div class="box-tools pull-right">
				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-create') ):?>
					<a href="<?php echo $this->url('location-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Add new location');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New');?></a>
				<?php endif; ?>
				</div>
			</div>
			<?php if($this->locationEntitys->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no locations.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<tbody>
					<?php foreach($this->locationEntitys as $locationEntity): ?>
						<tr>
							<td>
							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
								<a href="<?php echo $this->url('location-view', array('clientId' => $this->clientId, 'locationId' => $locationEntity->getLocationId()));?>" title="<?php echo $this->translate('View this location'); ?>">
									<?php echo $locationEntity->getLocationStreet(); ?>
									<?php echo $locationEntity->getLocationCity()?>,
									<?php echo $locationEntity->getLocationState(); ?>
									<?php echo $locationEntity->getLocationZip(); ?>
								</a>
							<?php else: ?>
								<?php echo $locationEntity->getLocationStreet(); ?>
								<?php echo $locationEntity->getLocationCity()?>,
								<?php echo $locationEntity->getLocationState(); ?>
								<?php echo $locationEntity->getLocationZip(); ?>
							<?php endif; ?>
							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
								<a href="<?php echo $this->url('location-update', array('clientId' => $this->clientId, 'locationId' => $locationEntity->getLocationId())); ?>" title="<?php echo $this->translate('Edit this location'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							<?php endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		
		<!-- tasks -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'task-list') ):?>
		<div class="box box-warning">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-flag f-fw"></i> <?php echo $this->translate('Active Tasks'); ?></h3>
				<div class="box-tools pull-right">
					<a href="<?php echo $this->url('task-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new task'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<?php if($this->taskEntitys->getTotalItemCount() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no active tasks.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Task Title'); ?></th>
							<th><?php echo $this->translate('Start'); ?></th>
							<th><?php echo $this->translate('End'); ?></th>
							<th><?php echo $this->translate('Priority'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->taskEntitys as $taskEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('task-view', array('clientId' => $this->clientId, 'taskId' => $taskEntity->getTaskId())); ?>" title="<?php echo $this->translate('View this task'); ?>">
									<?php echo $taskEntity->getTaskTitle(); ?>
								</a>
							</td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateStart()); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateEnd()); ?></td>
							<td><?php echo $taskEntity->getPriorityEntity()->getTaskPriorityValue(); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
	
	<div class="col-sm-8 col-xs-12">
		<!-- Work Orders -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-list') ):?>
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-wrench"></i> <?php echo $this->translate('Active Work Orders'); ?></h3>
				<div class="box-tools pull-right">
				<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-create') ):?>
					<a href="<?php echo $this->url('workorder-create', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Create new work order'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				<?php endif;?>
				</div>
			</div>
			<?php if($this->workorderEntitys->getTotalItemCount() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no active work orders.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Work Order #'); ?></th>
							<th><?php echo $this->translate('Description'); ?></th>
							<th><?php echo $this->translate('Scheduled'); ?></th>	
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->workorderEntitys as $workorderEntity): ?>
						<tr>
							<td>
								<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-view') ):?>
								<a href="<?php echo $this->url('workorder-view', array('clientId' => $this->clientId, 'workorderId' => $workorderEntity->getWorkorderId()));?>" title="<?php echo $this->translate('View this work order'); ?>">
									<?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getWorkorderId(); ?>
								</a>
								<?php else: ?>
									<?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getWorkorderId(); ?>
								<?php endif; ?>
							</td>
							<td><?php echo $workorderEntity->getWorkorderDescription(); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateScheduled()); ?></td>
						</tr>
					<?php endforeach;?>	
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
		
		<!-- invoices -->
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-list') ):?>
		<div class="box box-success">
    		<div class="box-header with-border">
    			<h3 class="box-title"><i class="fa fa-credit-card"></i> <?php echo $this->translate('Un-Paid Invoices'); ?></h3>
				<div class="box-tools pull-right">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'invoice-create') ):?>
					<a href="<?php echo $this->url('invoice-create', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Create new invoice');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
    		</div>
    		<?php if($this->invoiceEntitys->getTotalItemCount() == 0):?>
    		<div class="box-body">
    			<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no un-paid invoices.'); ?></p>
				</div>
    		</div>
    		<?php else: ?>
			<div class="box-body table-responsive no-padding">
    			<table class="table table-hover">
    				<thead>
    					<tr>
    						<th><?php echo $this->translate('Invoice #'); ?></th>
    						<th><?php echo $this->translate('Date'); ?></th>
    						<th><?php echo $this->translate('Amount'); ?></th>
    					</tr>
    				</thead>
    				<tbody>
    				<?php foreach($this->invoiceEntitys as $invoiceEntity): ?>
    					<tr>
    						<td>
    							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-view') ):?>
    							<a href="<?php echo $this->url('invoice-view', array('clientId' => $this->clientId, 'invoiceId' => $invoiceEntity->getInvoiceId()));?>" title="<?php echo $this->translate('View this invoice'); ?>">
    								<?php echo $this->translate('Invoice #');?><?php echo $invoiceEntity->getInvoiceId(); ?>
    							</a>
    							<?php else: ?>
    								<?php echo $this->translate('Invoice #');?><?php echo $invoiceEntity->getInvoiceId(); ?>
    							<?php endif;?>
    						</td>
    						<td><?php echo date($this->appConfig()->getConfigDateShort(), $invoiceEntity->getInvoiceDate()); ?></td>
    						<td class="text-right"><?php echo $this->currencyFormat($invoiceEntity->getInvoiceTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
    					</tr>
    				<?php endforeach; ?>
    				</tbody>
    			</table>
			</div>
			<?php endif;?>
		</div>
		<?php endif; ?>
		<!-- Host Alerts -->
		<div class="box box-danger">
    		<div class="box-header with-border">
    			<h3 class="box-title"><i class="fa fa-bell"></i> <?php echo $this->translate('Host Alerts'); ?></h3>
				<div class="box-tools pull-right"></div>
    		</div>
    		<div class="box-body">
    			<div class="alert alert-info">
    				<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no host alerts'); ?></p>
    			</div>
    		</div>
    	</div>
	</div>
</div>