<div class="row">
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-aqua"><i class="fa fa-wrench fa-fw"></i></span>
			<div class="info-box-content">
				<a href="#openWorkorders" title="<?php echo $this->translate('View open work orders'); ?>">
					<span class="info-box-text"><?php echo $this->translate('Work Orders')?></span>
					<span class="info-box-number"><?php echo $this->workorderEntitys->getTotalItemCount(); ?></span>
				</a>
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-green"><i class="fa fa-credit-card fa-fw"></i></span>
			<div class="info-box-content">
				<a href="#un-paidInvoices" title="<?php echo $this->translate('View un-paid invocies'); ?>">
					<span class="info-box-text">Un-Paid Invoices</span>
					<span class="info-box-number"><?php echo $this->invoiceEntitys->getTotalItemCount();?></span>
				</a>
			</div>
		</div>
	</div>
	<?php endif;
	?>
	<!-- fix for small devices only -->
	<div class="clearfix visible-sm-block"></div>
	
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-red"><i class="fa fa-bell fa-fw"></i></span>
			<div class="info-box-content">
				<a href="#hostAlerts" title="<?php echo $this->translate('View host alerts'); ?>">
					<span class="info-box-text">Host Alerts</span>
					<span class="info-box-number">0</span>
				</a>
			</div>
		</div>
	</div>
	
	<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'task-list') ):?>
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-yellow"><i class="fa fa-flag f-fw"></i></span>
			<div class="info-box-content">
				<a href="#openTasks" title="<?php echo $this->translate('View open tasks'); ?>">
					<span class="info-box-text"><?php echo $this->translate('Tasks'); ?></span>
					<span class="info-box-number"><?php echo $this->taskEntitys->getTotalItemCount(); ?></span>
				</a>
			</div>
		</div>
	</div>
	<?php endif;?>
</div>


<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title"><?php echo $this->translate('Annual Recap Report'); ?></h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8">
						<p class="text-center"><strong>
							
							<?php if($this->identity()->getUser() != 0): ?>
								<?php echo $this->translate('Cost'); ?>:
							<?php else: ?>
								<?php echo $this->translate('Sales'); ?>: 
							<?php endif; ?>
							<?php echo date("Y", time())?></strong>
						</p>
						<div class="chart">
							<canvas id="salesChart" style="height: 180px;"></canvas>
						</div>
					</div>
					<div class="col-md-4">
						<?php echo $this->SalesByLabor($this->clientId); ?>
					</div>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderLaborTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<span class="description-text"><?php echo $this->translate('TOTAL LABOR'); ?></span>
						</div>
					</div>
					
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderPartTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<span class="description-text"><?php echo $this->translate('TOTAL PARTS'); ?></span>
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<h5 class="description-header"><?php echo $this->currencyFormat($this->workorderRevenuTotal, $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></h5>
							<?php if($this->identity()->getUser() != 0): ?>
								<span class="description-text"><?php echo $this->translate('TOTAL COST'); ?></span>
							<?php else: ?>
								<span class="description-text"><?php echo $this->translate('TOTAL REVENUE'); ?></span>
							<?php endif; ?>
							
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block">
							<h5 class="description-header"><?php echo $this->workorderTotalCount; ?></h5>
							<span class="description-text"><?php echo $this->translate('WORK COMPLETIONS'); ?></span>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-12">
		<!-- Client Details -->
		<div class="box box-default">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-user"></i> <?php echo $this->clientEntity->getClientName(); ?></h3>
				<div class="box-tools pull-right">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-delete') ):?>
					<a href="<?php echo $this->url('client-delete', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Delete this client');?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<?php endif; ?>
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-update') ):?>
					<a href="<?php echo $this->url('client-update', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Edit this client');?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<?php if(! $this->userEntity): ?>
					<div class="alert alert-danger">
						<p><i class="fa fa-warning"></i> <?php echo $this->translate('Missing primary user.'); ?></p>
					</div>
				<?php else: ?>
				<div class="row">
					
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Primary Contact')?>:</b> 
						<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
							<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $this->userEntity->getUserId()));?>" title="<?php echo $this->translate('View this user'); ?>" class="pull-right">
								<?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?>
							</a>
						<?php else: ?>
							<span class="pull-right"><?php echo $this->userEntity->getUserNameFirst(); ?> <?php echo $this->userEntity->getUserNameLast(); ?></span>
						<?php endif;?>
						</p>
					</div>
					<div class="col-xs-12">
						
						<p><b><?php echo $this->translate('Phone')?>:</b> 
						
							<a href="tel:<?php echo $this->clientEntity->getPhoneEntity()->getPhoneNum(); ?>" title="<?php echo $this->translate('Call this phone number')?>" class="pull-right"><?php echo $this->clientEntity->getPhoneEntity()->getPhoneNum(); ?></a>
						</p>
					</div>
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('E-Mail')?>:</b> 
							<a class="pull-right"><?php echo $this->userEntity->getUserEmail(); ?></a>
						</p>
					</div>
				</div>
				
				
				<?php endif; ?>
			</div>
		</div>
		
		<!--  locations -->
		<div class="box box-default">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-globe f-fw"></i> <?php echo $this->translate('Locations'); ?></h3>
				<div class="box-tools pull-right">
				<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-create') ):?>
					<a href="<?php echo $this->url('location-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Add new location');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New');?></a>
				<?php endif; ?>
				</div>
			</div>
			<?php if($this->locationEntitys->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no locations.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<tbody>
					<?php foreach($this->locationEntitys as $locationEntity): ?>
						<tr>
							<td>
							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
								<a href="<?php echo $this->url('location-view', array('clientId' => $this->clientId, 'locationId' => $locationEntity->getLocationId()));?>" title="<?php echo $this->translate('View this location'); ?>">
									<?php echo $locationEntity->getLocationStreet(); ?>
									<?php echo $locationEntity->getLocationCity()?>,
									<?php echo $locationEntity->getLocationState(); ?>
									<?php echo $locationEntity->getLocationZip(); ?>
								</a>
							<?php else: ?>
								<?php echo $locationEntity->getLocationStreet(); ?>
								<?php echo $locationEntity->getLocationCity()?>,
								<?php echo $locationEntity->getLocationState(); ?>
								<?php echo $locationEntity->getLocationZip(); ?>
							<?php endif; ?>
							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'location-view') ):?>
								<a href="<?php echo $this->url('location-update', array('clientId' => $this->clientId, 'locationId' => $locationEntity->getLocationId())); ?>" title="<?php echo $this->translate('Edit this location'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							<?php endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		
		<!-- tasks -->
		<a id="openTasks"></a>
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'task-list') ):?>
		<div class="box box-warning">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-flag f-fw"></i> <?php echo $this->translate('Active Tasks'); ?></h3>
				<div class="box-tools pull-right">
					<a href="<?php echo $this->url('task-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new task'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<?php if($this->taskEntitys->getTotalItemCount() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no active tasks.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Task Title'); ?></th>
							<th><?php echo $this->translate('Start'); ?></th>
							<th><?php echo $this->translate('End'); ?></th>
							<th><?php echo $this->translate('Priority'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->taskEntitys as $taskEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('task-view', array('clientId' => $this->clientId, 'taskId' => $taskEntity->getTaskId())); ?>" title="<?php echo $this->translate('View this task'); ?>">
									<?php echo $taskEntity->getTaskTitle(); ?>
								</a>
							</td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateStart()); ?></td>
							<td><?php echo date($this->appConfig()->getConfigDateLong(), $taskEntity->getTaskDateEnd()); ?></td>
							<td><?php echo $taskEntity->getPriorityEntity()->getTaskPriorityValue(); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
	
	<div class="col-sm-8 col-xs-12">
		<!-- Work Orders -->
		<a id="openWorkorders"></a>
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-list') ):?>
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-wrench"></i> <?php echo $this->translate('Active Work Orders'); ?></h3>
				<div class="box-tools pull-right">
				<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'workorder-create') ):?>
					<a href="<?php echo $this->url('workorder-create', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Create new work order'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				<?php endif;?>
				</div>
			</div>
			<?php if($this->workorderEntitys->getTotalItemCount() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no active work orders.'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Work Order #'); ?></th>
							<th><?php echo $this->translate('Title'); ?></th>
							<th class="text-right"><?php echo $this->translate('Scheduled'); ?></th>	
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->workorderEntitys as $workorderEntity): ?>
						<tr>
							<td nowrap>
								<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-view') ):?>
								<a href="<?php echo $this->url('workorder-view', array('clientId' => $this->clientId, 'workorderId' => $workorderEntity->getWorkorderId()));?>" title="<?php echo $this->translate('View this work order'); ?>">
									<?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getWorkorderId(); ?>
								</a>
								<?php else: ?>
									<?php echo $this->translate('Work Order #'); ?><?php echo $workorderEntity->getWorkorderId(); ?>
								<?php endif; ?>
							</td>
							<td><?php echo $workorderEntity->getWorkorderTitle(); ?></td>
							<td nowrap class="text-right"><?php echo date($this->appConfig()->getConfigDateLong(), $workorderEntity->getWorkorderDateScheduled()); ?></td>
						</tr>
					<?php endforeach;?>	
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
		
		<!-- invoices -->
		<a id="un-paidInvoices"></a>
		<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-list') ):?>
		<div class="box box-success">
    		<div class="box-header with-border">
    			<h3 class="box-title"><i class="fa fa-credit-card"></i> <?php echo $this->translate('Un-Paid Invoices'); ?></h3>
				<div class="box-tools pull-right">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'invoice-create') ):?>
					<a href="<?php echo $this->url('invoice-create', array('clientId' => $this->clientId)); ?>" title="<?php echo $this->translate('Create new invoice');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
    		</div>
    		<?php if($this->invoiceEntitys->getTotalItemCount() == 0):?>
    		<div class="box-body">
    			<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no un-paid invoices.'); ?></p>
				</div>
    		</div>
    		<?php else: ?>
			<div class="box-body table-responsive no-padding">
    			<table class="table table-hover">
    				<thead>
    					<tr>
    						<th><?php echo $this->translate('Invoice #'); ?></th>
    						<th><?php echo $this->translate('Date'); ?></th>
    						<th><?php echo $this->translate('Amount'); ?></th>
    					</tr>
    				</thead>
    				<tbody>
    				<?php foreach($this->invoiceEntitys as $invoiceEntity): ?>
    					<tr>
    						<td>
    							<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'invoice-view') ):?>
    							<a href="<?php echo $this->url('invoice-view', array('clientId' => $this->clientId, 'invoiceId' => $invoiceEntity->getInvoiceId()));?>" title="<?php echo $this->translate('View this invoice'); ?>">
    								<?php echo $this->translate('Invoice #');?><?php echo $invoiceEntity->getInvoiceId(); ?>
    							</a>
    							<?php else: ?>
    								<?php echo $this->translate('Invoice #');?><?php echo $invoiceEntity->getInvoiceId(); ?>
    							<?php endif;?>
    						</td>
    						<td><?php echo date($this->appConfig()->getConfigDateShort(), $invoiceEntity->getInvoiceDate()); ?></td>
    						<td class="text-right"><?php echo $this->currencyFormat($invoiceEntity->getInvoiceTotal(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang()); ?></td>
    					</tr>
    				<?php endforeach; ?>
    				</tbody>
    			</table>
			</div>
			<?php endif;?>
		</div>
		<?php endif; ?>
		
		<!-- Host Alerts -->
		<a id="hostAlerts"></a>
		<div class="box box-danger">
    		<div class="box-header with-border">
    			<h3 class="box-title"><i class="fa fa-bell"></i> <?php echo $this->translate('Host Alerts'); ?></h3>
				<div class="box-tools pull-right"></div>
    		</div>
    		<div class="box-body">
    			<div class="alert alert-info">
    				<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no host alerts'); ?></p>
    			</div>
    		</div>
    	</div>
	</div>
</div>
<script>
$( document ).ready(function() {
	//-----------------------
	  //- MONTHLY SALES CHART -
	  //-----------------------

	  // Get context with jQuery - using jQuery's .get() method.
	  var salesChartCanvas = $("#salesChart").get(0).getContext("2d");
	  // This will get the first returned node in the jQuery collection.
	  var salesChart = new Chart(salesChartCanvas);

	
	var salesChartData = {
		labels: [<?php for($x = 1; $x <= 12; $x++): ?>"<?php echo $x;?>"<?php if($x < 12): ?>,<?php endif; ?><?php endfor;?>],
		datasets: [
			{
		        label: "Labor",
		        fillColor: "rgba(60,141,188,0.9)",
		        strokeColor: "rgba(60,141,188,0.8)",
		        pointColor: "#3b8bba",
		        pointStrokeColor: "rgba(60,141,188,1)",
		        pointHighlightFill: "#fff",
		        pointHighlightStroke: "rgba(60,141,188,1)",
		             data: [<?php foreach($this->dataSet as $data): ?><?php echo $data;?>,<?php endforeach;?>]
		           },
			]
		};

	var salesChartOptions = {
		    //Boolean - If we should show the scale at all
		    showScale: true,
		    //Boolean - Whether grid lines are shown across the chart
		    scaleShowGridLines: false,
		    //String - Colour of the grid lines
		    scaleGridLineColor: "rgba(0,0,0,.05)",
		    //Number - Width of the grid lines
		    scaleGridLineWidth: 1,
		    //Boolean - Whether to show horizontal lines (except X axis)
		    scaleShowHorizontalLines: true,
		    //Boolean - Whether to show vertical lines (except Y axis)
		    scaleShowVerticalLines: true,
		    //Boolean - Whether the line is curved between points
		    bezierCurve: true,
		    //Number - Tension of the bezier curve between points
		    bezierCurveTension: 0.3,
		    //Boolean - Whether to show a dot for each point
		    pointDot: false,
		    //Number - Radius of each point dot in pixels
		    pointDotRadius: 4,
		    //Number - Pixel width of point dot stroke
		    pointDotStrokeWidth: 1,
		    //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
		    pointHitDetectionRadius: 20,
		    //Boolean - Whether to show a stroke for datasets
		    datasetStroke: true,
		    //Number - Pixel width of dataset stroke
		    datasetStrokeWidth: 2,
		    //Boolean - Whether to fill the dataset with a color
		    datasetFill: true,
		    //String - A legend template
		    legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%=datasets[i].label%></li><%}%></ul>",
		    //Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
		    maintainAspectRatio: true,
		    //Boolean - whether to make the chart responsive to window resizing
		    responsive: true
		  };

	//Create the line chart
	  salesChart.Bar(salesChartData, salesChartOptions);


		
    console.log( "ready!" );
});
</script>