<div class="row">
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-aqua"><i class="fa fa-wrench fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Work Orders</span>
				<span class="info-box-number">0</span>
			</div>
		</div>
	</div>
	
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-red"><i class="fa fa-credit-card fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Un-Paid Invoices</span>
				<span class="info-box-number">0</span>
			</div>
		</div>
	</div>
	
	<!-- fix for small devices only -->
	<div class="clearfix visible-sm-block"></div>
	
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-green"><i class="fa fa-warning fa-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Host Alerts</span>
				<span class="info-box-number">0</span>
			</div>
		</div>
	</div>
	
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-yellow"><i class="fa fa-tasks f-fw"></i></span>
			<div class="info-box-content">
				<span class="info-box-text">Tasks</span>
				<span class="info-box-number">0</span>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Monthly Recap Report</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8">
						<p class="text-center"><strong>Sales: 1 Jan, 2014 - 30 Jul, 2014</strong></p>
						<div class="chart">
							<canvas id="salesChart" style="height: 180px;"></canvas>
						</div>
					</div>
					<div class="col-md-4">
						<p class="text-center"><strong>Sales By Labor Rate</strong></p>
						<div class="progress-group">
							<span class="progress-text">Basic Service Charge</span>
							<span class="progress-number"><b>$780</b></span>
							<div class="progress sm">
								<div class="progress-bar progress-bar-aqua" style="width: 80%"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
							<h5 class="description-header">$35,210.43</h5>
							<span class="description-text">TOTAL REVENUE</span>
						</div>
					</div>
					
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
							<h5 class="description-header">$10,390.90</h5>
							<span class="description-text">TOTAL COST</span>
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block border-right">
							<span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
							<h5 class="description-header">$24,813.53</h5>
							<span class="description-text">TOTAL PROFIT</span>
						</div>
					</div>
								
					<div class="col-sm-3 col-xs-6">
						<div class="description-block">
							<span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
							<h5 class="description-header">1200</h5>
							<span class="description-text">WORK COMPLETIONS</span>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-12">
		<!-- Client Details -->
		<div class="box box-default">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-user"></i> <?php echo $this->clientEntity->getClientName(); ?></h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool"><i class="fa fa-pencil"></i> Edit</button>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Primary Contact')?>:</b> </p>
					</div>
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Phone')?>:</b> </p>
					</div>
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('E-Mail')?>:</b> </p>
					</div>
					<div class="col-xs-12">
						<p><b><?php echo $this->translate('Mobile')?>:</b> </p>
					</div>
				</div>
			</div>
		</div>
		
		<!-- tasks -->
		<div class="box box-warning">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-tasks f-fw"></i> Open Tasks</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
				</div>
			</div>
			<div class="box-body">
			
			</div>
		</div>
	</div>
	<div class="col-sm-8 col-xs-12">
		<!-- Work Orders -->
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title"><i class="fa fa-wrench"></i> Active Work Orders</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" ng-click="createWorkorder(clientId)"><i class="fa fa-plus"></i> New</button>
				</div>
			</div>
			<div class="box-body">
			
			</div>
		</div>
		
		<!-- invoices -->
		<div class="box box-danger">
    		<div class="box-header with-border">
    			<h3 class="box-title"><i class="fa fa-credit-card"></i> Un-Paid Invoices</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool"><i class="fa fa-plus"></i> New</button>
				</div>
    		</div>
    		<div class="box-body">
			
			</div>
		</div>
		
	</div>
</div>