<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('View Auth'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('auth-delete', array('authId' => $this->authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Delete this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<a href="<?php echo $this->url('auth-update', array('authId' => $this->authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Edit this auth'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<a href="<?php echo $this->url('auth-password', array('authId' => $this->authEntity->getAuthId())); ?>" title="<?php echo $this->translate('Reset Password'); ?>" class="btn btn-box-tool"><i class="fa fa-lock"></i> <?php echo $this->translate('Password'); ?></a>
				</div>
			</div>
			<div class="box-body box-profile">
				 <h3 class="profile-username"><?php echo $this->authEntity->getAuthName(); ?></h3>
				 <p class="text-muted"><?php echo $this->authEntity->getAuthEmail(); ?></p>
				 <ul class="list-group list-group-unbordered">
				 	<li class="list-group-item">
				 		<b><?php echo $this->translate('Role');?></b> <a class="pull-right"><?php echo $this->authEntity->getAuthRole(); ?></a>
				 	</li>
				 	<li class="list-group-item">
				 		<b><?php echo $this->translate('Type'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getAuthType(); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Last Sign In'); ?></b> 
 				 			<a class="pull-right"><?php echo ($this->authEntity->getAuthLastLogin() > 0) ? $this->authEntity->getAuthLastLogin() : $this->translate('Never Signed In'); ?></a>
 				 	</li>
 				 	<li class="list-group-item">
 				 		<b><?php echo $this->translate('Ip Address');?></b> <a class="pull-right"><?php echo ($this->authEntity->getAuthLastIp() != null) ? $this->authEntity->getAuthLastIp() : $this->translate('Never Signed In'); ?></a>
 				 	</li>
				 </ul>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-user"></i>
					<?php if($this->authEntity->getAuthType() == 'Employee'): ?>
						<?php echo $this->translate('Employee'); ?>
					<?php else: ?>
						<?php echo $this->translate('User'); ?>
					<?php endif;?>
				</h3>
				<div class="box-tools">
					<?php if($this->authEntity->getAuthType() == 'Employee'): ?>
						<a href="<?php echo $this->url('employee-delete', array('employeeId' => $this->authEntity->getEmployeeEntity()->getEmployeeId())); ?>" title="<?php echo $this->translate('Delete this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
						<a href="<?php echo $this->url('employee-update', array('employeeId' => $this->authEntity->getEmployeeEntity()->getEmployeeId())); ?>" title="<?php echo $this->translate('Edit this employee'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php else: ?>
						<a href="<?php echo $this->url('user-delete', array('clientId' => $this->authEntity->getUserEntity()->getClientId(), 'userId' => $this->authEntity->getUserEntity()->getUserId())); ?>" title="<?php echo $this->translate('Delete this user'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
						<a href="<?php echo $this->url('user-update', array('clientId' => $this->authEntity->getUserEntity()->getClientId(), 'userId' => $this->authEntity->getUserEntity()->getUserId())); ?>" title="<?php echo $this->translate('Edit this user'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif;?>
				</div>
			</div>
			<div class="box-body box-profile">
				<?php if($this->authEntity->getAuthType() == 'Employee'): ?>
					<h3 class="profile-username"><?php echo $this->authEntity->getAuthName(); ?></h3>
					<p class="text-muted"><?php echo $this->authEntity->getAuthEmail(); ?></p>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<b><?php echo $this->translate('Title'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getEmployeeEntity()->getEmployeeTitle();?></a>
						</li>
						<li class="list-group-item">
							<b><?php echo $this->translate('Status'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getEmployeeEntity()->getEmployeeStatus();?></a>
						</li>
					</ul>
				<?php else: ?>
    				<h3 class="profile-username"><?php echo $this->authEntity->getUserEntity()->getUserNameFirst();?> <?php echo $this->authEntity->getUserEntity()->getUserNameLast();?></h3>
    				<p class="text-muted"><?php echo $this->authEntity->getUserEntity()->getUserEmail(); ?></p>
    				<ul class="list-group list-group-unbordered">
    					<li class="list-group-item">
    						<b><?php echo $this->translate('Title'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getUserEntity()->getUserJobTitle(); ?></a>
    					</li>
    					<li class="list-group-item">
    						<b><?php echo $this->translate('User Type'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getUserEntity()->getUserType(); ?></a>
    					</li>
    					<li class="list-group-item">
    						<b><?php echo $this->translate('User Status'); ?></b> <a class="pull-right"><?php echo $this->authEntity->getUserEntity()->getUserStatus(); ?></a>
    					</li>
    				</ul>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>