<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-line-chart" aria-hidden="true"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<div class="alert alert-warning">
					<p><i class="fa fa-warning fa-fw"></i> <?php echo $this->translate('Are you sure you want to delete the following subscription?'); ?></p>
				</div>
				
				<table class="table table-bordered table-hover table-striped table-condensed">
    				<thead>
    					<tr>
    						<th><?php echo $this->translate('Subscription Id'); ?></th>
    						<th><?php echo $this->translate('Due Date'); ?></th>
    						<th><?php echo $this->translate('End Date'); ?></th>
    						<th><?php echo $this->translate('Schedule'); ?></th>
    						<th><?php echo $this->translate('Status'); ?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<tr>
    						<td>
    							<a href="<?php echo $this->url('subscription-view', array('subscriptionId' => $this->entity->getSubscriptionId())); ?>" 
    								title="<?php echo $this->translate('View this subscription'); ?>">
    								<?php echo $this->entity->getSubscriptionId(); ?>
    							</a>
    						</td>
    						<td><?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getSubscriptionDateDue()); ?></td>
    						<td><?php echo date($this->appConfig()->getConfigDateShort(), $this->entity->getSubscriptionDateEnd()); ?></td>
    						<td><?php echo $this->entity->getSubscriptionScheduleEntity()->getSubscriptionScheduleName(); ?></td>
    						<td><?php echo $this->entity->getSubscriptionStatusEntity()->getSubscriptionStatusName(); ?></td>
    					</tr>
    				</tbody>
    			</table>
    			
				<form method="post">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>