<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Config\Service\ConfigServiceInterface'             => __DIR__ . '/src/Config/Service/ConfigServiceInterface.php',
    'Config\Service\Factory\ConfigServiceFactory'       => __DIR__ . '/src/Config/Service/Factory/ConfigServiceFactory.php',
    'Config\Service\ConfigService'                      => __DIR__ . '/src/Config/Service/ConfigService.php',
    'Config\Controller\UpdateController'                => __DIR__ . '/src/Config/Controller/UpdateController.php',
    'Config\Controller\IndexController'                 => __DIR__ . '/src/Config/Controller/IndexController.php',
    'Config\Controller\Factory\IndexControllerFactory'  => __DIR__ . '/src/Config/Controller/Factory/IndexControllerFactory.php',
    'Config\Controller\Factory\UpdateControllerFactory' => __DIR__ . '/src/Config/Controller/Factory/UpdateControllerFactory.php',
    'Config\View\Helper\AppConfig'                      => __DIR__ . '/src/Config/View/Helper/AppConfig.php',
    'Config\View\Helper\Factory\AppConfigFactory'       => __DIR__ . '/src/Config/View/Helper/Factory/AppConfigFactory.php',
    'Config\Form\ConfigForm'                            => __DIR__ . '/src/Config/Form/ConfigForm.php',
    'Config\Mapper\ConfigMapper'                        => __DIR__ . '/src/Config/Mapper/ConfigMapper.php',
    'Config\Mapper\ConfigMapperInterface'               => __DIR__ . '/src/Config/Mapper/ConfigMapperInterface.php',
    'Config\Mapper\Factory\ConfigMapperFactory'         => __DIR__ . '/src/Config/Mapper/Factory/ConfigMapperFactory.php',
    'Config\Hydrator\ConfigHydrator'                    => __DIR__ . '/src/Config/Hydrator/ConfigHydrator.php',
    'Config\Entity\ConfigEntityInterface'               => __DIR__ . '/src/Config/Entity/ConfigEntityInterface.php',
    'Config\Entity\ConfigEntity'                        => __DIR__ . '/src/Config/Entity/ConfigEntity.php',
    'Config\Module'                                     => __DIR__ . '/Module.php',
);
