<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-file" aria-hidden="true"></i>
					<?php echo $this->translate('Files'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'client-file-create') ):?>
					<a href="<?php echo $this->url('client-file-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new file'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
            			<form class="form-inline">
            				<div class="row">
            					<div class="col-xs-12">
            						<div class="form-group">
                						<div class="input-group input-group-sm">
                							<input type="text" name="keyword" id="keyword" class="form-control pull-right" placeholder="<?php echo $this->translate('Search'); ?>" value="<?php echo $this->keyword; ?>">
                    						<div class="input-group-btn">
                    							<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    						</div>
                						</div>
                					</div>
                				</div>
                			</div>
            			</form>
            		</li>
            		<?php if($this->paginator->count() == 0): ?>
            		<li class="list-group-item">
        				<div class="alert alert-info">
        					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No Files'); ?></p>
        				</div>
        			</li>	
            		<?php else: ?>
            		<?php foreach($this->paginator as $clientFileEntity): ?>
            		<?php $fileEntity = $clientFileEntity->getFileEntity(); ?>
            		<li class="list-group-item">
            			<div class="row">
            				<div class="col-xs-12">
            					<h3 class="profile-username">
            						<a href="<?php echo $this->url('client-file-view', array('clientFileId' => $clientFileEntity->getClientFileId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('View File'); ?>"><?php echo $fileEntity->getFileTitle(); ?></a>
            					</h3>
            				</div>
            			</div>
            			<div class="row">
            				<div class="col-xs-12 col-sm-4">
            					<b><?php echo $this->translate('Name'); ?>:</b> <?php echo $fileEntity->getFileName(); ?>
            				</div>
            				<div class="col-xs-12 col-sm-2">
            					<b><?php echo $this->translate('Type'); ?>:</b> <?php echo $fileEntity->getFileMime(); ?>
            				</div>
            				<div class="col-xs-12 col-sm-2">
            					<b><?php echo $this->translate('Size'); ?>:</b> <?php echo number_format($fileEntity->getFileSize() / 1024, 2, '.', ''); ?> mb
            				</div>
            				<div class="col-xs-12 col-sm-2">
            					<b><?php echo $this->translate('Created');?>:</b> <?php echo date($this->appConfig()->getConfigDateShort(), $fileEntity->getFileCreate()); ?>
            				</div>
            				<div class="col-xs-12 col-sm-2">
            					<a href="<?php echo $this->url('file-download', array('fileId' => $fileEntity->getFileId())); ?>" title="<?php echo $this->translate('Download File'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-download" aria-hidden="true"></i></a>
            				</div>
            			</div>
            		</li>
            		<?php endforeach; ?>
            		<?php endif;?>
				</ul>
				<?php if($this->pageCount > 1): ?>
				<div class="row">
					<div class="col-xs-12">
    				<?php echo $this->Paginator(
    	                        $this->itemCountPerPage,
    	                        $this->itemCount,
    	                        $this->pageCount,
    	                        $this->page,
    	                        $this->routeParams,
    	                        $this->queryParams); ?>
    	        	</div>
    			</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
			