<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->translate('Subscriptions'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
			<?php if($this->paginator->count() == 0): ?>
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No subscriptions.'); ?>
				</div>
				<?php else: ?>
				
				<?php endif;?>
			</div>
		</div>
	</div>
</div>