<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ClientFavorite\Service\FavoriteService'                       => __DIR__ . '/src/ClientFavorite/Service/FavoriteService.php',
    'ClientFavorite\Service\Factory\FavoriteServiceFactory'        => __DIR__ . '/src/ClientFavorite/Service/Factory/FavoriteServiceFactory.php',
    'ClientFavorite\Service\FavoriteServiceInterface'              => __DIR__ . '/src/ClientFavorite/Service/FavoriteServiceInterface.php',
    'ClientFavorite\Controller\DeleteController'                   => __DIR__ . '/src/ClientFavorite/Controller/DeleteController.php',
    'ClientFavorite\Controller\CreateController'                   => __DIR__ . '/src/ClientFavorite/Controller/CreateController.php',
    'ClientFavorite\Controller\IndexController'                    => __DIR__ . '/src/ClientFavorite/Controller/IndexController.php',
    'ClientFavorite\Controller\Factory\IndexControllerFactory'     => __DIR__ . '/src/ClientFavorite/Controller/Factory/IndexControllerFactory.php',
    'ClientFavorite\Controller\Factory\CreateControllerFactory'    => __DIR__ . '/src/ClientFavorite/Controller/Factory/CreateControllerFactory.php',
    'ClientFavorite\Controller\Factory\DeleteControllerFactory'    => __DIR__ . '/src/ClientFavorite/Controller/Factory/DeleteControllerFactory.php',
    'ClientFavorite\View\Helper\Favorite'                          => __DIR__ . '/src/ClientFavorite/View/Helper/Favorite.php',
    'ClientFavorite\View\Helper\Factory\FavoriteViewHelperFactory' => __DIR__ . '/src/ClientFavorite/View/Helper/Factory/FavoriteViewHelperFactory.php',
    'ClientFavorite\Mapper\FavoriteMapperInterface'                => __DIR__ . '/src/ClientFavorite/Mapper/FavoriteMapperInterface.php',
    'ClientFavorite\Mapper\FavoriteMapper'                         => __DIR__ . '/src/ClientFavorite/Mapper/FavoriteMapper.php',
    'ClientFavorite\Mapper\Factory\FavoriteMapperFactory'          => __DIR__ . '/src/ClientFavorite/Mapper/Factory/FavoriteMapperFactory.php',
    'ClientFavorite\Hydrator\FavoriteHydrator'                     => __DIR__ . '/src/ClientFavorite/Hydrator/FavoriteHydrator.php',
    'ClientFavorite\Entity\FavoriteEntity'                         => __DIR__ . '/src/ClientFavorite/Entity/FavoriteEntity.php',
    'ClientFavorite\Module'                                        => __DIR__ . '/Module.php',
);
