<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-shopping-cart" aria-hidden="true"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools">
					<?php if($this->acl()->isAllowed($this->identity()->getAuthRole(), 'product-type-create')): ?>
					<a href="<?php echo $this->url('product-type-create');?>" 
						title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool">
							<i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?>
					</a>
					<?php endif; ?>
				</div>
			</div>
			<?php if($this->paginator->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No product types'); ?>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-bordered table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate('Product Type Id'); ?></th>
							<th><?php echo $this->translate('Product Type Name');?></th>
							<th><?php echo $this->translate('Status'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $entity): ?>
						<tr>
							<td>
								<?php if($this->acl()->isAllowed($this->identity()->getAuthRole(), 'product-type-view')): ?>
								<a href="<?php echo $this->url('product-type-view', array('productTypeId' => $entity->getProductTypeId()));?>" 
									title="<?php echo $this->translate('View this product type'); ?>">
										<?php echo $entity->getProductTypeId(); ?>
								</a>
								<?php else: ?>
								<?php echo $entity->getProductTypeId()?>
								<?php endif; ?>
							</td>
							<td><?php echo $entity->getProductTypeName(); ?></td>
							<td><?php echo $entity->getProductTypeStatus(); ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>