<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-dollar" aria-hidden="true"></i>
					<?php echo $this->translate('Payroll Deduction Types'); ?>
				</h3>
				<div class="box-tools">
					<?php if($this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-deduction-type-create')): ?>
					<a href="<?php echo $this->url('payroll-deduction-type-create');?>" 
						title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool">
							<i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?>
					</a>
					<?php endif; ?>
				</div>
			</div>
			<?php if($this->paginator->count() == 0):?>
			<div class="box-body">
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate('No payroll deduction types'); ?>
				</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-bordered table-hover table-striped table-condensed">
					<thead>
						<tr>
							<th><?php echo $this->translate('Id'); ?></th>
							<th><?php echo $this->translate('Name'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $entity): ?>
						<tr>
							<td><?php echo $entity->getPayrollDeductionTypeId();?></td>
							<td>
								<?php if($this->acl()->isAllowed($this->identity()->getAuthRole(), 'payroll-deduction-type-view')): ?>
								<a href="<?php echo $this->url('payroll-deduction-type-view', array('payrollDeductionTypeId' => $entity->getPayrollDeductionTypeId())); ?>" 
									title="<?php echo $this->translate('View this payroll deduction type'); ?>">
										<?php echo $entity->getPayrollDeductionTypeName(); ?>
								</a>
								<?php else: ?>
								
								<?php endif;?>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif; ?>
			</div>
		</div>
	</div>
</div>