<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Config'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('config-update');?>" title="<?php echo $this->translate('Edit'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
				</div>
			</div>
		</div>
	</div>
</div>