<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ClientAccount\Service\AccountServiceInterface'       => __DIR__ . '/src/ClientAccount/Service/AccountServiceInterface.php',
    'ClientAccount\Service\AccountService'                => __DIR__ . '/src/ClientAccount/Service/AccountService.php',
    'ClientAccount\Service\Factory\AccountServiceFactory' => __DIR__ . '/src/ClientAccount/Service/Factory/AccountServiceFactory.php',
    'ClientAccount\Mapper\AccountMapperInterface'         => __DIR__ . '/src/ClientAccount/Mapper/AccountMapperInterface.php',
    'ClientAccount\Mapper\Factory\AccountMapperFactory'   => __DIR__ . '/src/ClientAccount/Mapper/Factory/AccountMapperFactory.php',
    'ClientAccount\Mapper\AccountMapper'                  => __DIR__ . '/src/ClientAccount/Mapper/AccountMapper.php',
    'ClientAccount\Hydrator\AccountHydrator'              => __DIR__ . '/src/ClientAccount/Hydrator/AccountHydrator.php',
    'ClientAccount\Entity\AccountEntity'                  => __DIR__ . '/src/ClientAccount/Entity/AccountEntity.php',
    'ClientAccount\Module'                                => __DIR__ . '/Module.php',
);
