<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-bank"></i>
					<?php echo $this->translate('Account Types'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('account-type-create');?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
			<?php if($this->typeEntitys->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no account types.'); ?>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name');?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->typeEntitys as $typeEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('account-type-view', array('accountTypeId' => $typeEntity->getAccountTypeId()));?>" title="<?php echo $this->translate('View this account type')?>">
									<?php echo $typeEntity->getAccountTypeName(); ?>
								</a>
							</td>
							<td class="text-right">
								<a href="<?php echo $this->url('account-type-delete', array('accountTypeId' => $typeEntity->getAccountTypeId())); ?>" title="<?php echo $this->translate('Delete this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
								<a href="<?php echo $this->url('account-type-update', array('accountTypeId' => $typeEntity->getAccountTypeId())); ?>" title="<?php echo $this->translate('Edit this labor rate'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
							
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>