<?php if($this->adminAcl): ?>

<li class="treeview <?php if($this->activeMenuItem == 'admin'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-cogs"></i> <span><?php echo $this->translate('Admin'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<!--  Admin Home -->
		<li class="<?php if($this->activeSubMenuItem == 'admin-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('admin-index'); ?>" title="<?php echo $this->translate('Home'); ?>">
				<i class="fa fa-home"></i> <?php echo $this->translate('Home'); ?>
			</a>
		</li>
		
		<!-- Auth -->
		<li class="<?php if($this->activeSubMenuItem == 'auth-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('auth-index'); ?>" title="<?php echo $this->translate('Auth'); ?>">
				<i class="fa fa-lock"></i> <?php echo $this->translate('Auth'); ?>
			</a>
		</li>
		
		<!-- config -->
		<li class="<?php if($this->activeSubMenuItem == 'config-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('config-index'); ?>" title="<?php echo $this->translate('Config'); ?>">
				<i class="fa fa-cog"></i> <?php echo $this->translate('Config'); ?>
			</a>
		</li>
		
		<!-- Cron -->
		<li class="<?php if($this->activeSubMenuItem == 'cron-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('cron-index'); ?>" title="<?php echo $this->translate('Cron'); ?>">
				<i class="fa fa-gears"></i> <?php echo $this->translate('Cron'); ?>
			</a>
		</li>
		
		
		
		<!-- Employees -->
		<li class="<?php if($this->activeSubMenuItem == 'employee-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-index'); ?>" title="<?php echo $this->translate('Employees'); ?>">
				<i class="fa fa-user"></i> <?php echo $this->translate('Employees'); ?>
			</a>
		</li>
		
		
		
		<!-- Host Attributes -->
		<li class="<?php if($this->activeSubMenuItem == 'host-attribute-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('host-attribute-index'); ?>" title="<?php echo $this->translate('Host Attributes'); ?>">
				<i class="fa fa-desktop"></i> <?php echo $this->translate('Host Attributes'); ?>
			</a>
		</li>
		
		<!-- Host Types -->
		<li class="<?php if($this->activeSubMenuItem == 'host-type-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('host-type-index'); ?>" title="<?php echo $this->translate('Host Types'); ?>">
				<i class="fa fa-desktop"></i> <?php echo $this->translate('Host Types'); ?>
			</a>
		</li>
			
		<!-- Invoice Options -->
		<li class="<?php if($this->activeSubMenuItem == 'invoice-option-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('invoice-option-index'); ?>" title="<?php echo $this->translate('Invoice Options'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Invoice Options'); ?>
			</a>
		</li>
		
		<!-- Labor Rates -->
		<li class="<?php if($this->activeSubMenuItem == 'labor-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('labor-index'); ?>" title="<?php echo $this->translate('Labor Rates'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Labor Rates'); ?>
			</a>
		</li>
		
		<!-- log -->
		<li class="<?php if($this->activeSubMenuItem == 'log-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('log-index'); ?>" title="<?php echo $this->translate('Logs'); ?>">
				<i class="fa fa-file"></i> <?php echo $this->translate('Logs'); ?>
			</a>
		</li>
		
		<!-- Payment Options -->
		<li class="<?php if($this->activeSubMenuItem == 'payment-option-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('payment-option-index'); ?>" title="<?php echo $this->translate('Payment Options'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Payment Options'); ?>
			</a>
		</li>
		
		<!-- Products -->
		<li class="<?php if($this->activeSubMenuItem == 'product-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('product-index'); ?>" title="<?php echo $this->translate('Products'); ?>">
				<i class="fa fa-shopping-cart" aria-hidden="true"></i> <?php echo $this->translate('Products'); ?>
			</a>
		</li>
		
		<!-- Access Control Lists -->
		<li class="<?php if($this->activeSubMenuItem == 'host-attribute-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('host-attribute-index'); ?>" title="<?php echo $this->translate('Access Control Lists'); ?>">
				<i class="fa fa-lock"></i> <?php echo $this->translate('Permisions'); ?>
			</a>
		</li>
		
		<!-- Work order options -->
		<li class="<?php if($this->activeSubMenuItem == 'workorder-option-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('workorder-option-index'); ?>" title="<?php echo $this->translate('Work Order Options'); ?>">
				<i class="fa fa-wrench"></i> <?php echo $this->translate('Work Order Options'); ?>
			</a>
		</li>
		
		
		
		
	</ul>
</li>
<?php endif; ?>