<?php // \Zend\Debug\Debug::dump($this->acl->isAllowed($this->identity()->getAuthRole(), 'admin-index'));?>
<li class="header"><?php echo $this->translate('ADMIN NAVIGATION'); ?></li>
<li class="treeview <?php if($this->activeMenuItem == 'admin'):?>active<?php endif;?>">
	<a href="#">
		<i class="fa fa-cogs"></i> <span><?php echo $this->translate('Admin'); ?></span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<!--  Admin Home -->
		<li class="<?php if($this->activeSubMenuItem == 'admin-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('admin-index'); ?>" title="<?php echo $this->translate('Home'); ?>">
				<i class="fa fa-home"></i> <?php echo $this->translate('Home'); ?>
			</a>
		</li>
		
		<!-- config -->
		<li class="<?php if($this->activeSubMenuItem == 'config-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('config-index'); ?>" title="<?php echo $this->translate('Config'); ?>">
				<i class="fa fa-cog"></i> <?php echo $this->translate('Config'); ?>
			</a>
		</li>
		
		<!-- Auth -->
		<li class="<?php if($this->activeSubMenuItem == 'auth-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('auth-index'); ?>" title="<?php echo $this->translate('Auth'); ?>">
				<i class="fa fa-lock"></i> <?php echo $this->translate('Auth'); ?>
			</a>
		</li>
		
		<!-- Employees -->
		<li class="<?php if($this->activeSubMenuItem == 'employee-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('employee-index'); ?>" title="<?php echo $this->translate('Employees'); ?>">
				<i class="fa fa-user"></i> <?php echo $this->translate('Employees'); ?>
			</a>
		</li>
		
		<!-- Labor Rates -->
		<li class="<?php if($this->activeSubMenuItem == 'labor-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('labor-index'); ?>" title="<?php echo $this->translate('Labor Rates'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Labor Rates'); ?>
			</a>
		</li>
		
		<!-- Payment Options -->
		<li class="<?php if($this->activeSubMenuItem == 'payment-option-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('payment-option-index'); ?>" title="<?php echo $this->translate('Payment Options'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Payment Options'); ?>
			</a>
		</li>
		
		<!-- Invoice Options -->
		<li class="<?php if($this->activeSubMenuItem == 'invoice-option-index'):?>active<?php endif;?>">
			<a href="<?php echo $this->url('invoice-option-index'); ?>" title="<?php echo $this->translate('Invoice Options'); ?>">
				<i class="fa fa-dollar"></i> <?php echo $this->translate('Invoice Options'); ?>
			</a>
		</li>
	</ul>
</li>
