<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-file-o" aria-hidden="true"></i>
					<?php echo $this->translate('View File'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'file-download') ):?>
					<a href="<?php echo $this->url('file-download', array('fileId' => $this->clientFileEntity->getFileEntity()->getFileId())); ?>" title="<?php echo $this->translate('Download File'); ?>" class="btn btn-box-tool pull-right"><i class="fa fa-download" aria-hidden="true"></i> <?php echo $this->translate('Download'); ?></a>
					<?php endif; ?>
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'client-file-delete') ):?>
						<a href="<?php echo $this->url('client-file-delete', array('clientFileId' => $this->clientFileEntity->getClientFileId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Delete this file'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body box-profile">
				<h3 class="profile-username"><?php echo $this->clientFileEntity->getFileEntity()->getFileName();?></h3>
				<p class="text-muted"><?php echo $this->clientFileEntity->getFileEntity()->getFileTitle(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">
						<b><?php echo $this->translate('Path'); ?>:</b>
						<a class="pull-right"><?php echo APPLICATION_PATH . '/' .$this->clientFileEntity->getFileEntity()->getFilePath(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Mime Type'); ?>:</b>
						<a class="pull-right"><?php echo $this->clientFileEntity->getFileEntity()->getFileMime(); ?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Size'); ?>:</b>
						<a class="pull-right"><?php echo $this->clientFileEntity->getFileEntity()->getFileSize()?> <?php echo $this->translate('bytes');?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Created'); ?>:</b>
						<a class="pull-right"><?php echo date($this->appConfig()->getConfigDateLong(), $this->clientFileEntity->getFileEntity()->getFileCreate());?></a>
					</li>
					<li class="list-group-item">
						<b><?php echo $this->translate('Created By'); ?>:</b>
						<a class="pull-right"><?php echo $this->clientFileEntity->getAuthEntity()->getAuthName(); ?></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>