<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InvoiceItem\Service\ItemServiceInterface'               => __DIR__ . '/src/InvoiceItem/Service/ItemServiceInterface.php',
    'InvoiceItem\Service\ItemService'                        => __DIR__ . '/src/InvoiceItem/Service/ItemService.php',
    'InvoiceItem\Service\Factory\ItemServiceFactory'         => __DIR__ . '/src/InvoiceItem/Service/Factory/ItemServiceFactory.php',
    'InvoiceItem\Controller\DeleteController'                => __DIR__ . '/src/InvoiceItem/Controller/DeleteController.php',
    'InvoiceItem\Controller\CreateController'                => __DIR__ . '/src/InvoiceItem/Controller/CreateController.php',
    'InvoiceItem\Controller\UpdateController'                => __DIR__ . '/src/InvoiceItem/Controller/UpdateController.php',
    'InvoiceItem\Controller\Factory\CreateControllerFactory' => __DIR__ . '/src/InvoiceItem/Controller/Factory/CreateControllerFactory.php',
    'InvoiceItem\Controller\Factory\DeleteControllerFactory' => __DIR__ . '/src/InvoiceItem/Controller/Factory/DeleteControllerFactory.php',
    'InvoiceItem\Form\ItemForm'                              => __DIR__ . '/src/InvoiceItem/Form/ItemForm.php',
    'InvoiceItem\Mapper\ItemMapperInterface'                 => __DIR__ . '/src/InvoiceItem/Mapper/ItemMapperInterface.php',
    'InvoiceItem\Mapper\ItemMapper'                          => __DIR__ . '/src/InvoiceItem/Mapper/ItemMapper.php',
    'InvoiceItem\Mapper\Factory\ItemMapperFactory'           => __DIR__ . '/src/InvoiceItem/Mapper/Factory/ItemMapperFactory.php',
    'InvoiceItem\Hydrator\ItemHydrator'                      => __DIR__ . '/src/InvoiceItem/Hydrator/ItemHydrator.php',
    'InvoiceItem\Entity\ItemEntity'                          => __DIR__ . '/src/InvoiceItem/Entity/ItemEntity.php',
    'InvoiceItem\Module'                                     => __DIR__ . '/Module.php',
);
