<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-life-ring" aria-hidden="true"></i>
					<?php echo $this->translate('Edit Support Ticket'); ?>
				</h3>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('ticketTitle'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12">
						<?php $element = $this->form->get('ticketText'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
              	<div class="row">
              		<div class="col-xs-12 col-sm-3">
						<?php $element = $this->form->get('ticketStatus'); ?>
						<div class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
							<label class="control-label"><?php echo $element->getLabel() ?></label>
							<?php echo $this->formElement($element); ?>
							<?php if($this->formElementErrors($element)): ?>
								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
							<?php endif; ?>
						</div>
              		</div>
              	</div>
              	
				<?php echo $this->formElement($this->form->get('ticketId')); ?>
				<?php echo $this->formElement($this->form->get('clientId')); ?>
				<?php echo $this->formElement($this->form->get('userId')); ?>
				<?php echo $this->formElement($this->form->get('ticketDateOpen')); ?>
				<?php echo $this->formElement($this->form->get('ticketDateClose')); ?>
				<?php echo $this->formSubmit($this->form->get('submit')); ?>
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>
<script>
  $(function () {
	  $("#ticketText").wysihtml5();
  });
 </script>