<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="fa fa-life-ring" aria-hidden="true"></i>
					<?php echo $this->translate('View Support Ticket'); ?>
				</h3>
				<div class="box-tools">
					<?php if($this->ticketEntity->getTicketStatus() != 'Closed'): ?>
					
					<a href="#"  data-toggle="modal" data-target="#ticketNoteCloseModal"  title="<?php echo $this->translate('Close this ticket'); ?>" class="btn btn-box-tool">
						<i class="fa fa-times"></i> <?php echo $this->translate('Close'); ?>
					</a>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'ticket-delete') ):?>
					<a href="<?php echo $this->url('ticket-delete', array('ticketId' => $this->ticketId, 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Delete this ticket'); ?>" class="btn btn-box-tool">
						<i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?>
					</a>
					<?php endif;?>
					
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'workorder-create') ):?>
					<a href="<?php echo $this->url('workorder-create', array('clientId' => $this->clientId), array('query' => array('ticketId' => $this->ticketId)));?>" title="<?php echo $this->translate('Create work order'); ?>" class="btn btn-box-tool">
						<i class="fa fa-wrench"></i> <?php echo $this->translate('Work Order'); ?>
					</a>
					<?php endif;?>
					<?php else: ?>
					<a href="" title="<?php echo $this->translate('Open Ticket')?>" class="btn btn-box-tool">
						<?php echo $this->translate('Open');?>
					</a>
					<?php endif;
					?>
					<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'ticket-update') ):?>
					<a href="<?php echo $this->url('ticket-update', array('ticketId' => $this->ticketId, 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Edit this ticket'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif;?>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-8">
						<p><b><?php echo $this->translate('Title'); ?>:</b> <?php echo $this->ticketEntity->getTicketTitle(); ?></p>
						<p><?php echo $this->ticketEntity->getTicketText(); ?></p>
					</div>
					<div class="col-xs-4">
						<div class="panel">
							<div class="panel-body">
								<ul class="list-group list-group-unbordered">
									<li class="list-group-item">
										<b><?php echo $this->translate('Status');?>:</b>
										<span class="pull-right">
											<?php echo $this->ticketEntity->getTicketStatus(); ?>
										</span>
									</li>
									<li class="list-group-item">
										<b><?php echo $this->translate('Created By');?>:</b>
										<span class="pull-right">
											<?php if( $this->acl()->isAllowed($this->identity()->getAuthRole(), 'user-view') ):?>
                                			<a href="<?php echo $this->url('user-view', array('clientId' => $this->clientId, 'userId' => $this->ticketEntity->getUserId())); ?>" title="<?php echo $this->translate('View this user');?>">
                                				<?php echo $this->ticketEntity->getUserEntity()->getUserNameFirst(); ?> <?php echo $this->ticketEntity->getUserEntity()->getUserNameLast(); ?>
                                			</a>
                                			<?php else: ?>
                                				<?php echo $this->ticketEntity->getUserEntity()->getUserNameFirst(); ?> <?php echo $this->ticketEntity->getUserEntity()->getUserNameLast(); ?>
                                			<?php endif; ?>
                                		</span>
									</li>
									<li class="list-group-item">
										<b><?php echo $this->translate('Created');?>:</b>
										<span class="pull-right">
											<?php echo date($this->appConfig()->getConfigdateLong(), $this->ticketEntity->getTicketDateOpen()); ?>
										</span>
									</li>
									<li class="list-group-item">
										<b><?php echo $this->translate('Closed');?>:</b>
										<span class="pull-right">
										<?php if($this->ticketStatus == "Closed"): ?>
											<?php echo date($this->appConfig()->getConfigdateLong(), $this->ticketEntity->getTicketDateClosed()); ?>
										<?php else: ?>
											<?php echo $this->translate('N/A'); ?>
										<?php endif; ?>
										</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->ticketNote($this->clientId, $this->ticketId, $this->ticketEntity->getTicketStatus()); ?>

<div class="modal fade" id="ticketNoteCloseModal" role="dialog" aria-labelledby="hostModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel"><i class="fa fa-life-ring" aria-hidden="true"></i> <?php echo $this->translate('Close Ticket')?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Are you sure you want to close this ticket?');?></p>
			</div>
			<div class="modal-footer">
				<form method="post" action="<?php echo $this->url('ticket-close', array('ticketId' => $this->ticketId, 'clientId' => $this->ticketId));?>">
                     <input type="submit" name="delete_confirmation" class="btn btn-danger" value="yes">
                     <input type="submit" name="delete_confirmation" class="btn btn-primary" value="no">
                </form>
			</div>
		</div>
	</div>
</div>