<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-lock"></i>
					<?php echo $this->translate('View Password'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'password-delete') ):?>
					<a href="<?php echo $this->url('password-delete', array('passwordId' => $this->passwordEntity->getPasswordId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Delete this password'); ?>" class="btn btn-box-tool"><i class="fa fa-times"></i> <?php echo $this->translate('Delete'); ?></a>
					<?php endif;?>
					
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'password-update') ):?>
					<a href="<?php echo $this->url('password-update', array('passwordId' => $this->passwordEntity->getPasswordId(), 'clientId' => $this->clientId));?>" title="<?php echo $this->translate('Edit this password'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<h3 class="profile-username"><?php echo $this->passwordEntity->getPasswordTitle(); ?></h3>
				<p class="text-muted"><?php echo $this->passwordEntity->getPasswordLocation(); ?></p>
				<ul class="list-group list-group-unbordered">
					<li class="list-group-item">	
						<b><?php echo $this->translate('Password'); ?></b> <a class="pull-right" data-toggle="modal" data-target="#myModal">******** <i class="fa fa-search"></i></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('View Password'); ?></h4>
      </div>
      <div class="modal-body">
       	<p class="text-centered"><b><?php echo $this->translate('Password'); ?>:</b> 
       		<?php echo $this->decrypt($this->passwordEntity->getPasswordPassword()); ?>
       	</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
      </div>
    </div>
  </div>
</div>
	