<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-desktop"></i>
					<?php echo $this->translate('Hosts'); ?>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('host-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new host'); ?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
				</div>
			</div>
		</div>
	</div>
</div>