<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<div class="box">
	<div class="box-body">

		<section id="introduction">
			<h2 class="page-header">
				<a href="#introduction">Introduction</a>
			</h2>
			<p class="lead">
				<b>PacificNM</b> is an open source service management solution for
				IT service companies. PacificNM is built and backed by a profesional
				IT provider so we know what you need and what you want.
			</p>
		</section>

		<section id="introduction">
			<h2 class="page-header">
				<a href="#introduction">Current Status &amp; Issues</a>
			</h2>
			<p class="lead">
				The source code for PacificNM is hosted at <a href="https://github.com/pacificnm/pnm" title="View the code" target="_blank">GitHub</a>
			</p>
			<h3 class="profile-username">Current Known Issues</h3>
			<ul class="list-group list-group-unbordered">
			<?php foreach($this->paginator as $entity): ?>
				
				<li class="list-group-item">
					<a href="<?php echo $entity->getHtmlUrl(); ?>" title="View this issue" target="_blank">
					<?php echo $entity->getTitle();?>
					</a>
					<p><?php echo $entity->getBody();?></p>
				</li>
			<?php endforeach; ?>
			</ul>
		</section>		

		<section id="plugins">
			<h2 class="page-header">
				<a href="#plugins">Plugins</a>
			</h2>
			<p class="lead">PacificNM makes use of the following plugins. For
				documentation, updates or license information, please visit the
				provided links.</p>
			<a href="https://almsaeedstudio.com/" target="_blank">AdminLTE Control Panel Template</a>
			<div class="row bring-up">
				<div class="col-xs-12 col-sm-3">
					<ul class="list-unstyled">
						<li><h4>Charts</h4></li>
						<li><a href="http://www.chartjs.org/" target="_blank">ChartJS</a></li>
						<li><a href="http://www.flotcharts.org/" target="_blank">Flot</a></li>
						<li><a href="http://morrisjs.github.io/morris.js/" target="_blank">Morris.js</a></li>
						<li><a href="http://omnipotent.net/jquery.sparkline/"
							target="_blank">Sparkline</a></li>
					</ul>
				</div>
				<!-- /.col -->
				<div class="col-xs-12 col-sm-3">
					<ul class="list-unstyled">
						<li><h4>Form Elements</h4></li>
						<li><a href="https://github.com/seiyria/bootstrap-slider/">Bootstrap
								Slider</a></li>
						<li><a href="http://ionden.com/a/plugins/ion.rangeSlider/en.html"
							target="_blank">Ion Slider</a></li>
						<li><a href="http://bootstrap-datepicker.readthedocs.org/"
							target="_blank">Date Picker</a></li>
						<li><a href="http://www.daterangepicker.com/" target="_blank">Date
								Range Picker</a></li>
						<li><a href="http://mjolnic.com/bootstrap-colorpicker/"
							target="_blank">Color Picker</a></li>
						<li><a href="https://github.com/jdewit/bootstrap-timepicker/"
							target="_blank">Time Picker</a></li>
						<li><a href="http://fronteed.com/iCheck/" target="_blank">iCheck</a></li>
						<li><a href="https://github.com/RobinHerbots/jquery.inputmask/"
							target="_blank">Input Mask</a></li>
					</ul>
				</div>
				<!-- /.col -->
				<div class="col-xs-12 col-sm-3">
					<ul class="list-unstyled">
						<li><h4>Editors</h4></li>
						<li><a
							href="https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/"
							target="_blank">Bootstrap WYSIHTML5</a></li>
						<li><a href="http://ckeditor.com/" target="_blank">CK Editor</a></li>
					</ul>
				</div>
				<!-- /. col -->
				<div class="col-xs-12 col-sm-3">
					<ul class="list-unstyled">
						<li><h4>Other</h4></li>
						<li><a
							href="https://datatables.net/examples/styling/bootstrap.html"
							target="_blank">DataTables</a></li>
						<li><a href="http://fullcalendar.io/" target="_blank">Full
								Calendar</a></li>
						<li><a href="http://jqueryui.com/" target="_blank">jQuery UI</a></li>
						<li><a href="http://anthonyterrien.com/knob/" target="_blank">jQuery
								Knob</a></li>
						<li><a href="http://jvectormap.com/" target="_blank">jVector Map</a></li>
						<li><a href="http://rocha.la/jQuery-slimScroll/" target="_blank">Slim
								Scroll</a></li>
						<li><a href="http://github.hubspot.com/pace/docs/welcome/"
							target="_blank">Pace</a></li>
					</ul>
				</div>
			</div>
		</section>


		<section id="license">
			<h2 class="page-header">
				<a href="#license">License</a>
			</h2>
			<h3>PacificNM</h3>
			<p class="lead">
		PacificNM is an open source project that is licensed under the MIT
		license. Copyright (c)
		2013 - <?php echo date("Y", time()); ?> Pacific Network Management
	
	</p>
			<p class="lead">Permission is hereby granted, free of charge, to any
				person obtaining a copy of this software and associated
				documentation files (the "Software"), to deal in the Software
				without restriction, including without limitation the rights to use,
				copy, modify, merge, publish, distribute, sublicense, and/or sell
				copies of the Software, and to permit persons to whom the Software
				is furnished to do so, subject to the following conditions:</p>

			<p class="lead">The above copyright notice and this permission notice
				shall be included in all copies or substantial portions of the
				Software.</p>

			<p class="lead">THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF
				ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
				WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
				NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
				BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
				ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
				CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
				SOFTWARE.</p>
		</section>
	</div>
</div>