<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license   https://www.pacificnm.com/license/new-bsd New BSD License
 */
?>
<?php $address = urlencode($this->locationEntity->getLocationStreet().'+'.$this->locationEntity->getLocationCity().'+'.$this->locationEntity->getLocationState().'+'.$this->locationEntity->getLocationZip());?>
<style>
    #map-outer {  
        height: 440px; 
	    padding: 20px; 
        margin-bottom: 20px; 
    }
    #map-container { height: 400px }
    @media all and (max-width: 991px) {
        #map-outer  { height: 650px }
    }
</style>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-globe"></i>
					<?php echo $this->translate('View Location'); ?>
				</h3>
				<div class="box-tools">
					<a href="https://www.google.com/maps/dir/<?php echo $this->translate('Current+Location');?>/<?php echo $address?>" title="<?php echo $this->translate('Driving Directions'); ?>" target="_blank" class="btn btn-box-tool"><i class="fa fa-car" aria-hidden="true"></i> <?php echo $this->translate('Directions'); ?></a>
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'location-update') ):?>
					<a href="<?php echo $this->url('location-update', array('clientId' => $this->clientId, 'locationId' => $this->locationEntity->getLocationId())); ?>" title="<?php echo $this->translate('Edit this location'); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-12">
						<h3 class="profile-username">
    						<?php echo $this->locationEntity->getLocationStreet(); ?>
    						<?php echo $this->locationEntity->getLocationCity()?>,
    						<?php echo $this->locationEntity->getLocationState(); ?>
    						<?php echo $this->locationEntity->getLocationZip(); ?>
    					</h3>
					</div>
				</div>
				<div class="row">
					<div id="map-outer" class="col-xs-12">
						<div id="map-container" class="col-xs-12"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
var geocoder;
var map;

function initMap() {
    var map = new google.maps.Map(document.getElementById('map-container'), {
      zoom: 16,
      center: {lat: 42.4390, lng: 123.3284},
      zoomControl: false,
      scaleControl: false,
      scrollwheel: false,
      disableDoubleClickZoom: true,
      panControl: false,
      draggable: false,
      mapTypeControl: false,
      streetViewControl: false,
    });
    var geocoder = new google.maps.Geocoder();

    geocodeAddress(geocoder, map);
  }

function geocodeAddress(geocoder, resultsMap) {
    var address = '<?php echo $this->locationEntity->getLocationStreet(); ?> <?php echo $this->locationEntity->getLocationCity()?>, <?php echo $this->locationEntity->getLocationState(); ?> <?php echo $this->locationEntity->getLocationZip(); ?>';
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }



	
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->appConfig()->getConfigGoogleApiKey(); ?>&callback=initMap">
</script>