<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">	
					<i class="fa fa-dollar"></i>
					<?php echo $this->translate('Bill'); ?>
				</h3>
				<div class="box-tools">
				
				</div>
			</div>
			<?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('There are no un-paid bills'); ?></p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Due Date');?></th>
							<th><?php echo $this->translate('Vendor'); ?></th>
							<th><?php echo $this->translate('Amount'); ?></th>
							<th><?php echo $this->translate('Balance'); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($this->paginator as $billEntity): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('vendor-bill-view', array('vendorId' => $billEntity->getVendorId(), 'vendorBillId' => $billEntity->getVendorBillId()));?>" title="<?php Echo $this->translate('View this bill')?>">
									<?php echo date($this->appConfig()->getConfigDateShort(), $billEntity->getVendorBillDateDue());?>
								</a>
							</td>
							<td>
								<a href="<?php echo $this->url('vendor-view', array('vendorId' => $billEntity->getVendorId())); ?>" title="<?php echo $this->translate('View this vendor'); ?>">
									<?php echo $billEntity->getVendorEntity()->getVendorName();?>
								</a>
							</td>
							<td><?php echo $this->currencyFormat($billEntity->getVendorBillAmount(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></td>
							<td><?php echo $this->currencyFormat($billEntity->getVendorBillBalance(), $this->appConfig()->getConfigCurrency(), $this->appConfig()->getConfigLang());?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>