<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pnm for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubTitle; ?></small>
				</h3>
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'subscription-create') ):?>
						<a href="<?php echo $this->url('subscription-create', array('clientId' => $this->clientId));?>" 
							title="<?php echo $this->translate('Create new work order');?>" class="btn btn-box-tool">
							<i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?>
						</a>
					<?php endif; ?>
				</div>
				
				<?php if($this->paginator->count() == 0): ?>
				<div class="box-body">
					<div class="alert alert-info">
						<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No Subscriptions'); ?></p>
					</div> 
				</div>
				<?php else: ?>
				<div class="box-body table-responsive no-padding">
					<table class="table table-bordered table-hover table-striped table-condensed">
    					<thead>
    						<tr>
    							<th><?php echo $this->translate('Subscription Id'); ?></th>
    							<th><?php echo $this->translate('Due Date'); ?></th>
    							<th><?php echo $this->translate('End Date'); ?></th>
    							<th><?php echo $this->translate('Schedule'); ?></th>
    							<th><?php echo $this->translate('Status'); ?></th>
    						</tr>
    					</thead>
    					<tbody>
    					<?php foreach($this->paginator as $entity): ?>
    						<tr>
    							<td>
    								<a href="<?php echo $this->url('subscription-view', array('subscriptionId' => $entity->getSubscriptionId(), 'clientId' => $entity->getClientId())); ?>" 
    									title="<?php echo $this->translate('View this subscription'); ?>">
    									<?php echo $entity->getSubscriptionId(); ?>
    								</a>
    							</td>
    							<td><?php echo date($this->appConfig()->getConfigDateShort(), $entity->getSubscriptionDateDue()); ?></td>
    							<td><?php echo date($this->appConfig()->getConfigDateShort(), $entity->getSubscriptionDateEnd()); ?></td>
    							<td><?php echo $entity->getSubscriptionScheduleEntity()->getSubscriptionScheduleName(); ?></td>
    							<td><?php echo $entity->getSubscriptionStatusEntity()->getSubscriptionStatusName(); ?></td>
    						</tr>
    					<?php endforeach; ?>
    					</tbody>
    				</table>
				</div>
				<?php endif;?>
			</div>
		</div>
	</div>
</div>