
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-line-chart"></i>
					<?php echo $this->translate('Subscriptions'); ?>
				</h3>
				<div class="box-tools">
					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'subscription-create') ):?>
						<a href="<?php echo $this->url('subscription-create', array('clientId' => $this->clientId));?>" title="<?php echo $this->translate('Create new work order');?>" class="btn btn-box-tool"><i class="fa fa-plus"></i> <?php echo $this->translate('New'); ?></a>
					<?php endif; ?>
				</div>
				<div class="box-body">
				<?php if($this->paginator->count() == 0): ?>
					<div class="alert alert-info">
						<p><i class="fa fa-info-circle"></i> <?php echo $this->translate('No Subscriptions'); ?></p>
					</div> 
				<?php else: ?>
				<ul class="list-group list-group-unbordered">
				<?php foreach($this->paginator as $entity): ?>
					<li class="list-group-item">
						<h3 class="profile-username">
    					<?php if( $this->layout()->acl->isAllowed($this->identity()->getAuthRole(), 'subscription-view') ):?>
    					<a href="<?php echo $this->url('subscription-view', array('clientId' => $this->clientId, 'subscriptionId' => $entity->getSubscriptionId())); ?>" title="<?php echo $this->translate('View this subscription'); ?>">
    						<?php echo $entity->getProductEntity()->getProductName(); ?>
    					</a>
    					<?php else: ?>
    						<?php echo $entity->getProductEntity()->getProductName(); ?>
    					<?php endif;?>
    					<span class="pull-right badge"><?php echo $entity->getSubscriptionStatusEntity()->getSubscriptionStatusName();?></span>
    					</h3>
    					<div class="row">
    						<div class="col-xs-12">
    							<p>
        							<b><?php echo $this->translate('Due Date')?>:</b>
        							<span class="pull-right">
        								<?php echo date($this->appConfig()->getConfigDateShort(), $entity->getSubscriptionDateDue()); ?>
        							</span>
        						</p>
    						</div>
    					</div>
    					<div class="row">
    						<div class="col-xs-12">
    							<p>
        							<b><?php echo $this->translate('End Date')?>:</b>
        							<span class="pull-right">
        								<?php echo date($this->appConfig()->getConfigDateShort(), $entity->getSubscriptionDateEnd()); ?>
        							</span>
        						</p>
    						</div>
    					</div>
					</li>
				<?php endforeach;?>
				</ul>
				<?php endif;?>
				</div>
			</div>
		</div>
	</div>
</div>