<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Install\Service\InstallService'                       => __DIR__ . '/src/Install/Service/InstallService.php',
    'Install\Service\Factory\InstallServiceFactory'        => __DIR__ . '/src/Install/Service/Factory/InstallServiceFactory.php',
    'Install\Service\InstallServiceInterface'              => __DIR__ . '/src/Install/Service/InstallServiceInterface.php',
    'Install\Controller\ConfigController'                  => __DIR__ . '/src/Install/Controller/ConfigController.php',
    'Install\Controller\AdminController'                   => __DIR__ . '/src/Install/Controller/AdminController.php',
    'Install\Controller\IndexController'                   => __DIR__ . '/src/Install/Controller/IndexController.php',
    'Install\Controller\CompleteController'                => __DIR__ . '/src/Install/Controller/CompleteController.php',
    'Install\Controller\Factory\CompleteControllerFactory' => __DIR__ . '/src/Install/Controller/Factory/CompleteControllerFactory.php',
    'Install\Controller\Factory\ConfigControllerFactory'   => __DIR__ . '/src/Install/Controller/Factory/ConfigControllerFactory.php',
    'Install\Controller\Factory\IndexControllerFactory'    => __DIR__ . '/src/Install/Controller/Factory/IndexControllerFactory.php',
    'Install\Controller\Factory\AdminControllerfactory'    => __DIR__ . '/src/Install/Controller/Factory/AdminControllerfactory.php',
    'Install\Controller\Factory\DatabaseControllerFactory' => __DIR__ . '/src/Install/Controller/Factory/DatabaseControllerFactory.php',
    'Install\Controller\DatabaseController'                => __DIR__ . '/src/Install/Controller/DatabaseController.php',
    'Install\Form\ConfigForm'                              => __DIR__ . '/src/Install/Form/ConfigForm.php',
    'Install\Form\AdminForm'                               => __DIR__ . '/src/Install/Form/AdminForm.php',
    'Install\Form\DatabaseForm'                            => __DIR__ . '/src/Install/Form/DatabaseForm.php',
    'Install\Mapper\InstallMapper'                         => __DIR__ . '/src/Install/Mapper/InstallMapper.php',
    'Install\Mapper\InstallMapperInterface'                => __DIR__ . '/src/Install/Mapper/InstallMapperInterface.php',
    'Install\Mapper\Factory\InstallMapperFactory'          => __DIR__ . '/src/Install/Mapper/Factory/InstallMapperFactory.php',
    'Install\Module'                                       => __DIR__ . '/Module.php',
);
