<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'History\Service\HistoryService'                      => __DIR__ . '/src/History/Service/HistoryService.php',
    'History\Service\Factory\HistoryServiceFactory'       => __DIR__ . '/src/History/Service/Factory/HistoryServiceFactory.php',
    'History\Service\HistoryServiceInterface'             => __DIR__ . '/src/History/Service/HistoryServiceInterface.php',
    'History\Controller\Plugin\SetHistory'                => __DIR__ . '/src/History/Controller/Plugin/SetHistory.php',
    'History\Controller\Plugin\Factory\SetHistoryFactory' => __DIR__ . '/src/History/Controller/Plugin/Factory/SetHistoryFactory.php',
    'History\View\Helper\GetAuthHistory'                  => __DIR__ . '/src/History/View/Helper/GetAuthHistory.php',
    'History\View\Helper\Factory\GetAuthHistoryFactory'   => __DIR__ . '/src/History/View/Helper/Factory/GetAuthHistoryFactory.php',
    'History\Mapper\HistoryMapper'                        => __DIR__ . '/src/History/Mapper/HistoryMapper.php',
    'History\Mapper\Factory\HistoryMapperFactory'         => __DIR__ . '/src/History/Mapper/Factory/HistoryMapperFactory.php',
    'History\Mapper\HistoryMapperInterface'               => __DIR__ . '/src/History/Mapper/HistoryMapperInterface.php',
    'History\Hydrator\HistoryHydrator'                    => __DIR__ . '/src/History/Hydrator/HistoryHydrator.php',
    'History\Entity\HistoryEntity'                        => __DIR__ . '/src/History/Entity/HistoryEntity.php',
    'History\Module'                                      => __DIR__ . '/Module.php',
);
